'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {validate}=require('../site-engine/index.cjs');const {validateSubmission,toBusinessTruth}=require('../owner-onboarding/index.cjs');const {validateReview,verifyBinding}=require('../operator-review/index.cjs');
const ROOT=path.resolve(__dirname,'../..');const encode=v=>JSON.stringify(v,null,2)+'\n';const sha=value=>crypto.createHash('sha256').update(Buffer.isBuffer(value)?value:typeof value==='string'?value:encode(value)).digest('hex');const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function authorize(submission,truth,review){
 validateSubmission(submission);validate('business-truth',truth);validateReview(review);verifyBinding(submission,review);
 const expected=toBusinessTruth(submission);if(sha(expected)!==sha(truth)){const e=new Error('BusinessTruth does not match the reviewed OwnerSubmission');e.code='TRUTH_MISMATCH';throw e;}
 if(review.decision!=='approved_private_demo'||review.capabilities.may_generate_private_demo!==true){const e=new Error('A current private-demo approval is required');e.code='PRIVATE_DEMO_BLOCKED';throw e;}
 if(review.capabilities.may_publish||review.capabilities.may_index||truth.publication_policy.may_index_demo){const e=new Error('Public capability is forbidden in private demo');e.code='PUBLICATION_BLOCKED';throw e;}
 if(!truth.sources.every(s=>s.source_type==='owner'&&s.rights_status==='needs_review')){const e=new Error('Private owner source policy mismatch');e.code='SOURCE_POLICY_MISMATCH';throw e;}
 return {submission,truth,review,hashes:{owner_submission:sha(submission),business_truth:sha(truth),operator_review:sha(review)}};
}
const actionLabels={schedule_conversation:'Agendar una conversación',explore_catalog:'Explorar la selección',request_valuation:'Solicitar una valoración',visit_project:'Conocer el proyecto',request_information:'Pedir información'};
function render(authorized){
 const {submission:s,truth:t,review:r}=authorized,name=t.identity.display_name.replace(/\s*[—-]\s*FICTICIO$/i,''),areas=s.service_areas.join(' · '),contact=t.contacts.emails[0]?.value||t.contacts.phones[0]?.value||'Pendiente de activación',services=t.services.map((service,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h3>${esc(service.name)}</h3><p>${esc(service.description||'')}</p></div></article>`).join('');
 const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="description" content="${esc(t.description)}"><title>${esc(name)} · Demo privada</title><link rel="stylesheet" href="styles.css"></head><body><div class="private-bar"><span></span> DEMO PRIVADA · INFORMACIÓN DECLARADA POR EL PROPIETARIO · NO PUBLICADA</div><header><a class="brand" href="index.html"><b>${esc(name.charAt(0))}</b><span>${esc(name)}<small>Vista privada para revisión</small></span></a><nav><a href="#enfoque">Enfoque</a><a href="#servicios">Servicios</a><a href="#contacto">Contacto</a></nav><a class="trace" href="trazabilidad.html">Ver trazabilidad ↗</a></header><main><section class="hero"><div><p class="eyebrow">${esc(t.identity.primary_category.replaceAll('-',' '))} · ${esc(areas)}</p><h1>${esc(name)}</h1><p class="lead">${esc(t.description)}</p><a class="button" href="#servicios">Conocer la propuesta <span>↓</span></a><div class="approval"><i>✓</i><p><b>Demo privada aprobada</b><br>Revisión ${esc(r.review_id.slice(-12))}</p></div></div><figure><img src="assets/courtyard.png" alt="Imagen conceptual sintética"><figcaption>Imagen conceptual · pendiente de activos finales</figcaption></figure></section><section class="manifesto" id="enfoque"><p class="eyebrow">Para quién trabajamos</p><blockquote>${esc(s.business_profile.ideal_customer)}</blockquote><div><span>Especialidad declarada</span><p>${esc(s.business_profile.specialty)}</p></div></section><section class="services" id="servicios"><div class="section-head"><div><p class="eyebrow">Oferta confirmada</p><h2>Un servicio claro para cada decisión.</h2></div><p>El contenido procede del expediente del propietario y permanece sujeto a revisión antes de cualquier publicación.</p></div><div class="service-list">${services}</div></section><section class="coverage"><div><p class="eyebrow">Cobertura declarada</p><h2>${esc(areas)}</h2></div><p>La demo organiza el alcance del negocio sin añadir ubicaciones, credenciales ni resultados que no estén en BusinessTruth.</p></section><section class="contact" id="contacto"><div><p class="eyebrow">Siguiente paso previsto</p><h2>${esc(actionLabels[s.business_profile.primary_action]||'Conversar')}</h2><p>Canal declarado: <strong>${esc(contact)}</strong></p></div><span aria-disabled="true">Contacto desactivado en demo privada</span></section></main><footer><div><b>${esc(name)}</b><span>Demo privada · noindex · sin publicación</span></div><a href="trazabilidad.html">Revisar fuentes y autorización</a></footer></body></html>`;
 const trace=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Trazabilidad · ${esc(name)}</title><link rel="stylesheet" href="styles.css"></head><body><div class="private-bar"><span></span> TRAZABILIDAD DE DEMO PRIVADA · NO PUBLICADA</div><main class="trace-page"><a href="index.html">← Volver a la demo</a><p class="eyebrow">Cadena de autorización</p><h1>Qué está aprobado<br>y qué sigue bloqueado.</h1><div class="trace-grid"><article><span>01</span><h2>Propietario</h2><p>Expediente confirmado el ${esc(s.owner_confirmed_at)}.</p><code>${authorized.hashes.owner_submission}</code></article><article><span>02</span><h2>BusinessTruth</h2><p>Hechos derivados sin diferencias respecto del expediente.</p><code>${authorized.hashes.business_truth}</code></article><article><span>03</span><h2>Operador</h2><p>${esc(r.review_id)} aprobó únicamente una demo privada.</p><code>${authorized.hashes.operator_review}</code></article></div><section class="permissions"><div><span>Demo privada</span><b>Permitida</b></div><div><span>Publicación</span><b>Bloqueada</b></div><div><span>Indexación</span><b>Bloqueada</b></div></section><p class="trace-note">Cualquier cambio en los datos invalida los hashes y exige una nueva revisión.</p></main></body></html>`;
 return {html,trace};
}
function build({submission,truth,review,outputDirectory,created_at='2026-09-30T16:00:00Z'}){
 const authorized=authorize(submission,truth,review),rendered=render(authorized);const css=fs.readFileSync(path.join(__dirname,'styles.css'),'utf8');const image=fs.readFileSync(path.join(ROOT,'pilot/assets/courtyard.png'));const files={'index.html':Buffer.from(rendered.html),'trazabilidad.html':Buffer.from(rendered.trace),'styles.css':Buffer.from(css),'assets/courtyard.png':image};const buildId='pdb-'+sha(encode({version:'0.8.0',hashes:authorized.hashes,artifacts:Object.fromEntries(Object.entries(files).map(([k,v])=>[k,sha(v)]))})).slice(0,20),destination=path.join(outputDirectory,submission.business_id,buildId);fs.mkdirSync(path.join(destination,'assets'),{recursive:true});for(const [name,bytes] of Object.entries(files)){fs.mkdirSync(path.dirname(path.join(destination,name)),{recursive:true});fs.writeFileSync(path.join(destination,name),bytes);}const manifest={schema_version:'0.1.0',build_id:buildId,business_id:submission.business_id,site_id:submission.business_id,source_hashes:authorized.hashes,review_id:review.review_id,mode:'private_demo',indexing:'noindex',publication:{status:'not_published',url:null},created_at,entrypoint:'index.html',artifacts:Object.entries(files).map(([name,bytes])=>({path:name,media_type:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'image/png',sha256:sha(bytes),bytes:bytes.length}))};validate('private-demo-build',manifest);fs.writeFileSync(path.join(destination,'private-demo-build.json'),encode(manifest));return {destination,manifest,authorized};
}
module.exports={authorize,render,build,sha,encode};
