'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');const {buildPilotRegistry,assertEligible,assertCatalogAssets,createUsageIndex,revokeAsset}=require('../packages/asset-publication/index.cjs');const {buildAll,renderProfile}=require('../packages/real-estate-renderer/index.cjs');const {server}=require('../scripts/serve-asset-usage.cjs');
const profiles=JSON.parse(fs.readFileSync(path.join(ROOT,'pilot/profiles.json'),'utf8')).profiles,catalog=JSON.parse(fs.readFileSync(path.join(ROOT,'pilot/catalog.json'),'utf8'));

test('registry derives hashes, bytes and dimensions from three real fixture files',()=>{const registry=buildPilotRegistry(ROOT);assert.equal(registry.assets.length,3);for(const asset of registry.assets){const bytes=fs.readFileSync(path.join(ROOT,'pilot/assets',asset.filename));assert.equal(asset.bytes,bytes.length);assert.equal(asset.content_sha256.length,64);assert(asset.dimensions.width>0&&asset.dimensions.height>0);assert.equal(asset.state,'synthetic_fixture');}});

test('synthetic fixtures are eligible only for local demo',()=>{const registry=buildPilotRegistry(ROOT),id=registry.assets[0].asset_id;assert.equal(assertEligible(registry,id,'local_demo').asset_id,id);assert.throws(()=>assertEligible(registry,id,'private'),error=>error.code==='ASSET_INELIGIBLE');assert.throws(()=>assertEligible(registry,id,'production'),error=>error.code==='ASSET_INELIGIBLE');});

test('catalog references must match registered identifiers, filenames and bytes',()=>{const registry=buildPilotRegistry(ROOT);assert.equal(assertCatalogAssets(registry,catalog,path.join(ROOT,'pilot/assets')),true);const changed=structuredClone(catalog);changed.items[0].asset_id='asset-unknown-demo';assert.throws(()=>assertCatalogAssets(registry,changed,path.join(ROOT,'pilot/assets')),error=>error.code==='ASSET_UNKNOWN');});

test('usage index lists every profile page affected by each asset',()=>{const registry=buildPilotRegistry(ROOT),index=createUsageIndex(registry,profiles,catalog);assert.equal(index.entries.length,3);assert.equal(index.entries[0].usages.length,15);assert.equal(index.entries[1].usages.length,10);assert.equal(new Set(index.entries.flatMap(entry=>entry.usages.map(usage=>usage.site_id))).size,5);});

test('revocation returns exact rebuild impact and removes all eligibility',()=>{const registry=buildPilotRegistry(ROOT),index=createUsageIndex(registry,profiles,catalog),result=revokeAsset(registry,index,'asset-coastal-demo','Retiro sintético solicitado para probar impacto.');const revoked=result.registry.assets.find(asset=>asset.asset_id==='asset-coastal-demo');assert.equal(revoked.state,'revoked');assert.deepEqual(revoked.eligibility,{local_demo:false,private:false,production:false});assert.equal(result.impact.usage_count,15);assert.equal(result.impact.pages.length,10);assert.throws(()=>assertEligible(result.registry,'asset-coastal-demo','local_demo'),error=>error.code==='ASSET_INELIGIBLE');});

test('renderer blocks a revoked referenced asset before writing a profile',()=>{const registry=buildPilotRegistry(ROOT),index=createUsageIndex(registry,profiles,catalog),revoked=revokeAsset(registry,index,'asset-coastal-demo','Revocación sintética para prueba.').registry;assert.throws(()=>renderProfile(profiles[0],path.join(ROOT,'pilot/generated-inputs',profiles[0].id),path.join(ROOT,'dist/revoked-asset-rejected'),catalog,revoked),error=>error.code==='ASSET_INELIGIBLE');});

test('build emits registry, inverse usage index and trace page',()=>{const result=buildAll();for(const name of ['asset-registry.json','asset-usage-index.json','asset-trace.html'])assert.equal(fs.existsSync(path.join(result.destination,name)),true);const trace=fs.readFileSync(path.join(result.destination,'asset-trace.html'),'utf8');assert.match(trace,/Cada imagen sabe dónde aparece/);assert.match(trace,/synthetic fixture/i);});

test('asset usage server is read-only, noindex and offline',async()=>{buildAll();const app=server();await new Promise((resolve,reject)=>{app.once('error',reject);app.listen(0,'127.0.0.1',resolve);});try{const origin=`http://127.0.0.1:${app.address().port}`,page=await fetch(origin);assert.equal(page.status,200);assert.match(page.headers.get('x-robots-tag'),/noindex/);assert.match(page.headers.get('content-security-policy'),/connect-src 'none'/);assert.equal((await fetch(origin,{method:'POST'})).status,405);}finally{await new Promise(resolve=>app.close(resolve));}});
