'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {createAssistedPilot,sha,questions,faqEntries}=require('../packages/assisted-single-business-pilot/index.cjs'),{server}=require('../scripts/serve-assisted-pilot.cjs'),root=path.resolve(__dirname,'..'),candidate={candidate_id:'biz_5',public_name:'Silvana Verano',archetype:'independent-advisor'},actors={manager:{actor_id:'manager',roles:['pilot_manager']},verifier:{actor_id:'verifier',roles:['destination_verifier']},conversation:{actor_id:'conversation',roles:['conversation_designer']},approver:{actor_id:'approver',roles:['contact_approver']},consent:{actor_id:'consent',roles:['consent_designer']},intake:{actor_id:'intake',roles:['intake_designer']},asset:{actor_id:'asset',roles:['asset_operator']},rehearsal:{actor_id:'rehearsal',roles:['rehearsal_operator']},auditor:{actor_id:'auditor',roles:['pilot_auditor']},viewer:{actor_id:'viewer',roles:['viewer']}};function base(){const service=createAssistedPilot({now:()=>new Date('2026-10-02T12:00:00.000Z')}),selection=service.selectCandidate(actors.manager,candidate),script=service.createScript(actors.conversation,selection.selection_id),faq=service.createFaq(actors.conversation,selection.selection_id),consent=service.consentKit(actors.consent,selection.selection_id),form=service.interviewForm(actors.intake,selection.selection_id),folder=service.assetFolder(actors.asset,selection.selection_id),rehearsal=service.rehearse(actors.rehearsal,selection.selection_id);return {service,selection,script,faq,consent,form,folder,rehearsal}}function ready(){const x=base(),destination=x.service.verifyDestination(actors.verifier,x.selection.selection_id,{channel:'whatsapp',masked_destination:'*** *** 321',verification_method:'manual_confirmation',verified:true}),authorization=x.service.authorize(actors.approver,x.selection.selection_id,destination.destination_id,x.script.script_id,{approved:true}),plan=x.service.createContactPlan(actors.manager,x.selection.selection_id,destination.destination_id,x.script.script_id,authorization.authorization_id),gate=x.service.evaluate(actors.auditor,x.selection.selection_id);return {...x,destination,authorization,plan,gate}}
const checks=[['selects exactly biz_5',()=>assert.equal(base().selection.candidate_ref,'biz_5')],
['selection is single business',()=>assert.equal(base().selection.scope,'single_business')],
['other candidate is rejected',()=>assert.throws(()=>createAssistedPilot().selectCandidate(actors.manager,{...candidate,candidate_id:'biz_2'}),{code:'SINGLE_PILOT_SCOPE'})],
['selection requires manager',()=>assert.throws(()=>createAssistedPilot().selectCandidate(actors.viewer,candidate),{code:'ROLE_REQUIRED'})],
['script is invitation only',()=>assert.equal(base().script.claims_mode,'invitation_only')],
['script has six questions',()=>assert.equal(base().script.questions.length,6)],
['script has decline response',()=>assert.match(base().script.decline_response,/Cerrar|Cerramos/)],
['script digest is sha256',()=>assert.match(base().script.script_digest,/^[a-f0-9]{64}$/)],
['faq has six entries',()=>assert.equal(base().faq.entries.length,6)],
['faq escalates two topics',()=>assert.equal(base().faq.escalation_topics.length,2)],
['faq explains private review',()=>assert.match(base().faq.entries[0].answer,/privada/)],
['consent has five scopes',()=>assert.equal(base().consent.scopes.length,5)],
['consent link is not issued',()=>assert.equal(base().consent.external_link_issued,false)],
['consent token policy is one use',()=>assert.equal(base().consent.token_policy,'one_time_hash_only')],
['interview has five sections',()=>assert.equal(base().form.sections.length,5)],
['interview has eight required fields',()=>assert.equal(base().form.required_fields.length,8)],
['interview has no synthetic prefill',()=>assert.equal(base().form.synthetic_prefill,false)],
['asset plan has five folders',()=>assert.equal(base().folder.folders.length,5)],
['asset plan requires rights',()=>assert.equal(base().folder.rights_required,true)],
['upload link is not issued',()=>assert.equal(base().folder.upload_link_issued,false)],
['assets retain 30 days',()=>assert.equal(base().folder.retention_days,30)],
['rehearsal passes eight checks',()=>assert.equal(base().rehearsal.checks.filter(x=>x.passed).length,8)],
['rehearsal is synthetic only',()=>assert.equal(base().rehearsal.synthetic_only,true)],
['rehearsal has zero messages',()=>assert.equal(base().rehearsal.external_messages,0)],
['unverified build gate is blocked',()=>{const x=base();assert.equal(x.service.evaluate(actors.auditor,x.selection.selection_id).status,'blocked')}],
['destination rejects example placeholder',()=>{const x=base();assert.throws(()=>x.service.verifyDestination(actors.verifier,x.selection.selection_id,{channel:'email',masked_destination:'x@example.test',verification_method:'manual_confirmation',verified:true}),{code:'REAL_DESTINATION_REQUIRED'})}],
['destination stores masked value',()=>assert.equal(ready().destination.masked_destination,'*** *** 321')],
['destination records verification method',()=>assert.equal(ready().destination.verification_method,'manual_confirmation')],
['authorization binds script digest',()=>{const x=ready();assert.equal(x.authorization.script_digest,x.script.script_digest)}],
['authorization expires in 24 hours',()=>{const x=ready();assert.equal(new Date(x.authorization.expires_at)-new Date('2026-10-02T12:00:00.000Z'),24*3600e3)}],
['contact plan requires operator',()=>assert.equal(ready().plan.operator_required,true)],
['contact plan never sends automatically',()=>assert.equal(ready().plan.external_delivery,false)],
['approved plan is ready for human send',()=>assert.equal(ready().plan.status,'ready_for_human_send')],
['unapproved plan stays blocked',()=>{const x=base(),d=x.service.verifyDestination(actors.verifier,x.selection.selection_id,{channel:'whatsapp',masked_destination:'*** 111',verification_method:'owner_provided',verified:true}),a=x.service.authorize(actors.approver,x.selection.selection_id,d.destination_id,x.script.script_id,{approved:false});assert.equal(x.service.createContactPlan(actors.manager,x.selection.selection_id,d.destination_id,x.script.script_id,a.authorization_id).status,'blocked')}],
['prepared build has two gate blockers',()=>{const data=JSON.parse(fs.readFileSync(path.join(root,'dist','assisted-pilot','data','assisted-pilot.json')));assert.deepEqual(data.gate.blockers,['verified_destination','explicit_authorization'])}],
['ready gate passes all checks',()=>assert.equal(ready().gate.checks.filter(x=>x.passed).length,8)],
['ready gate allows only human send',()=>assert.equal(ready().gate.external_send_allowed,true)],
['prepared gate forbids send',()=>{const x=base();assert.equal(x.service.evaluate(actors.auditor,x.selection.selection_id).external_send_allowed,false)}],
['handoff is prepared blocked',()=>{const x=base(),g=x.service.evaluate(actors.auditor,x.selection.selection_id),h=x.service.seal(actors.auditor,x.selection.selection_id,g.gate_id);assert.equal(h.status,'prepared_blocked')}],
['ready handoff targets operator',()=>{const x=ready(),h=x.service.seal(actors.auditor,x.selection.selection_id,x.gate.gate_id);assert.equal(h.status,'ready_for_operator')}],
['handoff has zero external messages',()=>{const x=base(),g=x.service.evaluate(actors.auditor,x.selection.selection_id),h=x.service.seal(actors.auditor,x.selection.selection_id,g.gate_id);assert.equal(h.external_messages,0)}],
['handoff has zero publications',()=>{const x=base(),g=x.service.evaluate(actors.auditor,x.selection.selection_id),h=x.service.seal(actors.auditor,x.selection.selection_id,g.gate_id);assert.equal(h.publications,0)}],
['summary contains one selection',()=>assert.equal(base().service.summary().selections,1)],
['summary has zero side effects',()=>{const s=base().service.summary();assert.equal(s.external_messages+s.publications,0)}],
['canonical hash deterministic',()=>assert.equal(sha({b:2,a:1}),sha({a:1,b:2}))],
['build selects Silvana candidate',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(root,'dist','assisted-pilot','data','assisted-pilot.json'))).selection.candidate_ref,'biz_5')],
['build loads no real destination',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(root,'dist','assisted-pilot','data','assisted-pilot.json'))).safety.real_destination_loaded,false)],
['build has no authorization',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(root,'dist','assisted-pilot','data','assisted-pilot.json'))).safety.contact_authorized,false)],
['build rehearsal passes',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(root,'dist','assisted-pilot','data','assisted-pilot.json'))).rehearsal.status,'passed')]];for(const [n,f] of checks)test(n,f);function request(s,url,method='GET'){return new Promise((ok,no)=>{const a=s.address(),q=http.request({hostname:'127.0.0.1',port:a.port,path:url,method},r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>ok({status:r.statusCode,headers:r.headers,body:b}))});q.on('error',no);q.end()})}async function started(){const s=server();await new Promise((ok,no)=>{s.once('error',no);s.listen(0,'127.0.0.1',ok)});return s}test('pilot UI is protected and noindex',async()=>{const s=await started();try{const r=await request(s,'/');assert.equal(r.status,200);assert.match(r.body,/Piloto asistido/);assert.equal(r.headers['x-robots-tag'],'noindex, nofollow')}finally{await new Promise(ok=>s.close(ok))}});test('pilot server rejects writes and traversal',async()=>{const s=await started();try{assert.equal((await request(s,'/','POST')).status,405);assert.equal((await request(s,'/%2e%2e/package.json')).status,404)}finally{await new Promise(ok=>s.close(ok))}});

