'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {createClaimEntitlementService,createLocalBillingAdapter,createUnconfiguredBillingAdapter}=require('../packages/claim-entitlements/index.cjs');const {server}=require('../scripts/serve-claim-entitlements.cjs');
const ROOT=path.resolve(__dirname,'..'),plans=JSON.parse(fs.readFileSync(path.join(ROOT,'commerce/plans.json'),'utf8')),actors={owner:{actor_id:'owner-alpha',role:'owner',tenant_id:'tenant-alpha'},operator:{actor_id:'operator-alpha',role:'operator',tenant_id:'tenant-alpha'},admin:{actor_id:'admin-root',role:'admin',tenant_id:null},system:{actor_id:'system-billing',role:'system',tenant_id:null},other:{actor_id:'owner-beta',role:'owner',tenant_id:'tenant-beta'}};
const service=(options={})=>createClaimEntitlementService({plans,now:()=>new Date('2026-09-30T17:00:00Z'),...options});
function claimWithEvidence(s){let claim=s.startClaim(actors.owner,{tenant_id:'tenant-alpha',business_id:'business-alpha'});claim=s.addEvidence(actors.owner,claim.claim_id,{kind:'domain_control',artifact_sha256:'a'.repeat(64)});claim=s.addEvidence(actors.owner,claim.claim_id,{kind:'phone_callback',artifact_sha256:'b'.repeat(64)});return s.submitClaim(actors.owner,claim.claim_id);}
function verifyClaim(s){let claim=claimWithEvidence(s);for(const evidence of claim.evidence)claim=s.reviewEvidence(actors.operator,claim.claim_id,evidence.evidence_id,'accepted','Prueba sintética aceptada.');return s.decideClaim(actors.operator,claim.claim_id,'verified','Dos factores independientes aceptados.');}
function billing(status='active',time='2026-09-30T17:01:00Z',extra={}){return {synthetic:true,tenant_id:'tenant-alpha',subscription_id:'subscription-'+'c'.repeat(24),plan_ref:'plan-pilot',type:status==='active'?'subscription.activated':`subscription.${status}`,new_status:status,occurred_at:time,idempotency_key:`evt-${status}-${time}`,...extra};}
test('technical plan catalog contains no prices or commercial commitments',()=>{for(const plan of plans){assert.equal(plan.status,'draft');assert.equal(plan.commercial_terms_ref,null);assert.equal(/price|amount|currency/i.test(JSON.stringify(plan)),false);}});
test('claim submission requires two independent evidence kinds',()=>{const s=service(),claim=s.startClaim(actors.owner,{tenant_id:'tenant-alpha',business_id:'business-alpha'}),one=s.addEvidence(actors.owner,claim.claim_id,{kind:'domain_control',artifact_sha256:'a'.repeat(64)});assert.throws(()=>s.submitClaim(actors.owner,one.claim_id),e=>e.code==='EVIDENCE_INSUFFICIENT');assert.throws(()=>s.addEvidence(actors.other,claim.claim_id,{kind:'phone_callback',artifact_sha256:'b'.repeat(64)}),e=>e.code==='ACCESS_DENIED');});
test('claimant cannot review their own evidence',()=>{const s=service(),claim=claimWithEvidence(s);assert.throws(()=>s.reviewEvidence(actors.owner,claim.claim_id,claim.evidence[0].evidence_id,'accepted','Autoaprobación'),e=>e.code==='ACCESS_DENIED'||e.code==='EVIDENCE_REVIEW_INVALID');});
test('independent reviewer verifies two accepted evidence kinds',()=>{const s=service(),claim=verifyClaim(s);assert.equal(claim.status,'verified');assert.equal(claim.reviewer_id,'operator-alpha');assert.equal(claim.evidence.filter(x=>x.verification_status==='accepted').length,2);});
test('claim cannot be verified with only one accepted factor',()=>{const s=service(),claim=claimWithEvidence(s),reviewed=s.reviewEvidence(actors.operator,claim.claim_id,claim.evidence[0].evidence_id,'accepted','Primera prueba aceptada.');assert.throws(()=>s.decideClaim(actors.operator,reviewed.claim_id,'verified','Intento incompleto.'),e=>e.code==='EVIDENCE_INSUFFICIENT');});
test('unconfigured billing adapter fails closed',()=>{const s=service({billingAdapter:createUnconfiguredBillingAdapter()});assert.throws(()=>s.ingestBilling(actors.system,billing()),e=>e.code==='BILLING_UNCONFIGURED');});
test('local sandbox billing is idempotent',()=>{const s=service({billingAdapter:createLocalBillingAdapter()}),raw=billing(),first=s.ingestBilling(actors.system,raw),second=s.ingestBilling(actors.system,raw);assert.equal(first.subscription.status,'active');assert.equal(first.duplicate,false);assert.equal(second.duplicate,true);assert.equal(second.subscription.version,1);});
test('draft plan cannot be activated by a production billing adapter',()=>{const local=createLocalBillingAdapter(),adapter={name:'billing_adapter',normalize(raw){const normalized=local.normalize(raw);normalized.event.provider='billing_adapter';return normalized;}},s=service({billingAdapter:adapter});assert.throws(()=>s.ingestBilling(actors.system,billing()),e=>e.code==='PLAN_INACTIVE');});
test('baseline safety capabilities remain available without claim or subscription',()=>{const s=service(),snapshot=s.derive(actors.owner,'tenant-alpha');assert.equal(s.can(snapshot,'portal.access'),true);assert.equal(s.can(snapshot,'privacy.request'),true);assert.equal(s.can(snapshot,'data.export.request'),true);assert.equal(s.can(snapshot,'site.publish'),false);assert.equal(snapshot.capabilities.find(x=>x.key==='site.publish').reason,'claim_required');});
test('verified claim plus active sandbox plan enables only configured capabilities',()=>{const s=service({billingAdapter:createLocalBillingAdapter()});verifyClaim(s);s.ingestBilling(actors.system,billing());const snapshot=s.derive(actors.owner,'tenant-alpha');assert.equal(s.can(snapshot,'site.preview'),true);assert.equal(s.can(snapshot,'lead.capture'),true);assert.equal(snapshot.capabilities.find(x=>x.key==='lead.capture').limit,50);assert.equal(s.can(snapshot,'site.publish'),false);assert.equal(snapshot.capabilities.find(x=>x.key==='site.publish').reason,'plan_disabled');});
test('past-due state removes plan capabilities but preserves safety access',()=>{const s=service({billingAdapter:createLocalBillingAdapter()});verifyClaim(s);s.ingestBilling(actors.system,billing());s.ingestBilling(actors.system,billing('past_due','2026-09-30T17:02:00Z'));const snapshot=s.derive(actors.owner,'tenant-alpha');assert.equal(s.can(snapshot,'lead.capture'),false);assert.equal(s.can(snapshot,'privacy.request'),true);assert.equal(snapshot.capabilities.find(x=>x.key==='lead.capture').reason,'subscription_inactive');});
test('claim revocation immediately removes commercial capabilities',()=>{const s=service({billingAdapter:createLocalBillingAdapter()}),claim=verifyClaim(s);s.ingestBilling(actors.system,billing());assert.equal(s.can(s.derive(actors.owner,'tenant-alpha'),'lead.capture'),true);s.revokeClaim(actors.admin,claim.claim_id,'Propiedad transferida en prueba sintética.');assert.equal(s.can(s.derive(actors.owner,'tenant-alpha'),'lead.capture'),false);});
test('manual grant is time limited and sensitive grants require verified claim',()=>{let time=new Date('2026-09-30T17:00:00Z');const s=createClaimEntitlementService({plans,now:()=>time});assert.throws(()=>s.createGrant(actors.admin,{tenant_id:'tenant-alpha',capability:'site.publish',expires_at:'2026-10-05T17:00:00Z',reason:'Piloto controlado.'}),e=>e.code==='CLAIM_REQUIRED');const grant=s.createGrant(actors.admin,{tenant_id:'tenant-alpha',capability:'analytics.basic',limit:null,expires_at:'2026-10-05T17:00:00Z',reason:'Piloto controlado.'});assert.equal(s.can(s.derive(actors.owner,'tenant-alpha'),'analytics.basic'),true);time=new Date('2026-10-06T17:00:00Z');assert.equal(s.can(s.derive(actors.owner,'tenant-alpha'),'analytics.basic'),false);assert.equal(grant.status,'active');});
test('unknown capability is denied by default',()=>{const s=service(),snapshot=s.derive(actors.owner,'tenant-alpha');assert.equal(s.can(snapshot,'secret.superpower'),false);});
test('stale and invalid billing transitions are rejected',()=>{const s=service({billingAdapter:createLocalBillingAdapter()});s.ingestBilling(actors.system,billing());assert.throws(()=>s.ingestBilling(actors.system,billing('active','2026-09-30T16:00:00Z',{idempotency_key:'stale-event'})),e=>e.code==='BILLING_EVENT_STALE');s.ingestBilling(actors.system,billing('cancelled','2026-09-30T17:03:00Z'));assert.throws(()=>s.ingestBilling(actors.system,billing('active','2026-09-30T17:04:00Z',{idempotency_key:'after-cancel'})),e=>e.code==='SUBSCRIPTION_TRANSITION_INVALID');});
test('claim and entitlement console is read-only, noindex and isolated',async()=>{const app=server();await new Promise((resolve,reject)=>{app.once('error',reject);app.listen(0,'127.0.0.1',resolve);});try{const origin=`http://127.0.0.1:${app.address().port}`,page=await fetch(origin);assert.equal(page.status,200);assert.match(page.headers.get('x-robots-tag'),/noindex/);assert.match(page.headers.get('content-security-policy'),/connect-src 'none'/);assert.equal((await fetch(origin,{method:'POST'})).status,405);assert.equal((await fetch(origin+'/../package.json')).status,404);}finally{await new Promise(resolve=>app.close(resolve));}});
