'use strict';const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');const {createCloudflareStagingActivation,createFakeCloudflareTransport,createCloudflareHttpTransport,sha}=require('../packages/cloudflare-staging-activation/index.cjs');const {server}=require('../scripts/serve-staging-activation.cjs');
const actors={admin:{actor_id:'admin-one',roles:['platform_admin']},admin2:{actor_id:'admin-two',roles:['platform_admin']},securityAdmin:{actor_id:'security-admin',roles:['security_admin']},operator:{actor_id:'operator-one',roles:['platform_operator']},platform:{actor_id:'platform-reviewer',roles:['platform_approver']},security:{actor_id:'security-reviewer',roles:['security_approver']},finance:{actor_id:'finance-reviewer',roles:['finance_approver']},executor:{actor_id:'executor-one',roles:['platform_executor']},viewer:{actor_id:'viewer-one',roles:['viewer']}};
function clock(){let value=new Date('2026-11-17T15:00:00Z');return {now:()=>new Date(value),advance:s=>{value=new Date(value.getTime()+s*1000);}};}function fixture(options={}){const time=clock(),transport=createFakeCloudflareTransport(options),service=createCloudflareStagingActivation({transport,now:time.now});return {time,transport,service};}const token=()=> 'x'.repeat(48);
async function readSession(options={}){const state=fixture(options),session=await state.service.openSession(actors.admin,{token:token(),account_id:'account-synthetic',zone_id:'zone-synthetic',mode:'read',ttl_seconds:1800});return {...state,session};}
async function discovered(options={}){const state=await readSession(options),permissions=await state.service.probePermissions(actors.operator,state.session.session_id),discovery=await state.service.discover(actors.operator,state.session.session_id);return {...state,permissions,discovery};}
async function planned(options={}){const state=await discovered(options),desired=[['workers','hc-staging-control-worker',{compatibility_date:'2026-09-30'}],['d1','hc-staging-control',{region:'auto'}],['custom_hostname','staging.guialima.online',{tls:'managed'}]].map(([kind,logical_name,config])=>({kind,logical_name,desired_digest:sha(config)})),plan=state.service.createActivationPlan(actors.operator,{environment_ref:'staging-lima',discovery_ref:state.discovery.discovery_id,desired_manifest_digest:sha(desired),desired,estimated_monthly_cost_cents:2100});return {...state,desired,plan};}
async function approved(options={}){const state=await planned(options);state.service.approvePlan(actors.platform,state.plan.plan_id);state.service.approvePlan(actors.security,state.plan.plan_id);state.service.approvePlan(actors.finance,state.plan.plan_id);return {...state,plan:state.service.getPlan(state.plan.plan_id)};}

test('opens read session without persisting token',async()=>{const {service,session}=await readSession();assert.equal(session.status,'active');assert.equal(session.secret_persisted,false);assert.equal('token' in session,false);assert(service._secrets.has(session.session_id));});
test('session stores fingerprints instead of provider identifiers',async()=>{const {session}=await readSession();assert.match(session.token_fingerprint,/^[a-f0-9]{64}$/);assert.match(session.account_fingerprint,/^[a-f0-9]{64}$/);assert.equal(session.account_fingerprint.includes('account'),false);});
test('opening session requires privileged role',async()=>{const {service}=fixture();await assert.rejects(()=>service.openSession(actors.viewer,{token:token(),account_id:'account',zone_id:'zone',mode:'read'}),{code:'ROLE_REQUIRED'});});
test('short token is rejected before transport',async()=>{const {service,transport}=fixture();await assert.rejects(()=>service.openSession(actors.admin,{token:'short',account_id:'account',zone_id:'zone',mode:'read'}),{code:'TOKEN_INVALID'});assert.equal(transport.requests.length,0);});
test('invalid token creates invalid non-secret session',async()=>{const {service}=fixture({invalidToken:true}),session=await service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'read'});assert.equal(session.status,'invalid');assert.equal(service._secrets.has(session.session_id),false);});
test('read session ttl cannot exceed one hour',async()=>{const {service}=fixture();await assert.rejects(()=>service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'read',ttl_seconds:3601}),{code:'SESSION_TTL_INVALID'});});
test('apply session ttl cannot exceed fifteen minutes',async()=>{const {service}=fixture();await assert.rejects(()=>service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'apply',ttl_seconds:901}),{code:'SESSION_TTL_INVALID'});});
test('expired session is rejected',async()=>{const state=await readSession();state.time.advance(1801);await assert.rejects(()=>state.service.probePermissions(actors.operator,state.session.session_id),{code:'SESSION_EXPIRED'});});
test('security admin can revoke session and erase in-memory token',async()=>{const {service,session}=await readSession();service.revokeSession(actors.securityAdmin,session.session_id);assert.equal(service.getSession(session.session_id).status,'revoked');assert.equal(service._secrets.has(session.session_id),false);});
test('permission probe uses only GET requests',async()=>{const state=await readSession();await state.service.probePermissions(actors.operator,state.session.session_id);assert(state.transport.requests.slice(1).every(item=>item.method==='GET'));});
test('permission probe checks six resource families',async()=>{const {permissions}=await discovered();assert.equal(permissions.checks.length,6);assert.equal(permissions.status,'passed');});
test('denied permission blocks probe',async()=>{const state=await readSession({deniedKinds:['r2']}),probe=await state.service.probePermissions(actors.operator,state.session.session_id);assert.equal(probe.status,'blocked');assert.equal(probe.checks.find(item=>item.capability==='r2.read').result,'denied');});
test('permission evidence redacts account and zone identifiers',async()=>{const {permissions}=await discovered();assert(permissions.checks.every(item=>!item.endpoint.includes('account-synthetic')));assert(permissions.checks.some(item=>item.endpoint.includes('{account}')));});
test('discovery requires passing permission probe',async()=>{const state=await readSession();await assert.rejects(()=>state.service.discover(actors.operator,state.session.session_id),{code:'PERMISSION_PROBE_REQUIRED'});});
test('blocked permission probe prevents discovery',async()=>{const state=await readSession({deniedKinds:['dns']});await state.service.probePermissions(actors.operator,state.session.session_id);await assert.rejects(()=>state.service.discover(actors.operator,state.session.session_id),{code:'PERMISSION_PROBE_REQUIRED'});});
test('discovery is explicitly read only',async()=>{const {discovery,transport}=await discovered();assert.equal(discovery.external_changes,false);assert(transport.requests.every(item=>item.method==='GET'));});
test('discovery imports six normalized resources',async()=>{const {discovery}=await discovered();assert.equal(discovery.resource_count,6);assert.equal(discovery.status,'completed');});
test('provider ids are represented by fingerprints',async()=>{const {discovery}=await discovered();assert(discovery.resources.every(item=>/^[a-f0-9]{64}$/.test(item.provider_id_fingerprint)));assert(discovery.resources.every(item=>!item.provider_id_fingerprint.includes('worker-1')));});
test('configuration is represented by digest',async()=>{const {discovery}=await discovered();assert(discovery.resources.every(item=>/^[a-f0-9]{64}$/.test(item.configuration_digest)));});
test('discovery records pages and minimum rate remaining',async()=>{const {discovery}=await discovered({remaining:1100});assert.equal(discovery.pages_read,6);assert.equal(discovery.rate_limit_remaining,1100);});
test('rate limit stays continue with healthy quota',async()=>{const {service}=await discovered({remaining:1100});assert(service.listRateLimits().every(item=>item.action==='continue'));});
test('rate limit throttles below ten percent',async()=>{const {service}=await discovered({remaining:50});assert(service.listRateLimits().some(item=>item.action==='throttle'));});
test('rate limit stops at zero',async()=>{const {service}=await discovered({remaining:0});assert(service.listRateLimits().some(item=>item.action==='stop'));});
test('public evidence contains no external changes',async()=>{const {service}=await discovered(),evidence=service.createPublicEvidence(actors.operator,[{hostname:'guialima.online',dns_resolved:true,https_reachable:false,status_code:0,tls:false,security_headers:false,indexing_policy:'unknown'}]);assert.equal(evidence.network_read_only,true);assert.equal(evidence.external_changes,false);});
test('reachable secure public probe passes with headers',async()=>{const {service}=await discovered(),evidence=service.createPublicEvidence(actors.operator,[{hostname:'hazlo-crecer.pages.dev',dns_resolved:true,https_reachable:true,status_code:200,tls:true,security_headers:true,indexing_policy:'index'}]);assert.equal(evidence.probes[0].status,'passed');});
test('reachable probe without security headers warns',async()=>{const {service}=await discovered(),evidence=service.createPublicEvidence(actors.operator,[{hostname:'example.com',dns_resolved:true,https_reachable:true,status_code:200,tls:true,security_headers:false,indexing_policy:'index'}]);assert.equal(evidence.probes[0].status,'warning');});
test('unreachable public probe fails',async()=>{const {service}=await discovered(),evidence=service.createPublicEvidence(actors.operator,[{hostname:'example.com',dns_resolved:false,https_reachable:false,status_code:0,tls:false,security_headers:false,indexing_policy:'unknown'}]);assert.equal(evidence.probes[0].status,'failed');});
test('activation plan requires completed discovery',async()=>{const state=await readSession();assert.throws(()=>state.service.createActivationPlan(actors.operator,{environment_ref:'staging',discovery_ref:'missing-discovery',desired_manifest_digest:sha('x'),desired:[{kind:'d1',logical_name:'db',desired_digest:sha('db')}],estimated_monthly_cost_cents:1}),{code:'DISCOVERY_INCOMPLETE'});});
test('activation plan requires desired resources',async()=>{const state=await discovered();assert.throws(()=>state.service.createActivationPlan(actors.operator,{environment_ref:'staging',discovery_ref:state.discovery.discovery_id,desired_manifest_digest:sha('x'),desired:[],estimated_monthly_cost_cents:1}),{code:'DESIRED_RESOURCES_REQUIRED'});});
test('matching discovered resource becomes verify action',async()=>{const {plan}=await planned();assert.equal(plan.actions.find(item=>item.logical_name==='hc-staging-control-worker').action,'verify');});
test('missing desired resource becomes create action',async()=>{const {plan}=await planned();assert.equal(plan.actions.find(item=>item.kind==='custom_hostname').action,'create');});
test('changed desired digest becomes update action',async()=>{const state=await discovered(),desired=[{kind:'d1',logical_name:'hc-staging-control',desired_digest:sha('changed')}],plan=state.service.createActivationPlan(actors.operator,{environment_ref:'staging',discovery_ref:state.discovery.discovery_id,desired_manifest_digest:sha(desired),desired,estimated_monthly_cost_cents:1});assert.equal(plan.actions[0].action,'update');});
test('plan digest binds discovery desired state and cost',async()=>{const {plan}=await planned();assert.match(plan.plan_digest,/^[a-f0-9]{64}$/);assert.equal(plan.status,'draft');});
test('plan creator cannot approve own plan',async()=>{const state=await planned(),same={actor_id:actors.operator.actor_id,roles:['platform_approver']};assert.throws(()=>state.service.approvePlan(same,state.plan.plan_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('same approval role cannot approve twice',async()=>{const state=await planned();state.service.approvePlan(actors.platform,state.plan.plan_id);assert.throws(()=>state.service.approvePlan({actor_id:'platform-two',roles:['platform_approver']},state.plan.plan_id),{code:'DUPLICATE_APPROVAL_ROLE'});});
test('one approval leaves plan draft',async()=>{const state=await planned(),result=state.service.approvePlan(actors.platform,state.plan.plan_id);assert.equal(result.plan.status,'draft');});
test('three independent roles approve exact digest',async()=>{const state=await approved();assert.equal(state.plan.status,'approved');assert.equal(state.service.summary().approvals,3);});
test('rejection blocks activation plan',async()=>{const state=await planned(),result=state.service.approvePlan(actors.security,state.plan.plan_id,{decision:'reject',comment:'Permissions are too broad'});assert.equal(result.plan.status,'blocked');});
test('apply authorization requires three approvals',async()=>{const state=await planned();state.service.approvePlan(actors.platform,state.plan.plan_id);assert.throws(()=>state.service.authorizeApply(actors.admin,state.plan.plan_id),{code:'PLAN_NOT_APPROVED'});});
test('plan creator cannot authorize their plan',async()=>{const state=await approved(),same={actor_id:actors.operator.actor_id,roles:['platform_admin']};assert.throws(()=>state.service.authorizeApply(same,state.plan.plan_id),{code:'INDEPENDENT_AUTHORIZATION_REQUIRED'});});
test('authorization stores nonce hash only',async()=>{const state=await approved(),result=state.service.authorizeApply(actors.admin,state.plan.plan_id);assert.match(result.nonce,/^[A-Za-z0-9_-]+$/);assert.notEqual(result.authorization.nonce_hash,result.nonce);assert.equal('nonce' in result.authorization,false);});
test('authorization ttl is capped at fifteen minutes',async()=>{const state=await approved();assert.throws(()=>state.service.authorizeApply(actors.admin,state.plan.plan_id,{ttl_seconds:901}),{code:'AUTHORIZATION_TTL_INVALID'});});
test('synthetic transport cannot apply external plan',async()=>{const state=await approved(),auth=state.service.authorizeApply(actors.admin,state.plan.plan_id),applySession=await state.service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'apply',ttl_seconds:600});await assert.rejects(()=>state.service.applyPlan(actors.executor,applySession.session_id,auth.authorization.authorization_id,auth.nonce),{code:'EXTERNAL_TRANSPORT_REQUIRED'});});
test('read session cannot execute apply',async()=>{const state=await approved(),auth=state.service.authorizeApply(actors.admin,state.plan.plan_id);await assert.rejects(()=>state.service.applyPlan(actors.executor,state.session.session_id,auth.authorization.authorization_id,auth.nonce),{code:'SESSION_MODE_MISMATCH'});});
test('wrong authorization nonce is rejected',async()=>{const state=await approved({externalChanges:true}),auth=state.service.authorizeApply(actors.admin,state.plan.plan_id),applySession=await state.service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'apply',ttl_seconds:600});await assert.rejects(()=>state.service.applyPlan(actors.executor,applySession.session_id,auth.authorization.authorization_id,'wrong-nonce'),{code:'AUTHORIZATION_NONCE_INVALID'});});
test('external fake applies only create and update actions',async()=>{const state=await approved({externalChanges:true}),auth=state.service.authorizeApply(actors.admin,state.plan.plan_id),applySession=await state.service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'apply',ttl_seconds:600}),result=await state.service.applyPlan(actors.executor,applySession.session_id,auth.authorization.authorization_id,auth.nonce);assert.equal(result.receipts.length,1);assert.equal(result.plan.status,'applied');assert(result.receipts.every(item=>item.external_change));});
test('apply authorization is single use',async()=>{const state=await approved({externalChanges:true}),auth=state.service.authorizeApply(actors.admin,state.plan.plan_id),applySession=await state.service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'apply',ttl_seconds:600});await state.service.applyPlan(actors.executor,applySession.session_id,auth.authorization.authorization_id,auth.nonce);await assert.rejects(()=>state.service.applyPlan(actors.executor,applySession.session_id,auth.authorization.authorization_id,auth.nonce),{code:'AUTHORIZATION_EXPIRED'});});
test('apply receipts redact account and resource names from endpoint template',async()=>{const state=await approved({externalChanges:true}),auth=state.service.authorizeApply(actors.admin,state.plan.plan_id),applySession=await state.service.openSession(actors.admin,{token:token(),account_id:'account-private',zone_id:'zone',mode:'apply',ttl_seconds:600});await state.service.applyPlan(actors.executor,applySession.session_id,auth.authorization.authorization_id,auth.nonce);assert.equal(state.service.listReceipts()[0].endpoint_template,'/accounts/{account}/staging/{kind}/{name}');});
test('failed apply blocks plan',async()=>{const state=await approved({externalChanges:true,failApply:true}),auth=state.service.authorizeApply(actors.admin,state.plan.plan_id),applySession=await state.service.openSession(actors.admin,{token:token(),account_id:'account',zone_id:'zone',mode:'apply',ttl_seconds:600});await assert.rejects(()=>state.service.applyPlan(actors.executor,applySession.session_id,auth.authorization.authorization_id,auth.nonce),{code:'APPLY_REQUEST_FAILED'});assert.equal(state.service.getPlan(state.plan.plan_id).status,'blocked');});
test('CI policy references secrets by name only',async()=>{const {service}=await discovered(),policy=service.createCiPolicy(actors.securityAdmin,{secret_refs:['CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID'],allowed_branch:'staging',permissions:['contents:read']});assert.equal(policy.plaintext_forbidden,true);assert.deepEqual(policy.secret_refs,['CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID']);});
test('CI policy requires security admin',async()=>{const {service}=await discovered();assert.throws(()=>service.createCiPolicy(actors.viewer,{secret_refs:['ONE','TWO'],allowed_branch:'staging',permissions:['read']}),{code:'ROLE_REQUIRED'});});
test('workflow separates discover plan apply and verify',async()=>{const {service}=await discovered(),policy=service.createCiPolicy(actors.securityAdmin,{secret_refs:['CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID'],allowed_branch:'staging',permissions:['contents:read']}),workflow=service.createWorkflow(actors.admin,policy.policy_id);assert.deepEqual(workflow.jobs.map(item=>item.mode),['read','plan','apply','verify']);assert.equal(workflow.apply_requires_approval,true);});
test('workflow digest binds policy and dependency chain',async()=>{const {service}=await discovered(),policy=service.createCiPolicy(actors.securityAdmin,{secret_refs:['CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID'],allowed_branch:'staging',permissions:['contents:read']}),workflow=service.createWorkflow(actors.admin,policy.policy_id);assert.match(workflow.workflow_digest,/^[a-f0-9]{64}$/);});
test('readiness is blocked without real artifacts',async()=>{const {service}=await discovered(),policy=service.createCiPolicy(actors.securityAdmin,{secret_refs:['CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID'],allowed_branch:'staging',permissions:['contents:read']}),workflow=service.createWorkflow(actors.admin,policy.policy_id),evidence=service.createPublicEvidence(actors.operator,[{hostname:'guialima.online',dns_resolved:true,https_reachable:false,status_code:0,tls:false,security_headers:false,indexing_policy:'unknown'}]),result=service.readiness(actors.admin,{permission_probe_ref:null,discovery_ref:null,plan_ref:null,ci_workflow_ref:workflow.workflow_id,public_evidence_ref:evidence.evidence_id});assert.equal(result.status,'blocked');assert(result.blockers.length>=3);});
test('approved synthetic plan is ready for final approval boundary',async()=>{const state=await approved(),policy=state.service.createCiPolicy(actors.securityAdmin,{secret_refs:['CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID'],allowed_branch:'staging',permissions:['contents:read']}),workflow=state.service.createWorkflow(actors.admin,policy.policy_id),evidence=state.service.createPublicEvidence(actors.operator,[{hostname:'guialima.online',dns_resolved:true,https_reachable:false,status_code:0,tls:false,security_headers:false,indexing_policy:'unknown'}]),result=state.service.readiness(actors.admin,{permission_probe_ref:state.permissions.probe_id,discovery_ref:state.discovery.discovery_id,plan_ref:state.plan.plan_id,ci_workflow_ref:workflow.workflow_id,public_evidence_ref:evidence.evidence_id});assert.equal(result.status,'ready_for_approval');});
test('HTTP transport sends bearer token only in request header',async()=>{let captured;const fetchImpl=async(url,options)=>{captured={url,options};return {status:200,headers:{get:()=>null},json:async()=>({success:true,result:{status:'active'}})};},transport=createCloudflareHttpTransport({fetchImpl});await transport.request({method:'GET',path:'/user/tokens/verify',token:token()});assert.equal(captured.options.headers.Authorization,`Bearer ${token()}`);assert.equal(captured.url.includes(token()),false);});
test('summary reports lifecycle counts without secrets',async()=>{const state=await approved(),summary=state.service.summary();assert.equal(summary.sessions,1);assert.equal(summary.discovered_resources,6);assert.equal(summary.approvals,3);assert.equal('token' in summary,false);});

function request(instance,url,method='GET'){return new Promise((resolve,reject)=>{const address=instance.address(),req=http.request({hostname:'127.0.0.1',port:address.port,path:url,method},res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body}));});req.on('error',reject);req.end();});}async function startedServer(){const instance=server();await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve);});return instance;}
test('activation console serves protected noindex HTML',async()=>{const instance=await startedServer();try{const response=await request(instance,'/');assert.equal(response.status,200);assert.match(response.body,/Staging Activation Room/);assert.match(response.headers['content-security-policy'],/connect-src 'none'/);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('activation console supports HEAD',async()=>{const instance=await startedServer();try{const response=await request(instance,'/','HEAD');assert.equal(response.status,200);assert.equal(response.body,'');}finally{await new Promise(resolve=>instance.close(resolve));}});
test('activation console rejects writes and traversal',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/','POST')).status,405);assert.equal((await request(instance,'/%2e%2e/package.json')).status,404);}finally{await new Promise(resolve=>instance.close(resolve));}});
