'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');const {createControlPlanePersistence,sha}=require('../packages/control-plane-persistence/index.cjs');const {server}=require('../scripts/serve-control-plane-recovery.cjs');
const actors={operator:{actor_id:'operator-persistence',role:'operator',tenant_id:'tenant-horizonte'},reviewer:{actor_id:'operator-recovery-review',role:'operator',tenant_id:'tenant-horizonte'},executor:{actor_id:'operator-recovery-exec',role:'operator',tenant_id:'tenant-horizonte'},worker:{actor_id:'worker-outbox',role:'service',tenant_id:'tenant-horizonte'},worker2:{actor_id:'worker-outbox-2',role:'service',tenant_id:'tenant-horizonte'},owner:{actor_id:'owner-horizonte',role:'owner',tenant_id:'tenant-horizonte'},other:{actor_id:'operator-other',role:'operator',tenant_id:'tenant-other'}};
function clock(){let value=new Date('2026-10-27T15:00:00Z');return {now:()=>new Date(value),advance:seconds=>{value=new Date(value.getTime()+seconds*1000);}};}
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hc-phase24-')),time=clock(),databasePath=path.join(dir,'control.db'),service=createControlPlanePersistence({databasePath,now:time.now});return {dir,time,databasePath,service};}
const write=(id='site-001',expected=0,payload={generation:1,recipe:'1.0.0'},overrides={})=>({entity_type:'desired_state',entity_id:id,expected_version:expected,payload,event_type:'control.desired_state.updated',...overrides});
function committed(){const state=fixture(),result=state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write()]});return {...state,result};}

test('new database starts empty',()=>{const state=fixture();assert.deepEqual(state.service.counts(),{entities:0,transactions:0,outbox:0,pending:0,claimed:0,delivered:0,dead_lettered:0});state.service.close();});
test('commit persists entity and outbox atomically',()=>{const state=committed(),counts=state.service.counts();assert.equal(counts.entities,1);assert.equal(counts.transactions,1);assert.equal(counts.outbox,1);assert.equal(state.result.transaction.write_count,1);state.service.close();});
test('stored entity returns payload and digest',()=>{const state=committed(),entity=state.service.readEntity(actors.owner,'tenant-horizonte','desired_state','site-001');assert.deepEqual(entity.payload,{generation:1,recipe:'1.0.0'});assert.equal(entity.payload_digest,sha(JSON.stringify(entity.payload)));state.service.close();});
test('optimistic update increments version',()=>{const state=committed(),result=state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('site-001',1,{generation:2,recipe:'1.1.0'})]});assert.equal(result.results[0].previous_version,1);assert.equal(result.results[0].new_version,2);state.service.close();});
test('stale optimistic write is rejected without side effects',()=>{const state=committed(),before=state.service.counts();assert.throws(()=>state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('site-001',0,{generation:2})]}),{code:'OPTIMISTIC_CONFLICT'});assert.deepEqual(state.service.counts(),before);state.service.close();});
test('multi-write transaction is all or nothing',()=>{const state=committed(),before=state.service.counts();assert.throws(()=>state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('site-002'),write('site-001',0)]}),{code:'OPTIMISTIC_CONFLICT'});assert.equal(state.service.readEntity(actors.owner,'tenant-horizonte','desired_state','site-002'),null);assert.deepEqual(state.service.counts(),before);state.service.close();});
test('synthetic pre-commit failure rolls back entity and event',()=>{const state=fixture();assert.throws(()=>state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write()]},{simulateFailure:true}),{code:'SIMULATED_FAILURE'});assert.equal(state.service.counts().entities,0);assert.equal(state.service.counts().outbox,0);state.service.close();});
test('one outbox event is created per write',()=>{const state=fixture(),result=state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('site-001'),write('site-002')]});assert.equal(result.events.length,2);assert(result.events.every(event=>event.transaction_ref===result.transaction.transaction_id));state.service.close();});
test('unknown entity type is rejected',()=>{const state=fixture();assert.throws(()=>state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('x',0,{}, {entity_type:'unknown'})]}),{code:'ENTITY_TYPE_INVALID'});state.service.close();});
test('unsafe event type is rejected',()=>{const state=fixture();assert.throws(()=>state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('site-unsafe',0,{}, {event_type:'BAD EVENT'})]}),{code:'EVENT_TYPE_INVALID'});state.service.close();});
test('tenant isolation protects reads and writes',()=>{const state=committed();assert.throws(()=>state.service.readEntity(actors.other,'tenant-horizonte','desired_state','site-001'),{code:'ACCESS_DENIED'});assert.throws(()=>state.service.commit(actors.other,{tenant_id:'tenant-horizonte',writes:[write('site-002')]}),{code:'ACCESS_DENIED'});state.service.close();});
test('owner reads but cannot commit',()=>{const state=committed();assert.equal(state.service.listEntities(actors.owner,'tenant-horizonte').length,1);assert.throws(()=>state.service.commit(actors.owner,{tenant_id:'tenant-horizonte',writes:[write('site-002')]}),{code:'ACCESS_DENIED'});state.service.close();});
test('worker claims pending outbox events',()=>{const state=committed(),claim=state.service.claimOutbox(actors.worker,'tenant-horizonte',{limit:10,leaseSeconds:60});assert.equal(claim.events.length,1);assert.equal(claim.events[0].status,'claimed');assert.equal(claim.worker_id,actors.worker.actor_id);state.service.close();});
test('claim limit is enforced',()=>{const state=committed();assert.throws(()=>state.service.claimOutbox(actors.worker,'tenant-horizonte',{limit:1001}),{code:'CLAIM_LIMIT_INVALID'});state.service.close();});
test('empty outbox claim returns null',()=>{const state=fixture();assert.equal(state.service.claimOutbox(actors.worker,'tenant-horizonte'),null);state.service.close();});
test('another worker cannot settle claimed event',()=>{const state=committed(),claim=state.service.claimOutbox(actors.worker,'tenant-horizonte');assert.throws(()=>state.service.settleOutbox(actors.worker2,claim.event_refs[0],{delivered:true}),{code:'OUTBOX_LEASE_INVALID'});state.service.close();});
test('delivery preserves event and marks it delivered',()=>{const state=committed(),claim=state.service.claimOutbox(actors.worker,'tenant-horizonte'),event=state.service.settleOutbox(actors.worker,claim.event_refs[0],{delivered:true});assert.equal(event.status,'delivered');assert.equal(state.service.counts().delivered,1);state.service.close();});
test('transient delivery failure returns event to pending',()=>{const state=committed(),claim=state.service.claimOutbox(actors.worker,'tenant-horizonte'),event=state.service.settleOutbox(actors.worker,claim.event_refs[0],{delivered:false,maxAttempts:3});assert.equal(event.status,'pending');assert.equal(event.attempts,1);state.service.close();});
test('repeated delivery failures dead-letter event',()=>{const state=committed();for(let attempt=0;attempt<2;attempt++){const claim=state.service.claimOutbox(actors.worker,'tenant-horizonte'),event=state.service.settleOutbox(actors.worker,claim.event_refs[0],{delivered:false,maxAttempts:2});if(attempt===1)assert.equal(event.status,'dead_lettered');}assert.equal(state.service.counts().dead_lettered,1);state.service.close();});
test('expired claim can be reclaimed by another worker',()=>{const state=committed();state.service.claimOutbox(actors.worker,'tenant-horizonte',{leaseSeconds:10});state.time.advance(11);const claim=state.service.claimOutbox(actors.worker2,'tenant-horizonte',{leaseSeconds:10});assert.equal(claim.worker_id,actors.worker2.actor_id);assert.equal(claim.events[0].attempts,2);state.service.close();});
test('integrity scan passes for valid database',()=>{const state=committed(),scan=state.service.integrityScan(actors.operator);assert.equal(scan.status,'passed');assert.equal(scan.entity_digest_failures,0);state.service.close();});
test('integrity scan detects entity payload tampering',()=>{const state=committed();state.service._db.prepare("UPDATE control_entities SET payload_json='{}'").run();const scan=state.service.integrityScan(actors.operator);assert.equal(scan.status,'failed');assert.equal(scan.entity_digest_failures,1);state.service.close();});
test('integrity scan detects outbox payload tampering',()=>{const state=committed();state.service._db.prepare("UPDATE outbox_events SET payload_json='{}'").run();const scan=state.service.integrityScan(actors.operator);assert.equal(scan.status,'failed');assert.equal(scan.outbox_digest_failures,1);state.service.close();});
test('snapshot writes deterministic tenant state',()=>{const state=committed(),target=path.join(state.dir,'snapshots','tenant.json'),snapshot=state.service.createSnapshot(actors.operator,'tenant-horizonte',target);assert.equal(snapshot.entity_count,1);assert.equal(snapshot.outbox_count,1);assert.equal(snapshot.transaction_count,1);assert.equal(snapshot.content_digest,sha(fs.readFileSync(target)));state.service.close();});
test('snapshot excludes another tenant',()=>{const state=committed();state.service.commit({actor_id:'admin-root',role:'admin',tenant_id:'root'},{tenant_id:'tenant-other',writes:[write('other-site')]});const snapshot=state.service.createSnapshot(actors.operator,'tenant-horizonte',path.join(state.dir,'tenant.json'));assert.equal(snapshot.entity_count,1);state.service.close();});
test('backup is a verified SQLite artifact',async()=>{const state=committed(),artifact=await state.service.createBackup(actors.operator,path.join(state.dir,'backups','control.db'));assert.equal(artifact.status,'verified');assert.equal(artifact.entity_count,1);assert.match(artifact.database_digest,/^[a-f0-9]{64}$/);state.service.close();});
test('backup verification compares digest integrity and counts',async()=>{const state=committed(),artifact=await state.service.createBackup(actors.operator,path.join(state.dir,'backups','control.db')),verification=state.service.verifyBackup(actors.operator,artifact.backup_id);assert.equal(verification.status,'passed');assert(verification.digest_match);state.service.close();});
test('modified backup fails verification',async()=>{const state=committed(),target=path.join(state.dir,'backups','control.db'),artifact=await state.service.createBackup(actors.operator,target);fs.appendFileSync(target,Buffer.from('tamper'));const verification=state.service.verifyBackup(actors.operator,artifact.backup_id);assert.equal(verification.status,'failed');assert.equal(verification.digest_match,false);state.service.close();});
test('backup target cannot be overwritten',async()=>{const state=committed(),target=path.join(state.dir,'backups','control.db');await state.service.createBackup(actors.operator,target);await assert.rejects(()=>state.service.createBackup(actors.operator,target),{code:'BACKUP_TARGET_EXISTS'});state.service.close();});
test('recovery objective records RPO RTO and transaction loss',()=>{const state=fixture(),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Control plane local',rpo_seconds:300,rto_seconds:60,maximum_lost_transactions:0});assert.equal(objective.rpo_seconds,300);assert.equal(objective.maximum_lost_transactions,0);state.service.close();});
test('restore plan begins as draft',async()=>{const state=committed(),backup=await state.service.createBackup(actors.operator,path.join(state.dir,'backup.db')),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Local',rpo_seconds:300,rto_seconds:60,maximum_lost_transactions:0}),plan=state.service.createRestorePlan(actors.operator,{backup_ref:backup.backup_id,objective_ref:objective.objective_id,target_path:path.join(state.dir,'restore.db')});assert.equal(plan.status,'draft');state.service.close();});
test('restore plan creator cannot approve it',async()=>{const state=committed(),backup=await state.service.createBackup(actors.operator,path.join(state.dir,'backup.db')),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Local',rpo_seconds:300,rto_seconds:60,maximum_lost_transactions:0}),plan=state.service.createRestorePlan(actors.operator,{backup_ref:backup.backup_id,objective_ref:objective.objective_id,target_path:path.join(state.dir,'restore.db')});assert.throws(()=>state.service.approveRestorePlan(actors.operator,plan.plan_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});state.service.close();});
test('unapproved restore cannot execute',async()=>{const state=committed(),backup=await state.service.createBackup(actors.operator,path.join(state.dir,'backup.db')),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Local',rpo_seconds:300,rto_seconds:60,maximum_lost_transactions:0}),plan=state.service.createRestorePlan(actors.operator,{backup_ref:backup.backup_id,objective_ref:objective.objective_id,target_path:path.join(state.dir,'restore.db')});assert.throws(()=>state.service.executeRestoreRehearsal(actors.executor,plan.plan_id),{code:'RESTORE_PLAN_NOT_APPROVED'});state.service.close();});
test('approved restore needs independent executor',async()=>{const state=committed(),backup=await state.service.createBackup(actors.operator,path.join(state.dir,'backup.db')),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Local',rpo_seconds:300,rto_seconds:60,maximum_lost_transactions:0}),plan=state.service.createRestorePlan(actors.operator,{backup_ref:backup.backup_id,objective_ref:objective.objective_id,target_path:path.join(state.dir,'restore.db')});state.service.approveRestorePlan(actors.reviewer,plan.plan_id);assert.throws(()=>state.service.executeRestoreRehearsal(actors.reviewer,plan.plan_id),{code:'INDEPENDENT_EXECUTION_REQUIRED'});state.service.close();});
test('restore rehearsal verifies integrity and recovery objectives',async()=>{const state=committed(),claim=state.service.claimOutbox(actors.worker,'tenant-horizonte');state.service.settleOutbox(actors.worker,claim.event_refs[0],{delivered:true});const backup=await state.service.createBackup(actors.operator,path.join(state.dir,'backup.db')),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Local',rpo_seconds:300,rto_seconds:60,maximum_lost_transactions:0}),plan=state.service.createRestorePlan(actors.operator,{backup_ref:backup.backup_id,objective_ref:objective.objective_id,target_path:path.join(state.dir,'restore.db')});state.service.approveRestorePlan(actors.reviewer,plan.plan_id);const run=state.service.executeRestoreRehearsal(actors.executor,plan.plan_id);assert.equal(run.status,'passed');assert(run.delivered_events_preserved);assert.equal(run.lost_transactions,0);assert.equal(run.external_changes,false);state.service.close();});
test('post-backup transaction violates zero-loss objective',async()=>{const state=committed(),backup=await state.service.createBackup(actors.operator,path.join(state.dir,'backup.db')),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Zero loss',rpo_seconds:0,rto_seconds:60,maximum_lost_transactions:0}),plan=state.service.createRestorePlan(actors.operator,{backup_ref:backup.backup_id,objective_ref:objective.objective_id,target_path:path.join(state.dir,'restore.db')});state.service.approveRestorePlan(actors.reviewer,plan.plan_id);state.time.advance(5);state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('site-002')]});const run=state.service.executeRestoreRehearsal(actors.executor,plan.plan_id);assert.equal(run.status,'failed');assert.equal(run.lost_transactions,1);assert.equal(run.objective_met,false);state.service.close();});
test('restore refuses an existing target',async()=>{const state=committed(),backup=await state.service.createBackup(actors.operator,path.join(state.dir,'backup.db')),objective=state.service.defineRecoveryObjective(actors.operator,{name:'Local',rpo_seconds:300,rto_seconds:60,maximum_lost_transactions:0}),target=path.join(state.dir,'restore.db'),plan=state.service.createRestorePlan(actors.operator,{backup_ref:backup.backup_id,objective_ref:objective.objective_id,target_path:target});state.service.approveRestorePlan(actors.reviewer,plan.plan_id);fs.writeFileSync(target,'occupied');assert.throws(()=>state.service.executeRestoreRehearsal(actors.executor,plan.plan_id),{code:'RESTORE_TARGET_EXISTS'});state.service.close();});
test('retention dry run reports eligible delivered events',()=>{const state=committed(),claim=state.service.claimOutbox(actors.worker,'tenant-horizonte');state.service.settleOutbox(actors.worker,claim.event_refs[0],{delivered:true});state.time.advance(40*86400);const policy=state.service.configureRetention(actors.operator,{delivered_outbox_days:30,transaction_days:365,snapshot_days:30,backup_days:30,minimum_backups:2}),run=state.service.runRetention(actors.operator,policy.policy_id,{dryRun:true});assert.equal(run.eligible_delivered_events,1);assert.equal(run.deleted_delivered_events,0);assert.equal(state.service.counts().delivered,1);state.service.close();});
test('retention deletes only old delivered events',()=>{const state=committed(),claim=state.service.claimOutbox(actors.worker,'tenant-horizonte');state.service.settleOutbox(actors.worker,claim.event_refs[0],{delivered:true});state.service.commit(actors.operator,{tenant_id:'tenant-horizonte',writes:[write('site-002')]});state.time.advance(40*86400);const policy=state.service.configureRetention(actors.operator,{delivered_outbox_days:30,transaction_days:365,snapshot_days:30,backup_days:30,minimum_backups:2}),run=state.service.runRetention(actors.operator,policy.policy_id,{dryRun:false});assert.equal(run.deleted_delivered_events,1);assert.equal(run.preserved_pending_events,1);assert.equal(state.service.counts().pending,1);state.service.close();});

function request(instance,url,method='GET'){return new Promise((resolve,reject)=>{const address=instance.address(),req=http.request({hostname:'127.0.0.1',port:address.port,path:url,method},res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body}));});req.on('error',reject);req.end();});}async function startedServer(){const instance=server();await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve);});return instance;}
test('recovery console serves protected noindex HTML',async()=>{const instance=await startedServer();try{const response=await request(instance,'/');assert.equal(response.status,200);assert.match(response.body,/Persistencia y recuperación/);assert.match(response.headers['content-security-policy'],/connect-src 'none'/);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('recovery console supports HEAD',async()=>{const instance=await startedServer();try{const response=await request(instance,'/','HEAD');assert.equal(response.status,200);assert.equal(response.body,'');}finally{await new Promise(resolve=>instance.close(resolve));}});
test('recovery console rejects writes and traversal',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/','POST')).status,405);assert.equal((await request(instance,'/%2e%2e/package.json')).status,404);}finally{await new Promise(resolve=>instance.close(resolve));}});
