'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {createFleetOrchestrator,sha}=require('../packages/fleet-orchestration/index.cjs');const {server}=require('../scripts/serve-fleet-orchestration.cjs');
const actors={operator:{actor_id:'operator-orchestrator',role:'operator',tenant_id:'tenant-horizonte'},reviewer:{actor_id:'operator-reviewer',role:'operator',tenant_id:'tenant-horizonte'},worker:{actor_id:'worker-alpha',role:'service',tenant_id:'tenant-horizonte'},worker2:{actor_id:'worker-beta',role:'service',tenant_id:'tenant-horizonte'},owner:{actor_id:'owner-horizonte',role:'owner',tenant_id:'tenant-horizonte'},other:{actor_id:'worker-other',role:'service',tenant_id:'tenant-other'}};
const refs={recipe1:'rv-'+'1'.repeat(24),recipe2:'rv-'+'2'.repeat(24),design1:'dsv-'+'3'.repeat(24),design2:'dsv-'+'4'.repeat(24),cohort:'cohort-'+'5'.repeat(24)};
function clock(){let value=new Date('2026-10-20T15:00:00Z');return {now:()=>new Date(value),advance:seconds=>{value=new Date(value.getTime()+seconds*1000);}};}
function configured(overrides={}){const time=clock(),service=createFleetOrchestrator({now:time.now});service.configurePolicy(actors.operator,{tenant_id:'tenant-horizonte',max_global:overrides.max_global??3,max_per_operation:overrides.max_per_operation??2,max_per_site:overrides.max_per_site??1,lease_seconds:overrides.lease_seconds??60});service.createWindow(actors.operator,{tenant_id:'tenant-horizonte',name:'Ventana Lima',starts_at:'2026-10-20T14:00:00Z',ends_at:'2026-10-20T18:00:00Z',allowed_operations:['apply_recipe','apply_design','apply_engine','apply_configuration','verify_state','rollback']});const budget=service.createBudget(actors.operator,{tenant_id:'tenant-horizonte',period_start:'2026-10-20T00:00:00Z',period_end:'2026-10-21T00:00:00Z',max_jobs:overrides.max_jobs??100,max_cost_units:overrides.max_cost_units??1000});return {service,time,budget};}
function desiredInput(site='site-001',generation=2,overrides={}){return {tenant_id:'tenant-horizonte',site_id:site,generation,recipe_version_ref:refs.recipe2,design_version_ref:refs.design1,engine_version:'3.2.0',configuration_digest:sha(`desired-${site}-${generation}`),source_cohort_ref:refs.cohort,...overrides};}
function observedInput(site='site-001',generation=1,overrides={}){return {tenant_id:'tenant-horizonte',site_id:site,generation,recipe_version_ref:refs.recipe1,design_version_ref:refs.design1,engine_version:'3.2.0',configuration_digest:sha(`observed-${site}-${generation}`),release_digest:sha(`release-${site}`),...overrides};}
function jobInput(desiredRef,overrides={}){return {tenant_id:'tenant-horizonte',site_id:'site-001',operation:'apply_recipe',idempotency_key:'reconcile:site-001:g2:apply_recipe',payload_digest:sha('payload'),desired_state_ref:desiredRef,priority:70,max_attempts:3,cost_units:3,...overrides};}
function readyJob(overrides={}){const state=configured(overrides),wanted=state.service.setDesiredState(actors.operator,desiredInput()),result=state.service.enqueue(actors.operator,jobInput(wanted.desired_state_id,overrides.job||{}));return {...state,wanted,job:result.job};}

test('policy stores closed tenant limits',()=>{const {service}=configured();const policy=[...service._state.policies.values()][0];assert.equal(policy.max_global,3);assert.equal(policy.lease_seconds,60);});
test('specific concurrency cannot exceed global',()=>{const service=createFleetOrchestrator();assert.throws(()=>service.configurePolicy(actors.operator,{tenant_id:'tenant-horizonte',max_global:1,max_per_operation:2,max_per_site:1,lease_seconds:60}),{code:'CONCURRENCY_POLICY_INVALID'});});
test('maintenance window requires increasing times',()=>assert.throws(()=>createFleetOrchestrator().createWindow(actors.operator,{tenant_id:'tenant-horizonte',name:'Inválida',starts_at:'2026-10-20T18:00:00Z',ends_at:'2026-10-20T14:00:00Z',allowed_operations:['verify_state']}),{code:'WINDOW_INVALID'}));
test('budget requires increasing period',()=>assert.throws(()=>createFleetOrchestrator().createBudget(actors.operator,{tenant_id:'tenant-horizonte',period_start:'2026-10-21T00:00:00Z',period_end:'2026-10-20T00:00:00Z',max_jobs:1,max_cost_units:1}),{code:'BUDGET_PERIOD_INVALID'}));
test('desired state records exact generation and versions',()=>{const {service}=configured(),value=service.setDesiredState(actors.operator,desiredInput());assert.equal(value.generation,2);assert.equal(value.recipe_version_ref,refs.recipe2);});
test('desired generation must increase',()=>{const {service}=configured();service.setDesiredState(actors.operator,desiredInput());assert.throws(()=>service.setDesiredState(actors.operator,desiredInput('site-001',2)),{code:'STALE_GENERATION'});});
test('observation cannot move generation backwards',()=>{const {service}=configured();service.observeState(actors.worker,observedInput('site-001',2));assert.throws(()=>service.observeState(actors.worker,observedInput('site-001',1)),{code:'STALE_OBSERVATION'});});
test('reconciliation requires both states',()=>{const {service}=configured();service.setDesiredState(actors.operator,desiredInput());assert.throws(()=>service.reconcileSite(actors.operator,'tenant-horizonte','site-001'),{code:'STATE_INCOMPLETE'});});
test('equal desired and observed state is no-op',()=>{const {service}=configured(),d=desiredInput('site-001',2);service.setDesiredState(actors.operator,d);service.observeState(actors.worker,observedInput('site-001',2,{recipe_version_ref:d.recipe_version_ref,design_version_ref:d.design_version_ref,engine_version:d.engine_version,configuration_digest:d.configuration_digest}));const plan=service.reconcileSite(actors.operator,'tenant-horizonte','site-001');assert.equal(plan.status,'no_op');assert.deepEqual(plan.operations,[]);});
test('recipe drift produces apply and verify operations',()=>{const {service}=configured();service.setDesiredState(actors.operator,desiredInput());service.observeState(actors.worker,observedInput('site-001',2,{configuration_digest:sha('desired-site-001-2')}));const plan=service.reconcileSite(actors.operator,'tenant-horizonte','site-001');assert.deepEqual(plan.operations,['apply_recipe','verify_state']);});
test('all drift maps to ordered operations',()=>{const {service}=configured();service.setDesiredState(actors.operator,desiredInput('site-001',3,{design_version_ref:refs.design2,engine_version:'3.3.0'}));service.observeState(actors.worker,observedInput());const plan=service.reconcileSite(actors.operator,'tenant-horizonte','site-001');assert.deepEqual(plan.operations,['apply_recipe','apply_design','apply_engine','apply_configuration','verify_state']);});
test('desired generation behind observed is blocked',()=>{const {service}=configured();service.setDesiredState(actors.operator,desiredInput('site-001',1));service.observeState(actors.worker,observedInput('site-001',2));const plan=service.reconcileSite(actors.operator,'tenant-horizonte','site-001');assert.equal(plan.status,'blocked');assert.deepEqual(plan.operations,[]);});
test('enqueue stores only digest and desired reference',()=>{const state=readyJob();assert.equal(state.job.status,'queued');assert.equal(state.job.payload,undefined);assert.match(state.job.payload_digest,/^[a-f0-9]{64}$/);});
test('same idempotency request returns original job',()=>{const state=readyJob(),again=state.service.enqueue(actors.operator,jobInput(state.wanted.desired_state_id));assert.equal(again.duplicate,true);assert.equal(again.job.job_id,state.job.job_id);assert.equal(state.service._state.jobs.size,1);});
test('same idempotency key with changed request is rejected',()=>{const state=readyJob();assert.throws(()=>state.service.enqueue(actors.operator,jobInput(state.wanted.desired_state_id,{payload_digest:sha('changed')})),{code:'IDEMPOTENCY_CONFLICT'});});
test('tenant isolation blocks enqueue',()=>{const state=readyJob();assert.throws(()=>state.service.enqueue(actors.other,jobInput(state.wanted.desired_state_id)),{code:'ACCESS_DENIED'});});
test('claim needs concurrency policy',()=>{const time=clock(),service=createFleetOrchestrator({now:time.now}),d=service.setDesiredState(actors.operator,desiredInput());service.enqueue(actors.operator,jobInput(d.desired_state_id));assert.equal(service.claim(actors.worker,'tenant-horizonte').reason,'policy_missing');});
test('empty queue produces explicit reason',()=>assert.equal(configured().service.claim(actors.worker,'tenant-horizonte').reason,'queue_empty'));
test('job outside maintenance window is not claimed',()=>{const state=readyJob();state.time.advance(4*3600);assert.equal(state.service.claim(actors.worker,'tenant-horizonte').reason,'window_or_specific_concurrency_limit');});
test('claim requires current budget',()=>{const time=clock(),service=createFleetOrchestrator({now:time.now});service.configurePolicy(actors.operator,{tenant_id:'tenant-horizonte',max_global:1,max_per_operation:1,max_per_site:1,lease_seconds:60});service.createWindow(actors.operator,{tenant_id:'tenant-horizonte',name:'Ventana',starts_at:'2026-10-20T14:00:00Z',ends_at:'2026-10-20T18:00:00Z',allowed_operations:['apply_recipe']});const d=service.setDesiredState(actors.operator,desiredInput());service.enqueue(actors.operator,jobInput(d.desired_state_id));assert.equal(service.claim(actors.worker,'tenant-horizonte').reason,'budget_missing_or_closed');});
test('claim creates lease and consumes budget',()=>{const state=readyJob(),result=state.service.claim(actors.worker,'tenant-horizonte');assert(result.claimed);assert.equal(result.job.status,'leased');assert.equal(state.service._state.budgets.get(state.budget.budget_id).consumed_cost_units,3);});
test('higher priority job claims first',()=>{const state=configured(),a=state.service.setDesiredState(actors.operator,desiredInput('site-001')),b=state.service.setDesiredState(actors.operator,desiredInput('site-002'));state.service.enqueue(actors.operator,jobInput(a.desired_state_id,{priority:20}));state.service.enqueue(actors.operator,jobInput(b.desired_state_id,{site_id:'site-002',idempotency_key:'reconcile:site-002:g2:apply_recipe',priority:90}));assert.equal(state.service.claim(actors.worker,'tenant-horizonte').job.site_id,'site-002');});
test('global concurrency limit blocks additional claim',()=>{const state=configured({max_global:1,max_per_operation:1,max_per_site:1}),a=state.service.setDesiredState(actors.operator,desiredInput('site-001')),b=state.service.setDesiredState(actors.operator,desiredInput('site-002'));state.service.enqueue(actors.operator,jobInput(a.desired_state_id));state.service.enqueue(actors.operator,jobInput(b.desired_state_id,{site_id:'site-002',idempotency_key:'reconcile:site-002:g2:apply_recipe'}));state.service.claim(actors.worker,'tenant-horizonte');assert.equal(state.service.claim(actors.worker2,'tenant-horizonte').reason,'tenant_concurrency_limit');});
test('per operation limit skips same operation',()=>{const state=configured({max_global:3,max_per_operation:1,max_per_site:1}),a=state.service.setDesiredState(actors.operator,desiredInput('site-001')),b=state.service.setDesiredState(actors.operator,desiredInput('site-002'));state.service.enqueue(actors.operator,jobInput(a.desired_state_id));state.service.enqueue(actors.operator,jobInput(b.desired_state_id,{site_id:'site-002',idempotency_key:'reconcile:site-002:g2:apply_recipe'}));state.service.claim(actors.worker,'tenant-horizonte');assert.equal(state.service.claim(actors.worker2,'tenant-horizonte').reason,'window_or_specific_concurrency_limit');});
test('per site limit permits a different site only',()=>{const state=configured({max_global:3,max_per_operation:3,max_per_site:1}),a=state.service.setDesiredState(actors.operator,desiredInput('site-001')),b=state.service.setDesiredState(actors.operator,desiredInput('site-002'));state.service.enqueue(actors.operator,jobInput(a.desired_state_id));state.service.enqueue(actors.operator,jobInput(a.desired_state_id,{operation:'verify_state',idempotency_key:'reconcile:site-001:g2:verify_state'}));state.service.enqueue(actors.operator,jobInput(b.desired_state_id,{site_id:'site-002',idempotency_key:'reconcile:site-002:g2:verify_state'}));state.service.claim(actors.worker,'tenant-horizonte');assert.equal(state.service.claim(actors.worker2,'tenant-horizonte').job.site_id,'site-002');});
test('job budget exhaustion fails closed',()=>{const state=readyJob({max_jobs:1,max_cost_units:100});state.service.claim(actors.worker,'tenant-horizonte');const d=state.service.setDesiredState(actors.operator,desiredInput('site-002'));state.service.enqueue(actors.operator,jobInput(d.desired_state_id,{site_id:'site-002',idempotency_key:'reconcile:site-002:g2:apply_recipe'}));assert.equal(state.service.claim(actors.worker2,'tenant-horizonte').reason,'budget_missing_or_closed');});
test('cost budget exhaustion is explicit',()=>{const state=readyJob({max_jobs:10,max_cost_units:2});assert.equal(state.service.claim(actors.worker,'tenant-horizonte').reason,'budget_exhausted');});
test('heartbeat extends owned lease',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte'),before=claimed.lease.expires_at;state.time.advance(20);const after=state.service.heartbeat(actors.worker,claimed.lease.lease_id);assert(Date.parse(after.expires_at)>Date.parse(before));});
test('another worker cannot heartbeat lease',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte');assert.throws(()=>state.service.heartbeat(actors.worker2,claimed.lease.lease_id),{code:'LEASE_OWNER_MISMATCH'});});
test('completion releases lease and completes idempotency',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte'),job=state.service.complete(actors.worker,claimed.lease.lease_id);assert.equal(job.status,'succeeded');assert.equal([...state.service._state.idempotency.values()][0].status,'completed');});
test('transient failure schedules 30 second retry',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte'),result=state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'UPSTREAM_TIMEOUT',safe_summary:'Synthetic upstream timed out.'});assert.equal(result.job.status,'retry_scheduled');assert.equal(result.retry.delay_seconds,30);});
test('retry is not claimable before available time',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte');state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'UPSTREAM_TIMEOUT',safe_summary:'Synthetic upstream timed out.'});assert.equal(state.service.claim(actors.worker,'tenant-horizonte').reason,'queue_empty');});
test('retry becomes claimable after backoff',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte');state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'UPSTREAM_TIMEOUT',safe_summary:'Synthetic upstream timed out.'});state.time.advance(31);assert(state.service.claim(actors.worker,'tenant-horizonte').claimed);});
test('second failure doubles retry delay',()=>{const state=readyJob(),first=state.service.claim(actors.worker,'tenant-horizonte');state.service.failJob(actors.worker,first.lease.lease_id,{failure_code:'UPSTREAM_TIMEOUT',safe_summary:'Synthetic upstream timed out.'});state.time.advance(31);const second=state.service.claim(actors.worker,'tenant-horizonte'),result=state.service.failJob(actors.worker,second.lease.lease_id,{failure_code:'UPSTREAM_TIMEOUT',safe_summary:'Synthetic upstream timed out.'});assert.equal(result.retry.delay_seconds,60);});
test('last failed attempt enters dead letter queue',()=>{const state=readyJob({job:{max_attempts:1}}),claimed=state.service.claim(actors.worker,'tenant-horizonte'),result=state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'VALIDATION_FAILED',safe_summary:'Synthetic validation failed.'});assert.equal(result.job.status,'dead_lettered');assert.equal(result.dead_letter.status,'open');});
test('failure code must be closed and safe',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte');assert.throws(()=>state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'bad code',safe_summary:'Synthetic failure.'}),{code:'FAILURE_CODE_INVALID'});});
test('expired lease is swept into retry',()=>{const state=readyJob({lease_seconds:10}),claimed=state.service.claim(actors.worker,'tenant-horizonte');state.time.advance(11);const results=state.service.sweepExpiredLeases(actors.operator,'tenant-horizonte');assert.equal(results.length,1);assert.equal(results[0].job.status,'retry_scheduled');assert.equal(state.service._state.leases.get(claimed.lease.lease_id).status,'expired');});
test('dead letter can be replayed with new idempotency key',()=>{const state=readyJob({job:{max_attempts:1}}),claimed=state.service.claim(actors.worker,'tenant-horizonte'),failed=state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'VALIDATION_FAILED',safe_summary:'Synthetic validation failed.'}),replayed=state.service.replayDeadLetter(actors.operator,failed.dead_letter.entry_id);assert.equal(replayed.duplicate,false);assert.equal(replayed.job.status,'queued');});
test('dead letter cannot be replayed twice',()=>{const state=readyJob({job:{max_attempts:1}}),claimed=state.service.claim(actors.worker,'tenant-horizonte'),failed=state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'VALIDATION_FAILED',safe_summary:'Synthetic validation failed.'});state.service.replayDeadLetter(actors.operator,failed.dead_letter.entry_id);assert.throws(()=>state.service.replayDeadLetter(actors.operator,failed.dead_letter.entry_id),{code:'REPLAY_NOT_ALLOWED'});});
test('reconciliation run counts no-op ready and blocked sites',()=>{const state=configured();const same=desiredInput('site-same',2),ready=desiredInput('site-ready',2),blocked=desiredInput('site-blocked',1);state.service.setDesiredState(actors.operator,same);state.service.observeState(actors.worker,observedInput('site-same',2,{recipe_version_ref:same.recipe_version_ref,design_version_ref:same.design_version_ref,engine_version:same.engine_version,configuration_digest:same.configuration_digest}));state.service.setDesiredState(actors.operator,ready);state.service.observeState(actors.worker,observedInput('site-ready',1));state.service.setDesiredState(actors.operator,blocked);state.service.observeState(actors.worker,observedInput('site-blocked',2));const run=state.service.runReconciliation(actors.operator,{tenant_id:'tenant-horizonte',site_ids:['site-same','site-ready','site-blocked'],budget_ref:state.budget.budget_id});assert.equal(run.no_op_sites,1);assert.equal(run.ready_sites,1);assert.equal(run.blocked_sites,1);assert(run.jobs_enqueued>0);});
test('repeated reconciliation suppresses duplicate jobs',()=>{const state=configured(),d=desiredInput('site-ready',2);state.service.setDesiredState(actors.operator,d);state.service.observeState(actors.worker,observedInput('site-ready',1));state.service.runReconciliation(actors.operator,{tenant_id:'tenant-horizonte',site_ids:['site-ready'],budget_ref:state.budget.budget_id});const again=state.service.runReconciliation(actors.operator,{tenant_id:'tenant-horizonte',site_ids:['site-ready'],budget_ref:state.budget.budget_id});assert.equal(again.jobs_enqueued,0);assert(again.duplicates_suppressed>0);});
test('queue snapshot reports jobs leases retries and budget',()=>{const state=readyJob(),claimed=state.service.claim(actors.worker,'tenant-horizonte');state.service.failJob(actors.worker,claimed.lease.lease_id,{failure_code:'UPSTREAM_TIMEOUT',safe_summary:'Synthetic upstream timed out.'});const snapshot=state.service.queueSnapshot(actors.owner,'tenant-horizonte',state.budget.budget_id);assert.equal(snapshot.scheduled_retries,1);assert.equal(snapshot.job_counts.retry_scheduled,1);assert.equal(snapshot.budget_remaining_jobs,99);});
test('owner reads but cannot enqueue',()=>{const state=readyJob();assert.equal(state.service.read(actors.owner,'tenant-horizonte').jobs.length,1);assert.throws(()=>state.service.enqueue(actors.owner,jobInput(state.wanted.desired_state_id,{idempotency_key:'reconcile:site-001:g2:other'})),{code:'ACCESS_DENIED'});});
test('cross tenant read is denied',()=>{const state=readyJob();assert.throws(()=>state.service.read(actors.other,'tenant-horizonte'),{code:'ACCESS_DENIED'});});

function request(instance,url,method='GET'){return new Promise((resolve,reject)=>{const address=instance.address(),req=http.request({hostname:'127.0.0.1',port:address.port,path:url,method},res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body}));});req.on('error',reject);req.end();});}
async function startedServer(){const instance=server();await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve);});return instance;}
test('orchestration console serves protected noindex HTML',async()=>{const instance=await startedServer();try{const response=await request(instance,'/');assert.equal(response.status,200);assert.match(response.body,/Orquestación durable/);assert.match(response.headers['content-security-policy'],/connect-src 'none'/);assert.match(response.headers['x-robots-tag'],/noindex/);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('orchestration console supports HEAD',async()=>{const instance=await startedServer();try{const response=await request(instance,'/','HEAD');assert.equal(response.status,200);assert.equal(response.body,'');}finally{await new Promise(resolve=>instance.close(resolve));}});
test('orchestration console rejects writes',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/','POST')).status,405);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('orchestration console blocks traversal',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/%2e%2e/package.json')).status,404);assert.equal((await request(instance,'/unknown.txt')).status,404);}finally{await new Promise(resolve=>instance.close(resolve));}});
