'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {createFleetGovernance,compareVersions,inRange,sha}=require('../packages/fleet-governance/index.cjs');
const {server}=require('../scripts/serve-fleet-governance.cjs');
const actors={maker:{actor_id:'operator-maker',role:'operator',tenant_id:'tenant-horizonte'},reviewer:{actor_id:'operator-reviewer',role:'operator',tenant_id:'tenant-horizonte'},release:{actor_id:'operator-release',role:'operator',tenant_id:'tenant-horizonte'},owner:{actor_id:'owner-horizonte',role:'owner',tenant_id:'tenant-horizonte'},service:{actor_id:'service-drift',role:'service',tenant_id:'tenant-horizonte'},other:{actor_id:'operator-other',role:'operator',tenant_id:'tenant-other'}};
const create=()=>createFleetGovernance({now:()=>new Date('2026-10-12T15:00:00Z')});
const recipeInput=(version='1.0.0',overrides={})=>({tenant_id:'tenant-horizonte',recipe_id:'inmobiliaria-asesor',version,archetype:'advisor',engine_range:{minimum:'3.0.0',maximum_exclusive:'4.0.0'},design_requirements:[{design_system_id:'horizonte-editorial',minimum:'2.0.0',maximum_exclusive:'3.0.0'}],source_proposal_refs:[],artifact:{sections:['hero','properties','contact'],version},...overrides});
const designInput=(version='2.3.0',overrides={})=>({tenant_id:'tenant-horizonte',design_system_id:'horizonte-editorial',version,tokens:{ink:'#111111',paper:'#f4efe7'},components:{hero:'v2',card:'v3'},accessibility_baseline:94,...overrides});
function active(service=create(),recipeVersion='1.0.0',designVersion='2.3.0'){const rv=service.registerRecipe(actors.maker,recipeInput(recipeVersion)),dv=service.registerDesign(actors.maker,designInput(designVersion));service.activateVersion(actors.reviewer,'recipe',rv.recipe_version_id);service.activateVersion(actors.reviewer,'design',dv.design_version_id);return {service,rv:service._state.recipeVersions.get(rv.recipe_version_id),dv:service._state.designVersions.get(dv.design_version_id)};}
function addSite(state,id='site-horizonte-001',overrides={}){return state.service.registerSite(actors.maker,{tenant_id:'tenant-horizonte',site_id:id,archetype:'advisor',cohort_label:'lima-piloto',current_recipe_ref:state.rv.recipe_version_id,current_design_ref:state.dv.design_version_id,engine_version:'3.2.0',release_digest:sha(id),...overrides});}
const dimensions=(overrides={})=>({truth:96,visual:92,accessibility:94,performance:90,conversion:88,...overrides});
const gates=(overrides={})=>({schema_valid:true,truth_verified:true,privacy_safe:true,rollback_ready:true,...overrides});
function rolloutState(){const base=active(),siteA=addSite(base,'site-horizonte-001'),siteB=addSite(base,'site-horizonte-002');const target=base.service.registerRecipe(actors.maker,recipeInput('1.1.0'));base.service.activateVersion(actors.reviewer,'recipe',target.recipe_version_id);const cohort=base.service.createCohort(actors.maker,{tenant_id:'tenant-horizonte',name:'Piloto Lima Centro',site_ids:[siteA.site_id,siteB.site_id],target_recipe_ref:target.recipe_version_id,target_design_ref:base.dv.design_version_id,steps_percent:[25,50,100],quality_threshold:85,rollback_threshold:78,max_incidents:0});base.service.approveCohort(actors.reviewer,cohort.cohort_id);base.service.startCohort(actors.release,cohort.cohort_id);return {...base,siteA,siteB,target,cohort:base.service._state.cohorts.get(cohort.cohort_id)};}

test('semantic versions compare numerically',()=>{assert(compareVersions('1.10.0','1.2.9')>0);assert.equal(compareVersions('2.0.0','2.0.0'),0);});
test('invalid semantic version is rejected',()=>assert.throws(()=>compareVersions('v1','1.0.0'),{code:'SEMVER_INVALID'}));
test('range excludes its upper bound',()=>{assert(inRange('2.9.9','2.0.0','3.0.0'));assert(!inRange('3.0.0','2.0.0','3.0.0'));});
test('recipe registration creates a draft without auto publication',()=>{const value=create().registerRecipe(actors.maker,recipeInput());assert.equal(value.status,'draft');assert.equal(value.auto_publish,false);assert.match(value.artifact_digest,/^[a-f0-9]{64}$/);});
test('design registration stores digests instead of source objects',()=>{const value=create().registerDesign(actors.maker,designInput());assert.match(value.token_digest,/^[a-f0-9]{64}$/);assert.equal(value.tokens,undefined);});
test('duplicate recipe version is rejected',()=>{const s=create();s.registerRecipe(actors.maker,recipeInput());assert.throws(()=>s.registerRecipe(actors.maker,recipeInput()),{code:'VERSION_EXISTS'});});
test('invalid increasing version range is rejected',()=>assert.throws(()=>create().registerRecipe(actors.maker,recipeInput('1.0.0',{engine_range:{minimum:'4.0.0',maximum_exclusive:'3.0.0'}})),{code:'VERSION_RANGE_INVALID'}));
test('creator cannot activate own version',()=>{const s=create(),v=s.registerRecipe(actors.maker,recipeInput());assert.throws(()=>s.activateVersion(actors.maker,'recipe',v.recipe_version_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('independent reviewer activates recipe',()=>{const s=create(),v=s.registerRecipe(actors.maker,recipeInput());assert.equal(s.activateVersion(actors.reviewer,'recipe',v.recipe_version_id).status,'active');});
test('independent reviewer activates design system',()=>{const s=create(),v=s.registerDesign(actors.maker,designInput());assert.equal(s.activateVersion(actors.reviewer,'design',v.design_version_id).status,'active');});
test('active versions within ranges are compatible',()=>{const state=active(),value=state.service.evaluateCompatibility(actors.maker,{tenant_id:'tenant-horizonte',recipe_version_ref:state.rv.recipe_version_id,design_version_ref:state.dv.design_version_id,engine_version:'3.2.0'});assert.equal(value.verdict,'compatible');});
test('engine outside range is incompatible',()=>{const state=active(),value=state.service.evaluateCompatibility(actors.maker,{tenant_id:'tenant-horizonte',recipe_version_ref:state.rv.recipe_version_id,design_version_ref:state.dv.design_version_id,engine_version:'4.0.0'});assert(value.reasons.includes('engine_out_of_range'));});
test('design family outside recipe is incompatible',()=>{const s=create(),rv=s.registerRecipe(actors.maker,recipeInput()),dv=s.registerDesign(actors.maker,designInput('2.3.0',{design_system_id:'otro-sistema'}));s.activateVersion(actors.reviewer,'recipe',rv.recipe_version_id);s.activateVersion(actors.reviewer,'design',dv.design_version_id);const value=s.evaluateCompatibility(actors.maker,{tenant_id:'tenant-horizonte',recipe_version_ref:rv.recipe_version_id,design_version_ref:dv.design_version_id,engine_version:'3.2.0'});assert(value.reasons.includes('design_system_not_allowed'));});
test('draft versions cannot be compatible',()=>{const s=create(),rv=s.registerRecipe(actors.maker,recipeInput()),dv=s.registerDesign(actors.maker,designInput());const value=s.evaluateCompatibility(actors.maker,{tenant_id:'tenant-horizonte',recipe_version_ref:rv.recipe_version_id,design_version_ref:dv.design_version_id,engine_version:'3.2.0'});assert.equal(value.verdict,'incompatible');});
test('site registration pins exact compatible versions',()=>{const state=active(),value=addSite(state);assert.equal(value.status,'stable');assert.equal(value.target_recipe_ref,null);});
test('duplicate fleet site is rejected',()=>{const state=active();addSite(state);assert.throws(()=>addSite(state),{code:'SITE_EXISTS'});});
test('cross tenant site registration is denied',()=>{const state=active();assert.throws(()=>state.service.registerSite(actors.other,{tenant_id:'tenant-horizonte'}),{code:'ACCESS_DENIED'});});
test('site registration blocks incompatible engine',()=>{const state=active();assert.throws(()=>addSite(state,'site-bad',{engine_version:'4.0.0'}),{code:'INCOMPATIBLE_VERSIONS'});});
test('quality score uses declared weights',()=>{const state=active(),site=addSite(state),value=state.service.scoreSite(actors.maker,{tenant_id:'tenant-horizonte',site_id:site.site_id,dimensions:dimensions(),hard_gates:gates()});assert.equal(value.overall_score,92);assert.equal(value.status,'passing');});
test('quality near threshold is watch',()=>{const state=active(),site=addSite(state),value=state.service.scoreSite(actors.maker,{tenant_id:'tenant-horizonte',site_id:site.site_id,dimensions:dimensions({truth:82,visual:82,accessibility:82,performance:82,conversion:82}),hard_gates:gates()});assert.equal(value.status,'watch');});
test('failed hard gate forces failing status',()=>{const state=active(),site=addSite(state),value=state.service.scoreSite(actors.maker,{tenant_id:'tenant-horizonte',site_id:site.site_id,dimensions:dimensions(),hard_gates:gates({privacy_safe:false})});assert.equal(value.status,'failing');});
test('invalid quality dimension is rejected',()=>{const state=active(),site=addSite(state);assert.throws(()=>state.service.scoreSite(actors.maker,{tenant_id:'tenant-horizonte',site_id:site.site_id,dimensions:dimensions({visual:101}),hard_gates:gates()}),{code:'QUALITY_DIMENSION_INVALID'});});
test('cohort creation pins targets and ordered steps',()=>{const state=rolloutState();assert.deepEqual(state.cohort.steps_percent,[25,50,100]);assert.equal(state.cohort.status,'running');});
test('duplicate site in cohort is rejected',()=>{const base=active(),one=addSite(base),target=base.service.registerRecipe(actors.maker,recipeInput('1.1.0'));base.service.activateVersion(actors.reviewer,'recipe',target.recipe_version_id);assert.throws(()=>base.service.createCohort(actors.maker,{tenant_id:'tenant-horizonte',name:'Duplicada',site_ids:[one.site_id,one.site_id],target_recipe_ref:target.recipe_version_id,target_design_ref:base.dv.design_version_id,steps_percent:[100],quality_threshold:85,rollback_threshold:78,max_incidents:0}),{code:'DUPLICATE_SITE'});});
test('rollout steps must be ordered and end at 100',()=>{const base=active(),one=addSite(base);assert.throws(()=>base.service.createCohort(actors.maker,{tenant_id:'tenant-horizonte',name:'Desordenada',site_ids:[one.site_id],target_recipe_ref:base.rv.recipe_version_id,target_design_ref:base.dv.design_version_id,steps_percent:[50,25],quality_threshold:85,rollback_threshold:78,max_incidents:0}),{code:'ROLLOUT_STEPS_INVALID'});});
test('cohort creator cannot approve it',()=>{const base=active(),one=addSite(base),value=base.service.createCohort(actors.maker,{tenant_id:'tenant-horizonte',name:'Aprobación independiente',site_ids:[one.site_id],target_recipe_ref:base.rv.recipe_version_id,target_design_ref:base.dv.design_version_id,steps_percent:[100],quality_threshold:85,rollback_threshold:78,max_incidents:0});assert.throws(()=>base.service.approveCohort(actors.maker,value.cohort_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('unapproved cohort cannot start',()=>{const base=active(),one=addSite(base),value=base.service.createCohort(actors.maker,{tenant_id:'tenant-horizonte',name:'Sin aprobar',site_ids:[one.site_id],target_recipe_ref:base.rv.recipe_version_id,target_design_ref:base.dv.design_version_id,steps_percent:[100],quality_threshold:85,rollback_threshold:78,max_incidents:0});assert.throws(()=>base.service.startCohort(actors.release,value.cohort_id),{code:'COHORT_NOT_APPROVED'});});
test('starting cohort schedules every member',()=>{const state=rolloutState();assert(state.cohort.site_ids.every(id=>state.service._state.sites.get(id).status==='scheduled'));});
test('checkpoint must follow configured order',()=>{const state=rolloutState();assert.throws(()=>state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:50,observed_sites:2,average_quality_score:90,incident_count:0,critical_drift_count:0}),{code:'STEP_OUT_OF_ORDER'});});
test('passing checkpoint advances cohort and sites',()=>{const state=rolloutState(),value=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:91,incident_count:0,critical_drift_count:0});assert.equal(value.verdict,'pass');assert.equal(state.cohort.current_step,25);assert.equal(state.service._state.sites.get(state.siteA.site_id).status,'canary');});
test('quality under advance threshold holds cohort',()=>{const state=rolloutState(),value=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:82,incident_count:0,critical_drift_count:0});assert.equal(value.verdict,'hold');assert.equal(state.cohort.status,'paused');});
test('incident beyond guardrail requires rollback',()=>{const state=rolloutState(),value=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:92,incident_count:1,critical_drift_count:0});assert.equal(value.verdict,'rollback');});
test('score under rollback threshold requires rollback',()=>{const state=rolloutState(),value=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:70,incident_count:0,critical_drift_count:0});assert.equal(value.verdict,'rollback');});
test('matching digest reports no drift',()=>{const state=active(),item=addSite(state),digest=sha('release');const value=state.service.detectDrift(actors.service,{tenant_id:'tenant-horizonte',site_id:item.site_id,asset_type:'configuration',expected_digest:digest,observed_digest:digest});assert.equal(value.severity,'none');assert.equal(value.status,'resolved');});
test('recipe digest mismatch is critical',()=>{const state=active(),item=addSite(state),value=state.service.detectDrift(actors.service,{tenant_id:'tenant-horizonte',site_id:item.site_id,asset_type:'recipe',expected_digest:sha('expected'),observed_digest:sha('observed')});assert.equal(value.severity,'critical');assert.equal(value.recommended_action,'rollback');});
test('engine digest mismatch pauses rollout',()=>{const state=active(),item=addSite(state),value=state.service.detectDrift(actors.service,{tenant_id:'tenant-horizonte',site_id:item.site_id,asset_type:'engine',expected_digest:sha('expected'),observed_digest:sha('observed')});assert.equal(value.severity,'high');assert.equal(value.recommended_action,'pause');});
test('non rollback checkpoint cannot authorize rollback',()=>{const state=rolloutState(),checkpoint=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:82,incident_count:0,critical_drift_count:0});assert.throws(()=>state.service.planRollback(actors.maker,{cohort_ref:state.cohort.cohort_id,trigger_type:'checkpoint',trigger_ref:checkpoint.checkpoint_id}),{code:'ROLLBACK_TRIGGER_INVALID'});});
test('rollback record is local and immutable in intent',()=>{const state=rolloutState(),checkpoint=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:70,incident_count:0,critical_drift_count:0}),value=state.service.planRollback(actors.maker,{cohort_ref:state.cohort.cohort_id,trigger_type:'checkpoint',trigger_ref:checkpoint.checkpoint_id});assert.equal(value.external_changes,false);assert.equal(value.status,'planned');});
test('rollback planner cannot execute it',()=>{const state=rolloutState(),checkpoint=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:70,incident_count:0,critical_drift_count:0}),value=state.service.planRollback(actors.maker,{cohort_ref:state.cohort.cohort_id,trigger_type:'checkpoint',trigger_ref:checkpoint.checkpoint_id});assert.throws(()=>state.service.executeRollback(actors.maker,value.rollback_id),{code:'INDEPENDENT_EXECUTION_REQUIRED'});});
test('independent rollback execution clears targets',()=>{const state=rolloutState(),checkpoint=state.service.evaluateCheckpoint(actors.reviewer,{cohort_ref:state.cohort.cohort_id,step_percent:25,observed_sites:2,average_quality_score:70,incident_count:0,critical_drift_count:0}),planned=state.service.planRollback(actors.maker,{cohort_ref:state.cohort.cohort_id,trigger_type:'checkpoint',trigger_ref:checkpoint.checkpoint_id}),value=state.service.executeRollback(actors.release,planned.rollback_id);assert.equal(value.status,'executed');assert.equal(state.cohort.status,'rolled_back');assert.equal(state.service._state.sites.get(state.siteA.site_id).target_recipe_ref,null);});
test('deprecation successor must differ',()=>{const state=active(),item=addSite(state);assert.throws(()=>state.service.createDeprecation(actors.maker,{tenant_id:'tenant-horizonte',asset_type:'recipe',deprecated_version_ref:state.rv.recipe_version_id,successor_version_ref:state.rv.recipe_version_id,affected_site_ids:[item.site_id],deadline:'2026-12-31T00:00:00Z',blockers:[]}),{code:'SUCCESSOR_INVALID'});});
test('deprecation plan begins as draft',()=>{const state=active(),item=addSite(state),target=state.service.registerRecipe(actors.maker,recipeInput('1.1.0')),value=state.service.createDeprecation(actors.maker,{tenant_id:'tenant-horizonte',asset_type:'recipe',deprecated_version_ref:state.rv.recipe_version_id,successor_version_ref:target.recipe_version_id,affected_site_ids:[item.site_id],deadline:'2026-12-31T00:00:00Z',blockers:['owner_acceptance_pending']});assert.equal(value.status,'draft');});
test('deprecation creator cannot approve it',()=>{const state=active(),item=addSite(state),target=state.service.registerRecipe(actors.maker,recipeInput('1.1.0')),value=state.service.createDeprecation(actors.maker,{tenant_id:'tenant-horizonte',asset_type:'recipe',deprecated_version_ref:state.rv.recipe_version_id,successor_version_ref:target.recipe_version_id,affected_site_ids:[item.site_id],deadline:'2026-12-31T00:00:00Z',blockers:[]});assert.throws(()=>state.service.approveDeprecation(actors.maker,value.plan_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('independent reviewer approves deprecation plan',()=>{const state=active(),item=addSite(state),target=state.service.registerRecipe(actors.maker,recipeInput('1.1.0')),value=state.service.createDeprecation(actors.maker,{tenant_id:'tenant-horizonte',asset_type:'recipe',deprecated_version_ref:state.rv.recipe_version_id,successor_version_ref:target.recipe_version_id,affected_site_ids:[item.site_id],deadline:'2026-12-31T00:00:00Z',blockers:[]});assert.equal(state.service.approveDeprecation(actors.reviewer,value.plan_id).status,'approved');});
test('portfolio snapshot aggregates latest fleet state',()=>{const state=active(),a=addSite(state,'site-horizonte-001'),b=addSite(state,'site-horizonte-002');state.service.scoreSite(actors.maker,{tenant_id:'tenant-horizonte',site_id:a.site_id,dimensions:dimensions(),hard_gates:gates()});state.service.scoreSite(actors.maker,{tenant_id:'tenant-horizonte',site_id:b.site_id,dimensions:dimensions({performance:70}),hard_gates:gates()});const value=state.service.portfolioSnapshot(actors.owner,'tenant-horizonte');assert.equal(value.total_sites,2);assert.equal(Object.values(value.quality_status_counts).reduce((sum,count)=>sum+count,0),2);});
test('tenant reader sees only authorized tenant',()=>{const state=active();addSite(state);assert.equal(state.service.read(actors.owner,'tenant-horizonte').sites.length,1);assert.throws(()=>state.service.read(actors.other,'tenant-horizonte'),{code:'ACCESS_DENIED'});});

function request(instance,url,method='GET'){return new Promise((resolve,reject)=>{const address=instance.address(),req=http.request({hostname:'127.0.0.1',port:address.port,path:url,method},res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body}));});req.on('error',reject);req.end();});}
async function startedServer(){const instance=server();await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve);});return instance;}
test('fleet console serves noindex CSP protected HTML',async()=>{const instance=await startedServer();try{const response=await request(instance,'/');assert.equal(response.status,200);assert.match(response.body,/Gobierno de flota/);assert.match(response.headers['content-security-policy'],/connect-src 'none'/);assert.match(response.headers['x-robots-tag'],/noindex/);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('fleet console supports HEAD',async()=>{const instance=await startedServer();try{const response=await request(instance,'/','HEAD');assert.equal(response.status,200);assert.equal(response.body,'');}finally{await new Promise(resolve=>instance.close(resolve));}});
test('fleet console rejects writes',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/','POST')).status,405);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('fleet console blocks traversal and unknown assets',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/%2e%2e/package.json')).status,404);assert.equal((await request(instance,'/unknown.txt')).status,404);}finally{await new Promise(resolve=>instance.close(resolve));}});
