'use strict';const test=require('node:test'),assert=require('node:assert/strict');const {createGoLiveControl}=require('../packages/go-live-control/index.cjs');const {server}=require('../scripts/serve-go-live-control.cjs');
const actors={creator:{actor_id:'operator-creator',role:'operator',tenant_id:'tenant-alpha'},reviewer:{actor_id:'operator-reviewer',role:'operator',tenant_id:'tenant-alpha'},owner:{actor_id:'owner-alpha',role:'owner',tenant_id:'tenant-alpha'},admin:{actor_id:'admin-root',role:'admin',tenant_id:null},other:{actor_id:'operator-other',role:'operator',tenant_id:'tenant-beta'},otherOwner:{actor_id:'owner-other',role:'owner',tenant_id:'tenant-beta'}};
const base={tenant_id:'tenant-alpha',business_id:'business-alpha',site_id:'site-alpha',pilot_package_ref:`pilotp-${'a'.repeat(24)}`,package_digest:'b'.repeat(64),synthetic:true,hostname:'alpha.guialima.online',window:{start_at:'2026-10-03T14:00:00Z',end_at:'2026-10-03T16:00:00Z',timezone:'America/Lima'},slo_targets:{availability_min_percent:99,latency_p95_max_ms:500},slo_policy_refs:['slo-router'],incident_owner:'operator-incident',rollback_target_ref:'release-stable'};
const service=()=>createGoLiveControl({now:()=>new Date('2026-10-01T14:00:00Z')});
function planned(s=service()){return {s,plan:s.createPlan(actors.creator,base)};}
function frozen(s=service()){const state=planned(s),freeze=state.s.activateFreeze(actors.creator,{plan_id:state.plan.plan_id,plan_digest:state.plan.plan_digest,baseline_ref:'baseline-alpha'});return {...state,freeze};}
function approved(s=service()){const state=frozen(s);state.s.recordDecision(actors.owner,{plan_id:state.plan.plan_id,plan_digest:state.plan.plan_digest,area:'business',decision:'go'});for(const area of ['technical','operations','privacy'])state.s.recordDecision(actors.reviewer,{plan_id:state.plan.plan_id,plan_digest:state.plan.plan_digest,area,decision:'go'});return state;}
function running(s=service()){const state=approved(s),run=state.s.startRun(actors.creator,{plan_id:state.plan.plan_id,plan_digest:state.plan.plan_digest});return {...state,run};}
function hypercare(s=service()){const state=running(s);for(const [stage,sample] of [[5,50],[25,150],[50,300],[100,600]])state.s.observeCanary(actors.creator,{run_id:state.run.run_id,stage_percent:stage,release_ref:'release-candidate',sample_size:sample,availability_percent:99.8,latency_p95_ms:250,error_count:0});return state;}
test('real execution is disabled by default',()=>{const s=service();assert.throws(()=>s.createPlan(actors.creator,{...base,synthetic:false}),e=>e.code==='REAL_EXECUTION_DISABLED');});
test('launch window must end after it begins',()=>{const s=service();assert.throws(()=>s.createPlan(actors.creator,{...base,window:{...base.window,end_at:base.window.start_at}}),e=>e.code==='WINDOW_INVALID');});
test('creates a four-stage synthetic plan with stable digest',()=>{const {plan}=planned();assert.deepEqual(plan.canary_stages,[5,25,50,100]);assert.match(plan.plan_digest,/^[a-f0-9]{64}$/);assert.equal(plan.status,'draft');});
test('hostname is normalized before validation',()=>{const s=service(),plan=s.createPlan(actors.creator,{...base,hostname:'Alpha.Guialima.Online.'});assert.equal(plan.hostname,'alpha.guialima.online');});
test('tenant isolation blocks cross-tenant reads and updates',()=>{const {s,plan}=planned();assert.throws(()=>s.read(actors.other,'tenant-alpha'),e=>e.code==='ACCESS_DENIED');assert.throws(()=>s.updatePlan(actors.other,plan.plan_id,plan.revision,{incident_owner:'operator-next'}),e=>e.code==='ACCESS_DENIED');});
test('plan update increments revision and changes digest',()=>{const {s,plan}=planned(),next=s.updatePlan(actors.creator,plan.plan_id,plan.revision,{incident_owner:'operator-next'});assert.equal(next.revision,2);assert.notEqual(next.plan_digest,plan.plan_digest);});
test('optimistic concurrency rejects a stale revision',()=>{const {s,plan}=planned();s.updatePlan(actors.creator,plan.plan_id,plan.revision,{incident_owner:'operator-next'});assert.throws(()=>s.updatePlan(actors.creator,plan.plan_id,plan.revision,{rollback_target_ref:'release-other'}),e=>e.code==='REVISION_CONFLICT');});
test('accepted package reference cannot be replaced by update',()=>{const {s,plan}=planned();assert.throws(()=>s.updatePlan(actors.creator,plan.plan_id,plan.revision,{pilot_package_ref:`pilotp-${'c'.repeat(24)}`}),e=>e.code==='PLAN_FIELD_IMMUTABLE');});
test('freeze rejects a stale plan digest',()=>{const {s,plan}=planned();assert.throws(()=>s.activateFreeze(actors.creator,{plan_id:plan.plan_id,plan_digest:'0'.repeat(64),baseline_ref:'baseline'}),e=>e.code==='PLAN_STALE');});
test('freeze records baseline and two permitted exceptions',()=>{const {freeze}=frozen();assert.equal(freeze.status,'active');assert.deepEqual(freeze.allowed_changes,['incident_mitigation','rollback']);});
test('active freeze blocks ordinary plan changes',()=>{const {s,plan}=frozen();assert.throws(()=>s.updatePlan(actors.creator,plan.plan_id,plan.revision,{incident_owner:'operator-next'}),e=>e.code==='CHANGE_FREEZE_ACTIVE');});
test('business GO requires the tenant owner',()=>{const {s,plan}=frozen();assert.throws(()=>s.recordDecision(actors.reviewer,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'business',decision:'go'}),e=>e.code==='ACCESS_DENIED');assert.throws(()=>s.recordDecision(actors.otherOwner,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'business',decision:'go'}),e=>e.code==='ACCESS_DENIED');});
test('plan creator cannot approve technical controls',()=>{const {s,plan}=frozen();assert.throws(()=>s.recordDecision(actors.creator,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'technical',decision:'go'}),e=>e.code==='INDEPENDENT_DECISION_REQUIRED');});
test('GO cannot override a failed check',()=>{const {s,plan}=frozen();assert.throws(()=>s.recordDecision(actors.reviewer,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'technical',decision:'go',failed_checks:['rollback-target']}),e=>e.code==='GO_BLOCKED');});
test('NO-GO records reasons and blocks the plan',()=>{const {s,plan}=frozen(),decision=s.recordDecision(actors.reviewer,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'technical',decision:'no_go',failed_checks:['rollback-target'],reason_codes:['rollback-missing']});assert.equal(decision.decision,'no_go');assert.equal(s.read(actors.creator,'tenant-alpha').plans[0].status,'blocked');});
test('area decision is immutable for the frozen digest',()=>{const {s,plan}=frozen();s.recordDecision(actors.owner,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'business',decision:'go'});assert.throws(()=>s.recordDecision(actors.owner,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'business',decision:'go'}),e=>e.code==='DECISION_EXISTS');});
test('run requires all four GO decisions',()=>{const {s,plan}=frozen();s.recordDecision(actors.owner,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,area:'business',decision:'go'});assert.throws(()=>s.startRun(actors.creator,{plan_id:plan.plan_id,plan_digest:plan.plan_digest}),e=>e.code==='GO_LIVE_NOT_APPROVED');});
test('four GO decisions approve the frozen plan',()=>{const {s,plan}=approved(),state=s.read(actors.creator,'tenant-alpha');assert.equal(state.decisions.length,4);assert.equal(state.plans[0].status,'approved');});
test('apply execution remains blocked',()=>{const {s,plan}=approved();assert.throws(()=>s.startRun(actors.creator,{plan_id:plan.plan_id,plan_digest:plan.plan_digest,execution_mode:'apply'}),e=>e.code==='EXECUTION_MODE_BLOCKED');});
test('run begins with zero side effects',()=>{const {run}=running();assert.equal(run.execution_mode,'dry_run');assert.equal(run.external_changes,0);assert.equal(run.external_messages,0);assert.equal(run.publication_performed,false);});
test('canary stages must be observed in sequence',()=>{const {s,run}=running();assert.throws(()=>s.observeCanary(actors.creator,{run_id:run.run_id,stage_percent:25,release_ref:'release-candidate',sample_size:100,availability_percent:100,latency_p95_ms:200,error_count:0}),e=>e.code==='CANARY_SEQUENCE_INVALID');});
test('passing four canary stages enters hypercare',()=>{const {s,run}=hypercare(),state=s.read(actors.creator,'tenant-alpha');assert.equal(state.observations.length,4);assert.equal(state.runs.find(item=>item.run_id===run.run_id).status,'hypercare');});
test('SLO breach triggers simulated rollback at exact stage',()=>{const {s,run}=running();s.observeCanary(actors.creator,{run_id:run.run_id,stage_percent:5,release_ref:'release-candidate',sample_size:50,availability_percent:100,latency_p95_ms:200,error_count:0});const result=s.observeCanary(actors.creator,{run_id:run.run_id,stage_percent:25,release_ref:'release-candidate',sample_size:100,availability_percent:98,latency_p95_ms:800,error_count:3});assert.equal(result.run.status,'rolled_back');assert.equal(result.rollback.stage_percent,25);assert.equal(result.rollback.external_changes,0);assert.ok(result.rollback.reason_codes.includes('latency-breach'));});
test('canary observation carries the SLO policy references',()=>{const {s,run}=running(),result=s.observeCanary(actors.creator,{run_id:run.run_id,stage_percent:5,release_ref:'release-candidate',sample_size:50,availability_percent:100,latency_p95_ms:200,error_count:0});assert.deepEqual(result.observation.slo_policy_refs,['slo-router']);});
test('manual rollback is explicit and side-effect free',()=>{const {s,run}=running(),result=s.manualRollback(actors.creator,{run_id:run.run_id,reason_code:'operator-stop'});assert.equal(result.trigger.source,'manual');assert.equal(result.trigger.external_changes,0);assert.equal(result.run.status,'rolled_back');});
test('hypercare checkpoints must be sequential',()=>{const {s,run}=hypercare();assert.throws(()=>s.recordHypercare(actors.creator,{run_id:run.run_id,window:'24h',availability_percent:100,latency_p95_ms:200,open_incidents:0}),e=>e.code==='HYPERCARE_SEQUENCE_INVALID');});
test('hypercare degradation triggers rollback',()=>{const {s,run}=hypercare(),result=s.recordHypercare(actors.creator,{run_id:run.run_id,window:'launch',availability_percent:99.8,latency_p95_ms:250,open_incidents:1});assert.equal(result.check.status,'failed');assert.equal(result.rollback.source,'hypercare');assert.ok(result.rollback.reason_codes.includes('open-incident'));});
test('three healthy checkpoints close run and release freeze',()=>{const {s,run}=hypercare();for(const window of ['launch','24h','72h'])s.recordHypercare(actors.creator,{run_id:run.run_id,window,availability_percent:99.9,latency_p95_ms:220,open_incidents:0});const state=s.read(actors.creator,'tenant-alpha');assert.equal(state.runs.find(item=>item.run_id===run.run_id).status,'closed');assert.equal(state.plans[0].status,'closed');assert.equal(state.freezes[0].status,'released');});
test('owner can read but cannot operate the run',()=>{const {s,run}=running();assert.equal(s.read(actors.owner,'tenant-alpha').runs.length,1);assert.throws(()=>s.observeCanary(actors.owner,{run_id:run.run_id,stage_percent:5,release_ref:'release',sample_size:10,availability_percent:100,latency_p95_ms:100,error_count:0}),e=>e.code==='ACCESS_DENIED');});
test('audit chain verifies per tenant',()=>{const {s,run}=running();s.manualRollback(actors.creator,{run_id:run.run_id,reason_code:'operator-stop'});assert.equal(s.verifyAudit('tenant-alpha'),true);assert.ok(s.read(actors.owner,'tenant-alpha').events.length>=8);});
test('go-live console is read-only, noindex and isolated',async()=>{const app=server();await new Promise((resolve,reject)=>{app.once('error',reject);app.listen(0,'127.0.0.1',resolve);});try{const origin=`http://127.0.0.1:${app.address().port}`,page=await fetch(origin);assert.equal(page.status,200);assert.match(page.headers.get('x-robots-tag'),/noindex/);assert.match(page.headers.get('content-security-policy'),/connect-src 'none'/);assert.equal((await fetch(origin,{method:'POST'})).status,405);assert.equal((await fetch(origin+'/../package.json')).status,404);}finally{await new Promise(resolve=>app.close(resolve));}});
