'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createPilotAcceptanceService}=require('../packages/pilot-acceptance/index.cjs');
const {server}=require('../scripts/serve-pilot-acceptance.cjs');
const actors={creator:{actor_id:'operator-creator',role:'operator',tenant_id:'tenant-alpha'},reviewer:{actor_id:'operator-reviewer',role:'operator',tenant_id:'tenant-alpha'},owner:{actor_id:'owner-alpha',role:'owner',tenant_id:'tenant-alpha'},admin:{actor_id:'admin-root',role:'admin',tenant_id:null},other:{actor_id:'operator-other',role:'operator',tenant_id:'tenant-beta'},otherOwner:{actor_id:'owner-other',role:'owner',tenant_id:'tenant-beta'}};
const refs={owner_submission:'onb-alpha-synthetic',business_truth:'truth-alpha-synthetic',brand_profile:'brand-alpha-synthetic',site_config:'config-alpha-synthetic',site_snapshot:'snapshot-alpha-synthetic',asset_registry:'assets-alpha-synthetic',privacy_notice:'privacy-alpha-synthetic'};
const acknowledgements={reviewed:true,authority_confirmed:true,facts_confirmed:true,asset_rights_confirmed:true,contact_publication_approved:true,domain_use_approved:true,privacy_notice_reviewed:true};
const service=()=>createPilotAcceptanceService({now:()=>new Date('2026-09-30T20:00:00Z')});
function created(s=service()){return {s,d:s.createDossier(actors.creator,{tenant_id:'tenant-alpha',business_id:'business-alpha',site_id:'site-alpha',synthetic:true,source_refs:refs})};}
function submitted(s=service()){let d=s.createDossier(actors.creator,{tenant_id:'tenant-alpha',business_id:'business-alpha',site_id:'site-alpha',synthetic:true,source_refs:refs});for(const requirement of d.requirements)d=s.updateRequirement(actors.creator,d.dossier_id,d.revision,requirement.key,{status:'ready',evidence_refs:[`evidence-${requirement.key}`]});d=s.submitDossier(actors.creator,d.dossier_id);return {s,d};}
function reviewed(s=service()){const state=submitted(s);for(const area of ['content','visual','privacy','technical'])state.s.recordReview(actors.reviewer,{dossier_id:state.d.dossier_id,dossier_hash:state.d.snapshot_hash,area,decision:'approved'});return state;}
function accepted(s=service()){const state=reviewed(s);const acceptance=state.s.ownerAccept(actors.owner,{dossier_id:state.d.dossier_id,dossier_hash:state.d.snapshot_hash,acknowledgements});return {...state,acceptance};}
function ready(s=service()){const state=accepted(s),evaluation=state.s.evaluateReadiness(actors.creator,state.d.dossier_id);return {...state,evaluation};}
test('real business data is disabled by default',()=>{const s=service();assert.throws(()=>s.createDossier(actors.creator,{tenant_id:'tenant-alpha',business_id:'business-alpha',site_id:'site-alpha',synthetic:false,source_refs:refs}),e=>e.code==='REAL_DATA_DISABLED');});
test('creates a synthetic dossier with nine closed requirements',()=>{const {d}=created();assert.equal(d.requirements.length,9);assert.equal(new Set(d.requirements.map(item=>item.key)).size,9);assert.match(d.snapshot_hash,/^[a-f0-9]{64}$/);});
test('tenant isolation blocks reads and mutations',()=>{const {s,d}=created();assert.throws(()=>s.read(actors.other,'tenant-alpha'),e=>e.code==='ACCESS_DENIED');assert.throws(()=>s.updateRequirement(actors.other,d.dossier_id,d.revision,'identity',{status:'ready',evidence_refs:['evidence']}),e=>e.code==='ACCESS_DENIED');});
test('optimistic revision rejects stale updates',()=>{const {s,d}=created(),next=s.updateRequirement(actors.creator,d.dossier_id,d.revision,'identity',{status:'ready',evidence_refs:['evidence-identity']});assert.equal(next.revision,2);assert.throws(()=>s.updateRequirement(actors.creator,d.dossier_id,d.revision,'brand',{status:'ready',evidence_refs:['evidence-brand']}),e=>e.code==='REVISION_CONFLICT');});
test('unknown requirements are denied',()=>{const {s,d}=created();assert.throws(()=>s.updateRequirement(actors.creator,d.dossier_id,d.revision,'billing',{status:'ready',evidence_refs:['evidence']}),e=>e.code==='REQUIREMENT_UNKNOWN');});
test('ready evidence cannot be empty and failed updates are atomic',()=>{const {s,d}=created();assert.throws(()=>s.updateRequirement(actors.creator,d.dossier_id,d.revision,'identity',{status:'ready',evidence_refs:[]}),e=>e.code==='SCHEMA_INVALID');const current=s.read(actors.creator,'tenant-alpha').dossiers[0];assert.equal(current.revision,1);assert.equal(current.requirements[0].status,'pending');});
test('blocked requirement records a blocker and prevents submission',()=>{const {s,d}=created(),next=s.updateRequirement(actors.creator,d.dossier_id,d.revision,'assets',{status:'blocked',blocker_code:'asset-rights-missing',evidence_refs:[]});assert.equal(next.status,'changes_requested');assert.equal(next.requirements.find(item=>item.key==='assets').blocker_code,'asset-rights-missing');assert.throws(()=>s.submitDossier(actors.creator,d.dossier_id),e=>e.code==='DOSSIER_INCOMPLETE');});
test('incomplete dossier cannot enter review',()=>{const {s,d}=created();assert.throws(()=>s.submitDossier(actors.creator,d.dossier_id),e=>e.code==='DOSSIER_INCOMPLETE'&&e.details.length===9);});
test('complete dossier enters review with an immutable snapshot',()=>{const {d}=submitted();assert.equal(d.status,'in_review');assert.equal(d.revision,10);assert.ok(d.requirements.every(item=>item.status==='ready'));});
test('dossier creator cannot approve their own work',()=>{const {s,d}=submitted();assert.throws(()=>s.recordReview(actors.creator,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'content',decision:'approved'}),e=>e.code==='INDEPENDENT_REVIEW_REQUIRED');});
test('review cannot bind to a stale dossier hash',()=>{const {s,d}=submitted(),changed=s.updateRequirement(actors.creator,d.dossier_id,d.revision,'copy',{status:'ready',evidence_refs:['new-copy-evidence']});assert.notEqual(changed.snapshot_hash,d.snapshot_hash);assert.throws(()=>s.recordReview(actors.reviewer,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'content',decision:'approved'}),e=>e.code==='DOSSIER_STALE');});
test('approval is blocked when an area check fails',()=>{const {s,d}=submitted();assert.throws(()=>s.recordReview(actors.reviewer,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'visual',decision:'approved',failed_checks:['design']}),e=>e.code==='REVIEW_BLOCKED');});
test('review decisions are immutable per area and snapshot',()=>{const {s,d}=submitted(),first=s.recordReview(actors.reviewer,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'content',decision:'approved'});assert.equal(first.decision,'approved');assert.throws(()=>s.recordReview(actors.admin,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'content',decision:'approved'}),e=>e.code==='REVIEW_ALREADY_RECORDED');});
test('changes request prevents further acceptance workflow',()=>{const {s,d}=submitted(),decision=s.recordReview(actors.reviewer,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'content',decision:'changes_requested',failed_checks:['copy'],reason_codes:['copy-needs-review']});assert.equal(decision.decision,'changes_requested');assert.throws(()=>s.recordReview(actors.reviewer,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'visual',decision:'approved'}),e=>e.code==='DOSSIER_NOT_IN_REVIEW');});
test('owner acceptance requires all four approved reviews',()=>{const {s,d}=submitted();s.recordReview(actors.reviewer,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,area:'content',decision:'approved'});assert.throws(()=>s.ownerAccept(actors.owner,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,acknowledgements}),e=>e.code==='REVIEWS_INCOMPLETE');});
test('owner from another tenant cannot accept',()=>{const {s,d}=reviewed();assert.throws(()=>s.ownerAccept(actors.otherOwner,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,acknowledgements}),e=>e.code==='ACCESS_DENIED');});
test('accepted owner record requires seven explicit acknowledgements',()=>{const {s,d}=reviewed();assert.throws(()=>s.ownerAccept(actors.owner,{dossier_id:d.dossier_id,dossier_hash:d.snapshot_hash,acknowledgements:{...acknowledgements,asset_rights_confirmed:false}}),e=>e.code==='SCHEMA_INVALID');});
test('owner acceptance binds to the exact reviewed snapshot',()=>{const {s,d,acceptance}=accepted();assert.equal(acceptance.decision,'accepted');assert.equal(acceptance.dossier_hash,d.snapshot_hash);assert.equal(acceptance.scope.length,7);});
test('readiness explains blockers instead of claiming success',()=>{const {s,d}=created(),evaluation=s.evaluateReadiness(actors.creator,d.dossier_id);assert.equal(evaluation.status,'blocked');assert.ok(evaluation.blockers.includes('owner-acceptance'));assert.ok(evaluation.blockers.includes('review-technical'));});
test('complete reviews and acceptance produce readiness',()=>{const {evaluation}=ready();assert.equal(evaluation.status,'ready_for_rehearsal');assert.equal(evaluation.blockers.length,0);assert.equal(evaluation.review_refs.length,4);});
test('rehearsal requires a current ready evaluation',()=>{const {s,d}=created();assert.throws(()=>s.rehearseLaunch(actors.creator,{dossier_id:d.dossier_id,readiness_ref:'pilote-'+'a'.repeat(24)}),e=>e.code==='READINESS_REQUIRED');});
test('local rehearsal passes with zero side effects',()=>{const {s,d,evaluation}=ready(),rehearsal=s.rehearseLaunch(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id});assert.equal(rehearsal.status,'passed');assert.equal(rehearsal.external_changes,0);assert.equal(rehearsal.external_messages,0);assert.equal(rehearsal.publication_performed,false);});
test('failed rehearsal cannot seal a package',()=>{const {s,d,evaluation}=ready(),rehearsal=s.rehearseLaunch(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id,fail_step:'domain-plan'});assert.equal(rehearsal.status,'failed');assert.throws(()=>s.sealPackage(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id,rehearsal_ref:rehearsal.rehearsal_id}),e=>e.code==='REHEARSAL_REQUIRED');});
test('sealed package remains review-only and immutable',()=>{const {s,d,evaluation}=ready(),rehearsal=s.rehearseLaunch(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id}),record=s.sealPackage(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id,rehearsal_ref:rehearsal.rehearsal_id});assert.equal(record.status,'sealed_local');assert.equal(record.may_publish,false);assert.match(record.content_digest,/^[a-f0-9]{64}$/);assert.throws(()=>s.updateRequirement(actors.creator,d.dossier_id,d.revision,'copy',{status:'ready',evidence_refs:['changed']}),e=>e.code==='DOSSIER_SEALED');});
test('package revocation is idempotent',()=>{const {s,d,evaluation}=ready(),rehearsal=s.rehearseLaunch(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id}),record=s.sealPackage(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id,rehearsal_ref:rehearsal.rehearsal_id});assert.equal(s.revokePackage(actors.admin,record.package_id).status,'revoked');assert.equal(s.revokePackage(actors.admin,record.package_id).status,'revoked');});
test('audit events form a verifiable chain',()=>{const {s,d,evaluation}=ready();s.rehearseLaunch(actors.creator,{dossier_id:d.dossier_id,readiness_ref:evaluation.evaluation_id});assert.equal(s.verifyAudit(),true);assert.ok(s.read(actors.owner,'tenant-alpha').events.length>=17);});
test('pilot acceptance console is read-only, noindex and isolated',async()=>{const app=server();await new Promise((resolve,reject)=>{app.once('error',reject);app.listen(0,'127.0.0.1',resolve);});try{const origin=`http://127.0.0.1:${app.address().port}`,page=await fetch(origin);assert.equal(page.status,200);assert.match(page.headers.get('x-robots-tag'),/noindex/);assert.match(page.headers.get('content-security-policy'),/connect-src 'none'/);assert.equal((await fetch(origin,{method:'POST'})).status,405);assert.equal((await fetch(origin+'/../package.json')).status,404);}finally{await new Promise(resolve=>app.close(resolve));}});
