'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {createEvidenceEngine,sha,allowedFields}=require('../packages/private-evidence-engine/index.cjs'),{server}=require('../scripts/serve-private-evidence-engine.cjs'),root=path.resolve(__dirname,'..'),actors={manager:{actor_id:'manager',roles:['evidence_manager']},intake:{actor_id:'intake',roles:['evidence_intake']},classifier:{actor_id:'classifier',roles:['privacy_classifier']},privacy:{actor_id:'privacy',roles:['privacy_reviewer']},privacy2:{actor_id:'privacy2',roles:['privacy_reviewer']},encryption:{actor_id:'encryption',roles:['encryption_operator']},business:{actor_id:'business',roles:['business_reviewer']},retention:{actor_id:'retention',roles:['retention_manager']},replacement:{actor_id:'replacement',roles:['replacement_operator']},auditor:{actor_id:'auditor',roles:['evidence_auditor']},viewer:{actor_id:'viewer',roles:['viewer']}},payload={business_name:'Synthetic Studio',services:['Buy','Sell'],service_areas:['Lima'],ideal_customer:'Families',differentiators:['Clarity'],asset_rights:'synthetic_fixture',owner_acceptance:'simulation_accepted',phone:'999',email:'x@example.test',exact_address:'secret',id_number:'secret'};function prepared({dual=true,expiry=true}={}){const engine=createEvidenceEngine({now:()=>new Date('2026-10-02T18:00:00.000Z')}),c=engine.openCase(actors.manager,'biz_5'),e=engine.ingest(actors.intake,c.case_id,{kind:'owner_form',source_type:'synthetic_fixture',payload}),classification=engine.classify(actors.classifier,e.evidence_id,{sensitivity:'restricted',data_categories:['identity','business_truth','contact','asset_rights','acceptance'],retention_days:30}),redaction=engine.redact(actors.privacy,e.evidence_id),encryption=engine.encrypt(actors.encryption,e.evidence_id,redaction.redaction_id),r1=engine.review(actors.privacy,encryption.encryption_id),r2=dual?engine.review(actors.business,encryption.encryption_id):null,ex=expiry?engine.setExpiry(actors.retention,e.evidence_id,30):null,map=engine.createMap(actors.replacement,c.case_id);return {engine,c,e,classification,redaction,encryption,r1,r2,ex,map}}function complete(){const x=prepared(),replacements=allowedFields.map(field=>x.engine.replace(actors.replacement,x.c.case_id,x.map.map_id,x.e.evidence_id,field,'old:'+field)),batch=x.engine.sealBatch(actors.replacement,x.c.case_id,replacements.map(r=>r.replacement_id)),pkg=x.engine.sealPackage(actors.auditor,x.c.case_id,batch.batch_id),gate=x.engine.gate(actors.auditor,x.c.case_id,pkg);return {...x,replacements,batch,pkg,gate}}
const checks=[
['case is private',()=>assert.equal(prepared().c.access,'private')],
['case defaults synthetic',()=>assert.equal(prepared().c.mode,'synthetic_rehearsal')],
['only pilot candidate accepted',()=>assert.throws(()=>createEvidenceEngine().openCase(actors.manager,'biz_2'),{code:'SINGLE_PILOT_SCOPE'})],
['manager role required',()=>assert.throws(()=>createEvidenceEngine().openCase(actors.viewer,'biz_5'),{code:'ROLE_REQUIRED'})],
['ingestion marks fixture synthetic',()=>assert.equal(prepared().e.synthetic,true)],
['ingestion stores payload digest',()=>assert.match(prepared().e.payload_digest,/^[a-f0-9]{64}$/)],
['ingestion never persists raw payload',()=>assert.equal(prepared().e.raw_persisted,false)],
['synthetic case rejects owner source',()=>{const x=createEvidenceEngine(),c=x.openCase(actors.manager,'biz_5');assert.throws(()=>x.ingest(actors.intake,c.case_id,{kind:'owner_form',source_type:'verified_owner',payload}),{code:'SOURCE_MODE_MISMATCH'})}],
['classification is restricted',()=>assert.equal(prepared().classification.sensitivity,'restricted')],
['classification has five categories',()=>assert.equal(prepared().classification.data_categories.length,5)],
['classification retains 30 days',()=>assert.equal(prepared().classification.retention_days,30)],
['redaction removes phone',()=>assert(prepared().redaction.removed_fields.includes('phone'))],
['redaction removes email',()=>assert(prepared().redaction.removed_fields.includes('email'))],
['redaction removes exact address',()=>assert(prepared().redaction.removed_fields.includes('exact_address'))],
['redaction removes id number',()=>assert(prepared().redaction.removed_fields.includes('id_number'))],
['redaction retains seven fields',()=>assert.equal(prepared().redaction.retained_fields.length,7)],
['redaction requires classification',()=>{const x=createEvidenceEngine(),c=x.openCase(actors.manager,'biz_5'),e=x.ingest(actors.intake,c.case_id,{kind:'owner_form',source_type:'synthetic_fixture',payload});assert.throws(()=>x.redact(actors.privacy,e.evidence_id),{code:'CLASSIFICATION_REQUIRED'})}],
['encryption uses AES 256 GCM',()=>assert.equal(prepared().encryption.algorithm,'aes-256-gcm')],
['encryption has IV',()=>assert(prepared().encryption.iv.length>=16)],
['encryption has auth tag',()=>assert(prepared().encryption.auth_tag.length>=16)],
['ciphertext differs from plaintext',()=>assert(!prepared().encryption.ciphertext.includes('Synthetic Studio'))],
['ciphertext has digest',()=>assert.match(prepared().encryption.ciphertext_digest,/^[a-f0-9]{64}$/)],
['encryption key is not persisted',()=>assert.equal(prepared().encryption.key_persisted,false)],
['privacy review approves',()=>assert.equal(prepared().r1.decision,'approved')],
['business review approves',()=>assert.equal(prepared().r2.role,'business_reviewer')],
['reviewer cannot review twice',()=>{const x=prepared({dual:false});assert.throws(()=>x.engine.review(actors.privacy,x.encryption.encryption_id),{code:'INDEPENDENT_REVIEW_REQUIRED'})}],
['same review role cannot satisfy dual review',()=>{const x=prepared({dual:false});assert.throws(()=>x.engine.review(actors.privacy2,x.encryption.encryption_id),{code:'DISTINCT_REVIEW_ROLES_REQUIRED'})}],
['each review has four checks',()=>assert.equal(prepared().r1.checks.length,4)],
['expiry is active',()=>assert.equal(prepared().ex.status,'active')],
['expiry destroys after 30 days',()=>{const x=prepared();assert.equal(new Date(x.ex.expires_at)-new Date('2026-10-02T18:00:00.000Z'),30*864e5)}],
['field map contains seven fields',()=>assert.equal(prepared().map.fields.length,7)],
['field map is synthetic',()=>assert.equal(prepared().map.synthetic,true)],
['replacement requires dual review',()=>{const x=prepared({dual:false});assert.throws(()=>x.engine.replace(actors.replacement,x.c.case_id,x.map.map_id,x.e.evidence_id,'business_name','old'),{code:'DUAL_REVIEW_REQUIRED'})}],
['replacement requires active expiry',()=>{const x=prepared({expiry:false});assert.throws(()=>x.engine.replace(actors.replacement,x.c.case_id,x.map.map_id,x.e.evidence_id,'business_name','old'),{code:'ACTIVE_EXPIRY_REQUIRED'})}],
['replacement rejects unmapped field',()=>{const x=prepared();assert.throws(()=>x.engine.replace(actors.replacement,x.c.case_id,x.map.map_id,x.e.evidence_id,'phone','old'),{code:'REPLACEMENT_SCOPE_INVALID'})}],
['simulation replacement is explicit',()=>assert.equal(complete().replacements[0].status,'simulated_replacement')],
['replacement stores only old digest',()=>assert.match(complete().replacements[0].old_value_digest,/^[a-f0-9]{64}$/)],
['replacement binds two reviews',()=>assert.equal(complete().replacements[0].review_refs.length,2)],
['complete flow replaces seven fields',()=>assert.equal(complete().replacements.length,7)],
['batch counts seven fields',()=>assert.equal(complete().batch.field_count,7)],
['batch is sealed',()=>assert.equal(complete().batch.status,'sealed')],
['batch digest is sha256',()=>assert.match(complete().batch.batch_digest,/^[a-f0-9]{64}$/)],
['package stays private',()=>assert.equal(complete().pkg.access,'private')],
['package publication is false',()=>assert.equal(complete().pkg.publication_allowed,false)],
['package is synthetic',()=>assert.equal(complete().pkg.synthetic,true)],
['package binds chain head',()=>assert.match(complete().pkg.chain_head,/^[a-f0-9]{64}$/)],
['chain verifies',()=>{const x=complete();assert.equal(x.engine.verifyChain(actors.auditor,x.c.case_id),true)}],
['chain sequence is contiguous',()=>{const x=complete(),chain=x.engine.getChain(x.c.case_id);assert.deepEqual(chain.map(e=>e.sequence),chain.map((_e,i)=>i+1))}],
['chain starts with null previous hash',()=>assert.equal(complete().engine.getChain(complete().c?.case_id||'x')[0]?.previous_hash??null,null)],
['gate simulation completes',()=>assert.equal(complete().gate.simulation_status,'complete')],
['gate real evidence stays pending',()=>assert.equal(complete().gate.real_evidence_status,'pending')],
['gate publication stays blocked',()=>assert.equal(complete().gate.publication_status,'blocked')],
['gate never allows public publish',()=>assert.equal(complete().gate.public_publish_allowed,false)],
['gate has real evidence blocker',()=>assert.deepEqual(complete().gate.blockers,['real_evidence'])],
['summary persists no keys',()=>assert.equal(complete().engine.summary().persisted_keys,0)],
['summary persists no raw payloads',()=>assert.equal(complete().engine.summary().raw_payloads,0)],
['summary has zero publications',()=>assert.equal(complete().engine.summary().publications,0)],
['canonical hash deterministic',()=>assert.equal(sha({b:2,a:1}),sha({a:1,b:2}))],
['build output is synthetic only',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(root,'dist','private-evidence-engine','data','evidence-engine.json'))).safety.synthetic_only,true)],
['build output has seven replacements',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(root,'dist','private-evidence-engine','data','evidence-engine.json'))).replacements.length,7)],
['build output has zero real replacements',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(root,'dist','private-evidence-engine','data','evidence-engine.json'))).safety.real_fields_replaced,0)]
];for(const [n,f] of checks)test(n,f);function request(s,url,method='GET'){return new Promise((ok,no)=>{const a=s.address(),q=http.request({hostname:'127.0.0.1',port:a.port,path:url,method},r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>ok({status:r.statusCode,headers:r.headers,body:b}))});q.on('error',no);q.end()})}async function started(){const s=server();await new Promise((ok,no)=>{s.once('error',no);s.listen(0,'127.0.0.1',ok)});return s}test('evidence UI is protected and noindex',async()=>{const s=await started();try{const r=await request(s,'/');assert.equal(r.status,200);assert.match(r.body,/Motor privado de evidencia/);assert.equal(r.headers['x-robots-tag'],'noindex, nofollow')}finally{await new Promise(ok=>s.close(ok))}});test('evidence server rejects writes and traversal',async()=>{const s=await started();try{assert.equal((await request(s,'/','POST')).status,405);assert.equal((await request(s,'/%2e%2e/package.json')).status,404)}finally{await new Promise(ok=>s.close(ok))}});