'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const {createFoundation,releaseAsset,keyFromBase64}=require('../packages/private-foundation/index.cjs');const {server}=require('../scripts/serve-private-foundation.cjs');
const ROOT=path.resolve(__dirname,'..'),asset=JSON.parse(fs.readFileSync(path.join(ROOT,'foundation/synthetic-asset.json'),'utf8')),clone=v=>structuredClone(v),ctx={owner:{actor_id:'owner-demo',role:'owner',tenant_id:'horizonte-casa-demo'},other:{actor_id:'owner-other',role:'owner',tenant_id:'otro-negocio-demo'},operator:{actor_id:'operator-demo',role:'operator',tenant_id:null},admin:{actor_id:'admin-demo',role:'admin',tenant_id:null}};
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'tl-vault-')),key=crypto.randomBytes(32),audit=crypto.randomBytes(32),vault=createFoundation(root,key,audit);t.after(()=>{const resolved=path.resolve(root);assert(resolved.startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(resolved,{recursive:true,force:true});});return {root,key,audit,vault};}
const record=(id='owner-submission-demo',expires_at='2026-12-31T00:00:00Z')=>({record_id:id,tenant_id:'horizonte-casa-demo',record_type:'owner_submission',payload:{display_name:'Horizonte Casa — FICTICIO',private_contact:'secreto@example.invalid'},retention_class:'active_pilot',expires_at});
test('encrypts private JSON with authenticated ciphertext and restores it',t=>{const {vault}=setup(t),envelope=vault.putJson(ctx.owner,record(),'2026-09-30T17:00:00Z'),raw=fs.readFileSync(path.join(vault.paths.vault,'owner-submission-demo.enc.json'),'utf8');assert.equal(raw.includes('secreto@example.invalid'),false);assert.equal(envelope.algorithm,'aes-256-gcm');assert.equal(vault.getJson(ctx.owner,'owner-submission-demo').payload.private_contact,'secreto@example.invalid');assert.equal(vault.verifyAudit().valid,true);});
test('wrong tenant is denied and the denial enters the audit chain',t=>{const {vault}=setup(t);vault.putJson(ctx.owner,record());assert.throws(()=>vault.getJson(ctx.other,'owner-submission-demo'),e=>e.code==='ACCESS_DENIED');const state=vault.verifyAudit();assert.equal(state.valid,true);assert.equal(state.entries,2);const log=fs.readFileSync(vault.paths.auditFile,'utf8');assert.match(log,/access.denied/);});
test('ciphertext tampering fails authenticated decryption',t=>{const {vault}=setup(t);vault.putJson(ctx.owner,record());const file=path.join(vault.paths.vault,'owner-submission-demo.enc.json'),envelope=JSON.parse(fs.readFileSync(file,'utf8'));envelope.ciphertext=envelope.ciphertext.slice(0,-2)+'aa';fs.writeFileSync(file,JSON.stringify(envelope));assert.throws(()=>vault.getJson(ctx.owner,'owner-submission-demo'),e=>e.code==='DECRYPT_FAILED');});
test('deletion requires admin and leaves a non-sensitive tombstone',t=>{const {vault}=setup(t);vault.putJson(ctx.owner,record());assert.throws(()=>vault.remove(ctx.owner,'owner-submission-demo','Solicitud válida'),e=>e.code==='ACCESS_DENIED');const tombstone=vault.remove(ctx.admin,'owner-submission-demo','Solicitud verificada del propietario','2026-10-01T00:00:00Z');assert.equal(fs.existsSync(path.join(vault.paths.vault,'owner-submission-demo.enc.json')),false);assert.equal(JSON.stringify(tombstone).includes('secreto@example.invalid'),false);assert.equal(vault.verifyAudit().valid,true);});
test('retention lists expired records and excludes legal hold',t=>{const {vault}=setup(t);vault.putJson(ctx.owner,record('record-expired','2026-09-01T00:00:00Z'));vault.putJson(ctx.owner,{...record('record-held',null),retention_class:'legal_hold'});const due=vault.retention(ctx.admin,'2026-10-01T00:00:00Z');assert.deepEqual(due.map(x=>x.record_id),['record-expired']);});
test('audit verification detects line modification',t=>{const {vault}=setup(t);vault.putJson(ctx.owner,record());assert.equal(vault.verifyAudit().valid,true);const rows=fs.readFileSync(vault.paths.auditFile,'utf8').trim().split('\n'),changed=JSON.parse(rows[0]);changed.result='failed';fs.writeFileSync(vault.paths.auditFile,JSON.stringify(changed)+'\n');assert.equal(vault.verifyAudit().valid,false);});
test('asset release requires clean scan, rights and no active content',()=>{assert.throws(()=>releaseAsset(asset),e=>e.code==='ASSET_BLOCKED');const clean=clone(asset);clean.rights={status:'approved',permission_note:'Permiso sintético confirmado.'};clean.security.scan_status='clean';const released=releaseAsset(clean);assert.equal(released.security.quarantine_status,'released');const active=clone(clean);active.security.active_content_detected=true;assert.throws(()=>releaseAsset(active),e=>e.code==='ASSET_BLOCKED');});
test('key parser rejects missing, short and malformed material',()=>{assert.throws(()=>keyFromBase64(''),e=>e.code==='KEY_INVALID');assert.throws(()=>keyFromBase64(Buffer.alloc(16).toString('base64')),e=>e.code==='KEY_INVALID');assert.equal(keyFromBase64(Buffer.alloc(32).toString('base64')).length,32);});
test('foundation server is read-only and isolated',async()=>{const app=server();await new Promise((resolve,reject)=>{app.once('error',reject);app.listen(0,'127.0.0.1',resolve);});try{const origin=`http://127.0.0.1:${app.address().port}`,page=await fetch(origin);assert.equal(page.status,200);assert.match(page.headers.get('x-robots-tag'),/noindex/);assert.match(page.headers.get('content-security-policy'),/connect-src 'none'/);assert.equal((await fetch(origin,{method:'POST'})).status,405);assert.equal((await fetch(origin+'/missing')).status,404);}finally{await new Promise(resolve=>app.close(resolve));}});
