'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {createStagingControlPlane,createSyntheticStagingAdapter,createBlockedStagingAdapter,sha}=require('../packages/staging-control-plane/index.cjs');const {server}=require('../scripts/serve-staging-control-plane.cjs');
const actors={admin:{actor_id:'admin-one',roles:['platform_admin']},admin2:{actor_id:'admin-two',roles:['platform_admin']},operator:{actor_id:'operator-one',roles:['platform_operator']},finance:{actor_id:'finance-one',roles:['finance_approver']},executor:{actor_id:'executor-one',roles:['platform_executor']},release:{actor_id:'release-one',roles:['release_manager']},security:{actor_id:'security-one',roles:['security_approver']},destroy:{actor_id:'destroy-one',roles:['destroy_approver']},viewer:{actor_id:'viewer-one',roles:['viewer']}};
function clock(){let value=new Date('2026-11-10T15:00:00Z');return {now:()=>new Date(value),advance:s=>{value=new Date(value.getTime()+s*1000);}};}
function fixture(options={}){const time=clock(),adapter=options.blocked?createBlockedStagingAdapter():createSyntheticStagingAdapter(options),service=createStagingControlPlane({adapter,now:time.now});return {time,adapter,service};}
function declared(options={}){const state=fixture(options),environment=state.service.createEnvironment(actors.admin,{environment_id:'staging-test',provider:'local-synthetic',region_policy:'Synthetic global edge',external_changes_allowed:false});state.service.declareResource(actors.operator,environment.environment_id,{resource_id:'res-db',kind:'d1',logical_name:'test-control-db',configuration:{type:'d1'}});state.service.declareResource(actors.operator,environment.environment_id,{resource_id:'res-queue',kind:'queue',logical_name:'test-events',configuration:{type:'queue'}});state.service.declareResource(actors.operator,environment.environment_id,{resource_id:'res-worker',kind:'worker',logical_name:'test-worker',depends_on:['res-db','res-queue'],configuration:{type:'worker'}});const preflight=state.service.preflight(actors.operator,environment.environment_id,['CF_ACCOUNT_ID','CF_D1_DATABASE_ID'],{CF_ACCOUNT_ID:'present',CF_D1_DATABASE_ID:'present'}),budget=state.service.createBudget(actors.operator,environment.environment_id,{monthly_limit_cents:5000,warning_percent:80}),approvedBudget=state.service.approveBudget(actors.finance,budget.budget_id);return {...state,environment,preflight,budget:approvedBudget};}
function planned(options={}){const state=declared(options),plan=state.service.createPlan(actors.operator,{environment_ref:state.environment.environment_id,preflight_ref:state.preflight.preflight_id,budget_ref:state.budget.budget_id,mode:'dry_run',estimated_monthly_cost_cents:2000}),approvedPlan=state.service.approvePlan(actors.admin,plan.plan_id);return {...state,plan:approvedPlan};}
function executed(options={}){const state=planned(options),execution=state.service.executePlan(actors.executor,state.plan.plan_id);return {...state,execution};}
function promoted(options={}){const state=executed(options),artifact_digest=sha('artifact'),manifest_digest=sha('manifest'),attestation={attestation_id:'attest-test-001',artifact_digest,manifest_digest,status:'verified'},promotion=state.service.createPromotion(actors.release,{environment_ref:state.environment.environment_id,artifact_digest,manifest_digest,attestation,source_release:'release-local-001',target_release:'release-staging-001'}),approvedPromotion=state.service.approvePromotion(actors.security,promotion.promotion_id);return {...state,artifact_digest,manifest_digest,attestation,promotion:approvedPromotion};}

test('creates a synthetic-only staging environment',()=>{const {environment}=declared();assert.equal(environment.data_classification,'synthetic');assert.equal(environment.external_changes_allowed,false);});
test('environment creation requires platform admin',()=>{const {service}=fixture();assert.throws(()=>service.createEnvironment(actors.viewer,{environment_id:'staging-x',region_policy:'Synthetic only'}),{code:'ROLE_REQUIRED'});});
test('duplicate environment is rejected',()=>{const {service}=declared();assert.throws(()=>service.createEnvironment(actors.admin,{environment_id:'staging-test',region_policy:'Synthetic only'}),{code:'ENVIRONMENT_EXISTS'});});
test('real data classification is blocked',()=>{const {service}=fixture();assert.throws(()=>service.createEnvironment(actors.admin,{environment_id:'staging-real',region_policy:'Global',data_classification:'real'}),{code:'REAL_DATA_BLOCKED'});});
test('declares resources with deterministic desired digests',()=>{const {service}=declared();assert.match(service.getResource('res-db').desired_digest,/^[a-f0-9]{64}$/);});
test('resource declaration requires operator role',()=>{const {service,environment}=declared();assert.throws(()=>service.declareResource(actors.viewer,environment.environment_id,{kind:'r2',logical_name:'blocked-resource'}),{code:'ROLE_REQUIRED'});});
test('duplicate logical resource is rejected',()=>{const {service,environment}=declared();assert.throws(()=>service.declareResource(actors.operator,environment.environment_id,{kind:'d1',logical_name:'test-control-db'}),{code:'RESOURCE_EXISTS'});});
test('resource lifecycle defaults to managed',()=>{const {service}=declared();assert.equal(service.getResource('res-db').lifecycle,'managed');});
test('preflight reports missing configuration names only',()=>{const {service,environment}=declared(),result=service.preflight(actors.operator,environment.environment_id,['CF_ACCOUNT_ID','CF_ZONE_ID'],{CF_ACCOUNT_ID:'secret-value'});assert.deepEqual(result.missing_names,['CF_ZONE_ID']);assert.equal(result.secret_values_persisted,0);});
test('ready preflight marks environment ready',()=>{const {service,environment,preflight}=declared();assert.equal(preflight.status,'ready');assert.equal(service.getEnvironment(environment.environment_id).status,'ready');});
test('blocked preflight cannot create plan',()=>{const state=declared(),blocked=state.service.preflight(actors.operator,state.environment.environment_id,['MISSING_NAME'],{});assert.throws(()=>state.service.createPlan(actors.operator,{environment_ref:state.environment.environment_id,preflight_ref:blocked.preflight_id,budget_ref:state.budget.budget_id,mode:'dry_run',estimated_monthly_cost_cents:1}),{code:'PREFLIGHT_NOT_READY'});});
test('preflight deduplicates required names',()=>{const {service,environment}=declared(),result=service.preflight(actors.operator,environment.environment_id,['CF_ACCOUNT_ID','CF_ACCOUNT_ID'],{CF_ACCOUNT_ID:'present'});assert.equal(result.required_names.length,1);});
test('budget starts as draft',()=>{const {service,environment}=declared(),budget=service.createBudget(actors.operator,environment.environment_id,{monthly_limit_cents:1000});assert.equal(budget.status,'draft');});
test('budget requires finance approval',()=>{const {service,environment}=declared(),budget=service.createBudget(actors.operator,environment.environment_id,{monthly_limit_cents:1000});assert.throws(()=>service.approveBudget(actors.viewer,budget.budget_id),{code:'ROLE_REQUIRED'});});
test('budget creator cannot approve own budget',()=>{const {service,environment}=declared(),creator={actor_id:'same',roles:['platform_operator','finance_approver']},budget=service.createBudget(creator,environment.environment_id,{monthly_limit_cents:1000});assert.throws(()=>service.approveBudget(creator,budget.budget_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('approved budget records independent reviewer',()=>{const {budget}=declared();assert.equal(budget.approved_by,actors.finance.actor_id);});
test('cost below warning is allowed',()=>{const {service,budget}=declared({actualCostCents:1200}),observation=service.observeCost(actors.operator,budget.budget_id,2000);assert.equal(observation.action,'allow');});
test('cost at warning threshold warns',()=>{const {service,budget}=declared({actualCostCents:4000}),observation=service.observeCost(actors.operator,budget.budget_id,4000);assert.equal(observation.action,'warn');});
test('cost at hard limit blocks',()=>{const {service,budget}=declared({actualCostCents:5000}),observation=service.observeCost(actors.operator,budget.budget_id,1000);assert.equal(observation.action,'block');});
test('plan orders dependencies before worker',()=>{const {plan}=planned();assert.deepEqual(plan.resource_refs.slice(-1),['res-worker']);});
test('plan digest binds immutable intent',()=>{const {plan}=planned();assert.match(plan.plan_digest,/^[a-f0-9]{64}$/);});
test('plan requires resources',()=>{const state=fixture(),env=state.service.createEnvironment(actors.admin,{environment_id:'empty-stage',region_policy:'Synthetic'}),pf=state.service.preflight(actors.operator,env.environment_id,['CF_ACCOUNT_ID'],{CF_ACCOUNT_ID:'x'}),budget=state.service.createBudget(actors.operator,env.environment_id,{monthly_limit_cents:1000}),approved=state.service.approveBudget(actors.finance,budget.budget_id);assert.throws(()=>state.service.createPlan(actors.operator,{environment_ref:env.environment_id,preflight_ref:pf.preflight_id,budget_ref:approved.budget_id,mode:'dry_run',estimated_monthly_cost_cents:10}),{code:'RESOURCES_REQUIRED'});});
test('plan detects missing dependency',()=>{const state=declared();state.service.declareResource(actors.operator,state.environment.environment_id,{resource_id:'res-bad',kind:'worker',logical_name:'bad-worker',depends_on:['res-missing']});assert.throws(()=>state.service.createPlan(actors.operator,{environment_ref:state.environment.environment_id,preflight_ref:state.preflight.preflight_id,budget_ref:state.budget.budget_id,mode:'dry_run',estimated_monthly_cost_cents:10}),{code:'DEPENDENCY_NOT_FOUND'});});
test('plan detects dependency cycle',()=>{const state=fixture(),env=state.service.createEnvironment(actors.admin,{environment_id:'cycle-stage',region_policy:'Synthetic'});state.service.declareResource(actors.operator,env.environment_id,{resource_id:'res-a',kind:'worker',logical_name:'cycle-a',depends_on:['res-b']});state.service.declareResource(actors.operator,env.environment_id,{resource_id:'res-b',kind:'worker',logical_name:'cycle-b',depends_on:['res-a']});const pf=state.service.preflight(actors.operator,env.environment_id,['CF_ACCOUNT_ID'],{CF_ACCOUNT_ID:'x'}),budget=state.service.createBudget(actors.operator,env.environment_id,{monthly_limit_cents:1000}),approved=state.service.approveBudget(actors.finance,budget.budget_id);assert.throws(()=>state.service.createPlan(actors.operator,{environment_ref:env.environment_id,preflight_ref:pf.preflight_id,budget_ref:approved.budget_id,mode:'dry_run',estimated_monthly_cost_cents:10}),{code:'RESOURCE_CYCLE'});});
test('apply mode is blocked on synthetic adapter',()=>{const state=declared();assert.throws(()=>state.service.createPlan(actors.operator,{environment_ref:state.environment.environment_id,preflight_ref:state.preflight.preflight_id,budget_ref:state.budget.budget_id,mode:'apply',estimated_monthly_cost_cents:10}),{code:'APPLY_BLOCKED'});});
test('plan creator cannot approve own plan',()=>{const state=declared(),same={actor_id:'same',roles:['platform_operator','platform_admin']},plan=state.service.createPlan(same,{environment_ref:state.environment.environment_id,preflight_ref:state.preflight.preflight_id,budget_ref:state.budget.budget_id,mode:'dry_run',estimated_monthly_cost_cents:10});assert.throws(()=>state.service.approvePlan(same,plan.plan_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('independent admin approves plan',()=>{const {plan}=planned();assert.equal(plan.status,'approved');});
test('unapproved plan cannot execute',()=>{const state=declared(),plan=state.service.createPlan(actors.operator,{environment_ref:state.environment.environment_id,preflight_ref:state.preflight.preflight_id,budget_ref:state.budget.budget_id,mode:'dry_run',estimated_monthly_cost_cents:10});assert.throws(()=>state.service.executePlan(actors.executor,plan.plan_id),{code:'PLAN_NOT_APPROVED'});});
test('dry-run plan simulates every resource',()=>{const {execution}=executed();assert.equal(execution.plan.status,'simulated');assert.equal(execution.changes.length,3);assert(execution.changes.every(item=>item.external_change===false));});
test('budget hard stop blocks execution',()=>{const state=planned({actualCostCents:5000});assert.throws(()=>state.service.executePlan(actors.executor,state.plan.plan_id),{code:'BUDGET_EXHAUSTED'});});
test('executed plan activates environment',()=>{const {service,environment}=executed();assert.equal(service.getEnvironment(environment.environment_id).status,'active');});
test('execution marks resources ready',()=>{const {service}=executed();assert.equal(service.getResource('res-worker').status,'ready');});
test('inventory contains every declared resource',()=>{const {service,environment}=executed(),inventory=service.captureInventory(actors.operator,environment.environment_id);assert.equal(inventory.resources.length,3);});
test('inventory has a deterministic content digest',()=>{const {service,environment}=executed(),inventory=service.captureInventory(actors.operator,environment.environment_id);assert.match(inventory.inventory_digest,/^[a-f0-9]{64}$/);});
test('external inventory query is blocked in synthetic mode',()=>{const {service,environment}=executed();assert.throws(()=>service.captureInventory(actors.operator,environment.environment_id,{externalQuery:true}),{code:'EXTERNAL_QUERY_BLOCKED'});});
test('matching inventory reports in sync',()=>{const {service,environment}=executed(),inventory=service.captureInventory(actors.operator,environment.environment_id),drift=service.observeDrift(actors.operator,environment.environment_id,inventory.inventory_id);assert.equal(drift.status,'in_sync');assert.equal(drift.secrets_compared,false);});
test('changed digest creates critical drift',()=>{const {service,environment}=executed({driftResource:'res-worker'}),inventory=service.captureInventory(actors.operator,environment.environment_id),drift=service.observeDrift(actors.operator,environment.environment_id,inventory.inventory_id);assert.equal(drift.status,'critical');assert.equal(drift.differences[0].field,'digest');});
test('missing resource creates critical drift',()=>{const {service,environment}=executed({missingResource:'res-db'}),inventory=service.captureInventory(actors.operator,environment.environment_id),drift=service.observeDrift(actors.operator,environment.environment_id,inventory.inventory_id);assert.equal(drift.status,'critical');assert.equal(drift.differences[0].field,'presence');});
test('inventory cannot be used for another environment',()=>{const {service,environment}=executed(),inventory=service.captureInventory(actors.operator,environment.environment_id);service.createEnvironment(actors.admin,{environment_id:'other-stage',region_policy:'Synthetic'});assert.throws(()=>service.observeDrift(actors.operator,'other-stage',inventory.inventory_id),{code:'INVENTORY_MISMATCH'});});
test('promotion requires active environment',()=>{const state=declared(),d=sha('x'),attestation={attestation_id:'attest-x',artifact_digest:d,manifest_digest:d,status:'verified'};assert.throws(()=>state.service.createPromotion(actors.release,{environment_ref:state.environment.environment_id,artifact_digest:d,manifest_digest:d,attestation,source_release:'release-a',target_release:'release-b'}),{code:'ENVIRONMENT_NOT_ACTIVE'});});
test('promotion requires matching artifact attestation',()=>{const state=executed(),d=sha('x'),attestation={attestation_id:'attest-x',artifact_digest:sha('other'),manifest_digest:d,status:'verified'};assert.throws(()=>state.service.createPromotion(actors.release,{environment_ref:state.environment.environment_id,artifact_digest:d,manifest_digest:d,attestation,source_release:'release-a',target_release:'release-b'}),{code:'ATTESTATION_INVALID'});});
test('valid promotion begins as draft',()=>{const {promotion}=promoted();assert.equal(promotion.status,'approved');assert.equal(promotion.approved_by,actors.security.actor_id);});
test('promotion creator cannot self approve',()=>{const state=executed(),d=sha('x'),attestation={attestation_id:'attest-x',artifact_digest:d,manifest_digest:d,status:'verified'},same={actor_id:'same',roles:['release_manager','security_approver']},promotion=state.service.createPromotion(same,{environment_ref:state.environment.environment_id,artifact_digest:d,manifest_digest:d,attestation,source_release:'release-a',target_release:'release-b'});assert.throws(()=>state.service.approvePromotion(same,promotion.promotion_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('smoke suite deduplicates checks',()=>{const state=promoted(),suite=state.service.createSmokeSuite(actors.release,state.environment.environment_id,['health','health','noindex']);assert.equal(suite.checks.length,2);assert.equal(suite.minimum_passed,2);});
test('approved promotion passes complete smoke suite',()=>{const state=promoted(),suite=state.service.createSmokeSuite(actors.release,state.environment.environment_id,['health','artifact_digest','identity_deny']),result=state.service.runSmoke(actors.executor,suite.suite_id,state.promotion.promotion_id);assert.equal(result.status,'passed');assert.equal(result.passed,3);});
test('failed smoke blocks promotion',()=>{const state=promoted({failSmoke:'health'}),suite=state.service.createSmokeSuite(actors.release,state.environment.environment_id,['health','noindex']),result=state.service.runSmoke(actors.executor,suite.suite_id,state.promotion.promotion_id);assert.equal(result.status,'failed');assert.equal(state.service.getPromotion(state.promotion.promotion_id).status,'blocked');});
test('unapproved promotion cannot run smoke',()=>{const state=executed(),d=sha('x'),attestation={attestation_id:'attest-x',artifact_digest:d,manifest_digest:d,status:'verified'},promotion=state.service.createPromotion(actors.release,{environment_ref:state.environment.environment_id,artifact_digest:d,manifest_digest:d,attestation,source_release:'release-a',target_release:'release-b'}),suite=state.service.createSmokeSuite(actors.release,state.environment.environment_id,['health']);assert.throws(()=>state.service.runSmoke(actors.executor,suite.suite_id,promotion.promotion_id),{code:'PROMOTION_NOT_APPROVED'});});
test('rollback plan starts draft with safe steps',()=>{const state=promoted(),rollback=state.service.createRollback(actors.release,state.promotion.promotion_id,'release-local-previous');assert.equal(rollback.status,'draft');assert(rollback.steps.includes('verify audit chain'));});
test('rollback creator cannot approve own rollback',()=>{const state=promoted(),same={actor_id:'same',roles:['release_manager','platform_admin']},rollback=state.service.createRollback(same,state.promotion.promotion_id,'release-local-previous');assert.throws(()=>state.service.approveRollback(same,rollback.rollback_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('unapproved rollback cannot execute',()=>{const state=promoted(),rollback=state.service.createRollback(actors.release,state.promotion.promotion_id,'release-local-previous');assert.throws(()=>state.service.executeRollback(actors.executor,rollback.rollback_id),{code:'ROLLBACK_NOT_APPROVED'});});
test('approved rollback restores prior release synthetically',()=>{const state=promoted(),rollback=state.service.createRollback(actors.release,state.promotion.promotion_id,'release-local-previous'),approved=state.service.approveRollback(actors.admin,rollback.rollback_id),run=state.service.executeRollback(actors.executor,approved.rollback_id);assert.equal(run.rollback.status,'executed');assert.equal(run.result.external_change,false);});
test('rollback marks promotion rolled back',()=>{const state=promoted(),rollback=state.service.createRollback(actors.release,state.promotion.promotion_id,'release-local-previous'),approved=state.service.approveRollback(actors.admin,rollback.rollback_id);state.service.executeRollback(actors.executor,approved.rollback_id);assert.equal(state.service.getPromotion(state.promotion.promotion_id).status,'rolled_back');});
test('teardown reverses dependency order',()=>{const state=executed(),teardown=state.service.createTeardown(actors.operator,state.environment.environment_id);assert.equal(teardown.ordered_deletions[0],'res-worker');});
test('teardown retains shared resources',()=>{const state=declared();state.service.declareResource(actors.operator,state.environment.environment_id,{resource_id:'res-shared',kind:'secrets_store',logical_name:'shared-secrets',lifecycle:'retain'});const plan=state.service.createPlan(actors.operator,{environment_ref:state.environment.environment_id,preflight_ref:state.preflight.preflight_id,budget_ref:state.budget.budget_id,mode:'dry_run',estimated_monthly_cost_cents:100}),approved=state.service.approvePlan(actors.admin,plan.plan_id);state.service.executePlan(actors.executor,approved.plan_id);const teardown=state.service.createTeardown(actors.operator,state.environment.environment_id);assert.deepEqual(teardown.retained_refs,['res-shared']);});
test('teardown requires destroy approver',()=>{const state=executed(),teardown=state.service.createTeardown(actors.operator,state.environment.environment_id);assert.throws(()=>state.service.approveTeardown(actors.viewer,teardown.teardown_id),{code:'ROLE_REQUIRED'});});
test('teardown creator cannot self approve',()=>{const state=executed(),same={actor_id:'same',roles:['platform_operator','destroy_approver']},teardown=state.service.createTeardown(same,state.environment.environment_id);assert.throws(()=>state.service.approveTeardown(same,teardown.teardown_id),{code:'INDEPENDENT_APPROVAL_REQUIRED'});});
test('unapproved teardown cannot execute',()=>{const state=executed(),teardown=state.service.createTeardown(actors.operator,state.environment.environment_id);assert.throws(()=>state.service.executeTeardown(actors.executor,teardown.teardown_id),{code:'TEARDOWN_NOT_APPROVED'});});
test('synthetic teardown marks managed resources destroyed',()=>{const state=executed(),teardown=state.service.createTeardown(actors.operator,state.environment.environment_id),approved=state.service.approveTeardown(actors.destroy,teardown.teardown_id),run=state.service.executeTeardown(actors.executor,approved.teardown_id);assert.equal(run.status,'simulated');assert.equal(state.service.getResource('res-worker').status,'destroyed');});
test('complete rehearsal passes with no external changes',()=>{const state=promoted(),suite=state.service.createSmokeSuite(actors.release,state.environment.environment_id,['health','audit_chain']),smoke=state.service.runSmoke(actors.executor,suite.suite_id,state.promotion.promotion_id),rollback=state.service.createRollback(actors.release,state.promotion.promotion_id,'release-local-previous'),approvedRollback=state.service.approveRollback(actors.admin,rollback.rollback_id);state.service.executeRollback(actors.executor,approvedRollback.rollback_id);const teardown=state.service.createTeardown(actors.operator,state.environment.environment_id),approvedTeardown=state.service.approveTeardown(actors.destroy,teardown.teardown_id);state.service.executeTeardown(actors.executor,approvedTeardown.teardown_id);const result=state.service.recordRehearsal(actors.admin,{environment_ref:state.environment.environment_id,plan_ref:state.plan.plan_id,promotion_ref:state.promotion.promotion_id,smoke_result_ref:smoke.result_id,rollback_ref:rollback.rollback_id,teardown_ref:teardown.teardown_id});assert.equal(result.status,'passed');assert.equal(result.external_changes,false);});
test('blocked adapter cannot provision staging',()=>{const {service}=fixture({blocked:true}),env=service.createEnvironment(actors.admin,{environment_id:'blocked-stage',provider:'cloudflare',region_policy:'Global',external_changes_allowed:false});assert.equal(env.status,'draft');assert.equal(service.summary().adapter_mode,'blocked');});
test('summary reports all lifecycle artifacts',()=>{const state=executed(),inventory=state.service.captureInventory(actors.operator,state.environment.environment_id);state.service.observeDrift(actors.operator,state.environment.environment_id,inventory.inventory_id);const summary=state.service.summary();assert.equal(summary.environments,1);assert.equal(summary.resources,3);assert.equal(summary.plans,1);assert.equal(summary.drifts,1);});

function request(instance,url,method='GET'){return new Promise((resolve,reject)=>{const address=instance.address(),req=http.request({hostname:'127.0.0.1',port:address.port,path:url,method},res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body}));});req.on('error',reject);req.end();});}async function startedServer(){const instance=server();await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve);});return instance;}
test('staging console serves protected noindex HTML',async()=>{const instance=await startedServer();try{const response=await request(instance,'/');assert.equal(response.status,200);assert.match(response.body,/Staging Control Plane/);assert.match(response.headers['content-security-policy'],/connect-src 'none'/);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('staging console supports HEAD',async()=>{const instance=await startedServer();try{const response=await request(instance,'/','HEAD');assert.equal(response.status,200);assert.equal(response.body,'');}finally{await new Promise(resolve=>instance.close(resolve));}});
test('staging console rejects writes and traversal',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/','POST')).status,405);assert.equal((await request(instance,'/%2e%2e/package.json')).status,404);}finally{await new Promise(resolve=>instance.close(resolve));}});
