'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {createZeroTrustSecurity,sha}=require('../packages/zero-trust-security/index.cjs');
const {server}=require('../scripts/serve-zero-trust-security.cjs');
const actors={admin:{actor_id:'security-admin',roles:['security_admin']},broker:{actor_id:'token-broker',roles:['token_broker']},operator:{actor_id:'operator-one',roles:['operator']},approver1:{actor_id:'approver-one',roles:['security_approver']},approver2:{actor_id:'approver-two',roles:['security_approver']},executor:{actor_id:'executor-one',roles:['privileged_executor']},responder:{actor_id:'responder-one',roles:['incident_responder']},outsider:{actor_id:'outsider',roles:['viewer']}};
function clock(){let value=new Date('2026-11-03T15:00:00Z');return {now:()=>new Date(value),advance:seconds=>{value=new Date(value.getTime()+seconds*1000);}};}
function fixture(){const time=clock(),service=createZeroTrustSecurity({now:time.now});return {time,service};}
function configured(){const state=fixture();state.service.registerIdentity(actors.admin,{identity_id:'svc-publisher',display_name:'Publisher',tenant_scopes:['tenant-horizonte'],capabilities:['site.publish','artifact.attest']});state.service.bindWorkload(actors.admin,{identity_ref:'svc-publisher',runtime:'local',subject:'process:publisher',environment:'local'});state.service.definePolicy(actors.admin,{policy_id:'policy-publish',capabilities:['site.publish','artifact.attest'],environments:['local','staging'],maximum_risk:'medium'});return state;}
function issued(){const state=configured(),result=state.service.issueCredential(actors.broker,{identity_ref:'svc-publisher',audience:'control-plane',ttl_seconds:300});return {...state,...result};}

test('registers a least-privilege service identity',()=>{const {service}=configured();assert.equal(service.summary().identities,1);assert.deepEqual(service.summary().active_key_ref,'sigk-root-001');});
test('identity registration requires security admin',()=>{const {service}=fixture();assert.throws(()=>service.registerIdentity(actors.outsider,{identity_id:'svc-x',display_name:'X service',tenant_scopes:['t'],capabilities:['x.read']}),{code:'ROLE_REQUIRED'});});
test('duplicate identity is rejected',()=>{const {service}=configured();assert.throws(()=>service.registerIdentity(actors.admin,{identity_id:'svc-publisher',display_name:'Duplicate',tenant_scopes:['t'],capabilities:['x.read']}),{code:'IDENTITY_EXISTS'});});
test('workload binding records runtime subject',()=>{const {service}=configured();assert.equal(service.summary().bindings,1);});
test('workload binding rejects unknown identity',()=>{const {service}=fixture();assert.throws(()=>service.bindWorkload(actors.admin,{identity_ref:'svc-missing',runtime:'local',subject:'process:x',environment:'local'}),{code:'IDENTITY_NOT_FOUND'});});
test('policy versions increase on replacement',()=>{const {service}=configured(),policy=service.definePolicy(actors.admin,{policy_id:'policy-publish',capabilities:['site.publish'],environments:['local'],maximum_risk:'low'});assert.equal(policy.version,2);});
test('credential contains no reusable secret record',()=>{const {credential,token}=issued();assert.match(token,/^hct1\./);assert.equal(credential.token_hash,sha(token));assert.equal('token' in credential,false);});
test('token broker may issue a credential',()=>{const {credential}=issued();assert.equal(credential.status,'active');});
test('credential ttl has a lower bound',()=>{const {service}=configured();assert.throws(()=>service.issueCredential(actors.broker,{identity_ref:'svc-publisher',audience:'control-plane',ttl_seconds:10}),{code:'CREDENTIAL_TTL_INVALID'});});
test('credential ttl has an upper bound',()=>{const {service}=configured();assert.throws(()=>service.issueCredential(actors.broker,{identity_ref:'svc-publisher',audience:'control-plane',ttl_seconds:901}),{code:'CREDENTIAL_TTL_INVALID'});});
test('credential cannot escalate tenants',()=>{const {service}=configured();assert.throws(()=>service.issueCredential(actors.broker,{identity_ref:'svc-publisher',audience:'control-plane',ttl_seconds:300,tenant_scopes:['tenant-other']}),{code:'SCOPE_ESCALATION'});});
test('credential cannot escalate capabilities',()=>{const {service}=configured();assert.throws(()=>service.issueCredential(actors.broker,{identity_ref:'svc-publisher',audience:'control-plane',ttl_seconds:300,capabilities:['site.delete']}),{code:'SCOPE_ESCALATION'});});
test('valid credential is authorized by policy',()=>{const {service,token}=issued(),result=service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}});assert.equal(result.decision.result,'allow');});
test('wrong audience is denied',()=>{const {service,token}=issued();assert.throws(()=>service.verifyCredential(token,{audience:'other',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'AUDIENCE_MISMATCH'});});
test('wrong tenant is denied',()=>{const {service,token}=issued();assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-other',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'TENANT_SCOPE_DENIED'});});
test('ungranted capability is denied',()=>{const {service,token}=issued();assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.delete',context:{environment:'local',risk:'low'}}),{code:'CAPABILITY_DENIED'});});
test('tampered token signature is denied',()=>{const {service,token}=issued(),bad=token.slice(0,-2)+'aa';assert.throws(()=>service.verifyCredential(bad,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'TOKEN_SIGNATURE_INVALID'});});
test('expired credential is denied',()=>{const {service,token,time}=issued();time.advance(301);assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'TOKEN_EXPIRED'});});
test('revoked credential is denied',()=>{const {service,token,credential}=issued();service.revokeCredential(actors.admin,credential.credential_id);assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'TOKEN_REVOKED'});});
test('suspended identity invalidates live credential',()=>{const {service,token}=issued();service.setIdentityStatus(actors.admin,'svc-publisher','suspended');assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'IDENTITY_INACTIVE'});});
test('policy blocks unsupported environment',()=>{const {service,token}=issued();assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'production',risk:'low'}}),{code:'ENVIRONMENT_DENIED'});});
test('policy blocks excessive risk',()=>{const {service,token}=issued();assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'high'}}),{code:'RISK_DENIED'});});
test('policy can require mfa',()=>{const {service}=configured();service.definePolicy(actors.admin,{policy_id:'policy-publish',capabilities:['site.publish','artifact.attest'],environments:['local'],maximum_risk:'medium',require_mfa:true});const {token}=service.issueCredential(actors.broker,{identity_ref:'svc-publisher',audience:'control-plane',ttl_seconds:300});assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'MFA_REQUIRED'});});
test('mfa satisfies a policy that requires it',()=>{const {service}=configured();service.definePolicy(actors.admin,{policy_id:'policy-publish',capabilities:['site.publish','artifact.attest'],environments:['local'],maximum_risk:'medium',require_mfa:true});const {token}=service.issueCredential(actors.broker,{identity_ref:'svc-publisher',audience:'control-plane',ttl_seconds:300}),result=service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low',mfa:true}});assert.equal(result.decision.result,'allow');});
test('denials are recorded as access decisions',()=>{const {service,token}=issued();assert.throws(()=>service.verifyCredential(token,{audience:'wrong',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local'}}));assert.equal(service.listDecisions().at(-1).result,'deny');});
test('key rotation creates a new active key',()=>{const {service}=configured(),before=service.summary().active_key_ref,rotation=service.rotateSigningKey(actors.admin,{grace_seconds:60});assert.notEqual(rotation.new_key_ref,before);assert.equal(service.summary().keys,2);});
test('old token works during key grace period',()=>{const {service,token}=issued();service.rotateSigningKey(actors.admin,{grace_seconds:60});assert.equal(service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}).decision.result,'allow');});
test('old token fails after grace and retirement',()=>{const {service,token,time}=issued();service.rotateSigningKey(actors.admin,{grace_seconds:60});time.advance(61);service.retireExpiredKeys(actors.admin);assert.throws(()=>service.verifyCredential(token,{audience:'control-plane',tenant_id:'tenant-horizonte',capability:'site.publish',context:{environment:'local',risk:'low'}}),{code:'TOKEN_KEY_INACTIVE'});});
test('key rotation requires security admin',()=>{const {service}=configured();assert.throws(()=>service.rotateSigningKey(actors.outsider),{code:'ROLE_REQUIRED'});});
test('artifact receives a verifiable attestation',()=>{const {service,token}=issued(),attestation=service.attestArtifact(token,{audience:'control-plane',tenant_id:'tenant-horizonte',environment:'local',artifact_name:'site-bundle.zip',artifact_digest:'a'.repeat(64),manifest_digest:'b'.repeat(64)});assert(service.verifyAttestation(attestation.attestation_id));});
test('artifact attestation rejects wrong environment policy',()=>{const {service,token}=issued();assert.throws(()=>service.attestArtifact(token,{audience:'control-plane',tenant_id:'tenant-horizonte',environment:'production',artifact_name:'site.zip',artifact_digest:'a'.repeat(64),manifest_digest:'b'.repeat(64)}),{code:'ENVIRONMENT_DENIED'});});
test('high-risk operation needs one approval',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'tenant.pause',resource:'tenant-horizonte',risk:'high',justification:'Pause during a synthetic incident rehearsal'});assert.equal(operation.required_approvals,1);});
test('critical operation needs two approvals',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'key.revoke',resource:'sigk-root-001',risk:'critical',justification:'Revoke a compromised signing key in rehearsal'});assert.equal(operation.required_approvals,2);});
test('requester cannot approve own operation',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation({...actors.operator,roles:['operator','security_approver']},{capability:'tenant.pause',resource:'tenant-horizonte',risk:'high',justification:'Pause during a synthetic incident rehearsal'});assert.throws(()=>service.approvePrivilegedOperation({...actors.operator,roles:['security_approver']},operation.operation_id),{code:'SELF_APPROVAL_DENIED'});});
test('duplicate operation approval is rejected',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'tenant.pause',resource:'tenant-horizonte',risk:'critical',justification:'Pause during a synthetic incident rehearsal'});service.approvePrivilegedOperation(actors.approver1,operation.operation_id);assert.throws(()=>service.approvePrivilegedOperation(actors.approver1,operation.operation_id),{code:'DUPLICATE_APPROVAL'});});
test('one approval leaves critical operation pending',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'key.revoke',resource:'key-1',risk:'critical',justification:'Critical key response synthetic rehearsal'}),result=service.approvePrivilegedOperation(actors.approver1,operation.operation_id);assert.equal(result.operation.status,'pending');});
test('two approvals authorize critical operation',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'key.revoke',resource:'key-1',risk:'critical',justification:'Critical key response synthetic rehearsal'});service.approvePrivilegedOperation(actors.approver1,operation.operation_id);const result=service.approvePrivilegedOperation(actors.approver2,operation.operation_id);assert.equal(result.operation.status,'approved');});
test('unapproved privileged operation cannot execute',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'tenant.pause',resource:'tenant-horizonte',risk:'high',justification:'Pause during a synthetic incident rehearsal'});assert.throws(()=>service.executePrivilegedOperation(actors.executor,operation.operation_id,()=>({ok:true})),{code:'OPERATION_NOT_APPROVED'});});
test('approver cannot execute the operation',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'tenant.pause',resource:'tenant-horizonte',risk:'high',justification:'Pause during a synthetic incident rehearsal'});service.approvePrivilegedOperation(actors.approver1,operation.operation_id);assert.throws(()=>service.executePrivilegedOperation({...actors.approver1,roles:['privileged_executor']},operation.operation_id,()=>({ok:true})),{code:'SEPARATION_OF_DUTIES_REQUIRED'});});
test('independent executor runs an approved operation once',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'tenant.pause',resource:'tenant-horizonte',risk:'high',justification:'Pause during a synthetic incident rehearsal'});service.approvePrivilegedOperation(actors.approver1,operation.operation_id);const result=service.executePrivilegedOperation(actors.executor,operation.operation_id,input=>({applied:true,resource:input.resource}));assert.equal(result.operation.status,'executed');assert(result.result.applied);});
test('rejected operation cannot execute',()=>{const {service}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'tenant.pause',resource:'tenant-horizonte',risk:'high',justification:'Pause during a synthetic incident rehearsal'});service.approvePrivilegedOperation(actors.approver1,operation.operation_id,{decision:'reject',comment:'Insufficient evidence'});assert.throws(()=>service.executePrivilegedOperation(actors.executor,operation.operation_id,()=>({ok:true})),{code:'OPERATION_NOT_APPROVED'});});
test('expired operation cannot be approved',()=>{const {service,time}=fixture(),operation=service.requestPrivilegedOperation(actors.operator,{capability:'tenant.pause',resource:'tenant-horizonte',risk:'high',justification:'Pause during a synthetic incident rehearsal',ttl_seconds:60});time.advance(61);assert.throws(()=>service.approvePrivilegedOperation(actors.approver1,operation.operation_id),{code:'OPERATION_EXPIRED'});});
test('break-glass starts pending',()=>{const {service}=fixture(),session=service.requestBreakGlass(actors.responder,{ticket_ref:'INC-2026-001',reason:'Synthetic outage requires temporary diagnostic access',capabilities:['tenant.inspect'],tenant_scopes:['tenant-horizonte'],ttl_seconds:300});assert.equal(session.status,'pending');});
test('break-glass requester cannot self approve',()=>{const {service}=fixture(),session=service.requestBreakGlass({...actors.responder,roles:['incident_responder','security_approver']},{ticket_ref:'INC-1',reason:'Synthetic outage requires temporary diagnostic access',capabilities:['tenant.inspect'],tenant_scopes:['tenant-horizonte']});assert.throws(()=>service.approveBreakGlass({...actors.responder,roles:['security_approver']},session.session_id),{code:'SELF_APPROVAL_DENIED'});});
test('approved break-glass permits exact scope',()=>{const {service}=fixture(),session=service.requestBreakGlass(actors.responder,{ticket_ref:'INC-1',reason:'Synthetic outage requires temporary diagnostic access',capabilities:['tenant.inspect'],tenant_scopes:['tenant-horizonte']});service.approveBreakGlass(actors.approver1,session.session_id);assert(service.authorizeBreakGlass(actors.responder,session.session_id,{tenant_id:'tenant-horizonte',capability:'tenant.inspect'}));});
test('break-glass denies scope expansion',()=>{const {service}=fixture(),session=service.requestBreakGlass(actors.responder,{ticket_ref:'INC-1',reason:'Synthetic outage requires temporary diagnostic access',capabilities:['tenant.inspect'],tenant_scopes:['tenant-horizonte']});service.approveBreakGlass(actors.approver1,session.session_id);assert.throws(()=>service.authorizeBreakGlass(actors.responder,session.session_id,{tenant_id:'tenant-other',capability:'tenant.inspect'}),{code:'BREAK_GLASS_SCOPE_DENIED'});});
test('break-glass expires automatically',()=>{const {service,time}=fixture(),session=service.requestBreakGlass(actors.responder,{ticket_ref:'INC-1',reason:'Synthetic outage requires temporary diagnostic access',capabilities:['tenant.inspect'],tenant_scopes:['tenant-horizonte'],ttl_seconds:60});service.approveBreakGlass(actors.approver1,session.session_id);time.advance(61);assert.throws(()=>service.authorizeBreakGlass(actors.responder,session.session_id,{tenant_id:'tenant-horizonte',capability:'tenant.inspect'}),{code:'BREAK_GLASS_EXPIRED'});});
test('revoked break-glass cannot be used',()=>{const {service}=fixture(),session=service.requestBreakGlass(actors.responder,{ticket_ref:'INC-1',reason:'Synthetic outage requires temporary diagnostic access',capabilities:['tenant.inspect'],tenant_scopes:['tenant-horizonte']});service.approveBreakGlass(actors.approver1,session.session_id);service.revokeBreakGlass(actors.admin,session.session_id);assert.throws(()=>service.authorizeBreakGlass(actors.responder,session.session_id,{tenant_id:'tenant-horizonte',capability:'tenant.inspect'}),{code:'BREAK_GLASS_EXPIRED'});});
test('audit chain verifies after normal actions',()=>{const {service}=issued();assert.equal(service.verifyAudit().status,'passed');});
test('audit verification detects tampering',()=>{const {service}=issued();service._auditEntries[0].action='tampered.action';const result=service.verifyAudit();assert.equal(result.status,'failed');assert.equal(result.first_failure_sequence,1);});
test('security rehearsal reports all checks',()=>{const {service}=configured(),result=service.runRehearsal(actors.admin,[()=>true,()=>1===1,()=>Boolean(service.verifyAudit())]);assert.equal(result.status,'passed');assert.equal(result.checks_passed,3);assert.equal(result.external_changes,false);});

function request(instance,url,method='GET'){return new Promise((resolve,reject)=>{const address=instance.address(),req=http.request({hostname:'127.0.0.1',port:address.port,path:url,method},res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body}));});req.on('error',reject);req.end();});}
async function startedServer(){const instance=server();await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve);});return instance;}
test('security console serves protected noindex HTML',async()=>{const instance=await startedServer();try{const response=await request(instance,'/');assert.equal(response.status,200);assert.match(response.body,/Identidad y control privilegiado/);assert.match(response.headers['content-security-policy'],/connect-src 'none'/);}finally{await new Promise(resolve=>instance.close(resolve));}});
test('security console supports HEAD',async()=>{const instance=await startedServer();try{const response=await request(instance,'/','HEAD');assert.equal(response.status,200);assert.equal(response.body,'');}finally{await new Promise(resolve=>instance.close(resolve));}});
test('security console rejects writes and traversal',async()=>{const instance=await startedServer();try{assert.equal((await request(instance,'/','POST')).status,405);assert.equal((await request(instance,'/%2e%2e/package.json')).status,404);}finally{await new Promise(resolve=>instance.close(resolve));}});
