'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const Ajv=require('ajv/dist/2020'),addFormats=require('ajv-formats');
const ROOT=path.resolve(__dirname,'../..'),ajv=new Ajv({allErrors:true,strict:false,validateFormats:true});addFormats(ajv);
const schemaNames=['recipe-version','design-system-version','version-compatibility','fleet-site-record','fleet-quality-snapshot','rollout-cohort','rollout-checkpoint','fleet-drift-report','fleet-rollback-record','version-deprecation-plan','fleet-portfolio-snapshot'];
const validators=Object.fromEntries(schemaNames.map(name=>[name,ajv.compile(JSON.parse(fs.readFileSync(path.join(ROOT,'contracts',`${name}.schema.json`),'utf8')))]));
const clone=value=>JSON.parse(JSON.stringify(value));
const canonical=value=>JSON.stringify(value,(_key,current)=>current&&typeof current==='object'&&!Array.isArray(current)?Object.fromEntries(Object.entries(current).sort(([a],[b])=>a.localeCompare(b))):current);
const sha=value=>crypto.createHash('sha256').update(typeof value==='string'?value:canonical(value)).digest('hex');
const fail=(code,message,details)=>Object.assign(new Error(message),{code,details});
function validate(name,value){const check=validators[name];if(!check(value))throw fail('SCHEMA_INVALID',`${name} invalid`,check.errors);return value;}
function semver(value){const match=/^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/.exec(value);if(!match)throw fail('SEMVER_INVALID',`Invalid semantic version: ${value}`);return match.slice(1).map(Number);}
function compareVersions(left,right){const a=semver(left),b=semver(right);for(let index=0;index<3;index++){if(a[index]!==b[index])return a[index]-b[index];}return 0;}
const inRange=(version,minimum,maximumExclusive)=>compareVersions(version,minimum)>=0&&compareVersions(version,maximumExclusive)<0;

function createFleetGovernance({now=()=>new Date()}={}){
  const recipeVersions=new Map(),designVersions=new Map(),compatibility=new Map(),sites=new Map(),quality=new Map(),cohorts=new Map(),checkpoints=new Map(),drifts=new Map(),rollbacks=new Map(),deprecations=new Map(),portfolios=new Map();let sequence=0;
  const stamp=()=>now().toISOString(),makeId=(prefix,salt='')=>`${prefix}-${sha(`${prefix}|${salt}|${sequence++}|${stamp()}`).slice(0,24)}`;
  function authorize(actor,tenantId,roles){if(!actor||!roles.includes(actor.role)||(actor.role!=='admin'&&actor.tenant_id!==tenantId))throw fail('ACCESS_DENIED','Actor cannot access this tenant');}
  function recipe(ref){const value=recipeVersions.get(ref);if(!value)throw fail('RECIPE_VERSION_NOT_FOUND','Recipe version not found');return value;}
  function design(ref){const value=designVersions.get(ref);if(!value)throw fail('DESIGN_VERSION_NOT_FOUND','Design version not found');return value;}
  function site(ref){const value=sites.get(ref);if(!value)throw fail('SITE_NOT_FOUND','Fleet site not found');return value;}
  function cohort(ref){const value=cohorts.get(ref);if(!value)throw fail('COHORT_NOT_FOUND','Rollout cohort not found');return value;}
  function uniqueVersion(collection,tenantId,assetId,version,idField){if([...collection.values()].some(item=>item.tenant_id===tenantId&&item[idField]===assetId&&item.version===version))throw fail('VERSION_EXISTS','Asset version already exists');}
  function registerRecipe(actor,input){authorize(actor,input.tenant_id,['operator','admin']);uniqueVersion(recipeVersions,input.tenant_id,input.recipe_id,input.version,'recipe_id');semver(input.version);semver(input.engine_range.minimum);semver(input.engine_range.maximum_exclusive);if(compareVersions(input.engine_range.minimum,input.engine_range.maximum_exclusive)>=0)throw fail('VERSION_RANGE_INVALID','Engine range must be increasing');for(const requirement of input.design_requirements){semver(requirement.minimum);semver(requirement.maximum_exclusive);if(compareVersions(requirement.minimum,requirement.maximum_exclusive)>=0)throw fail('VERSION_RANGE_INVALID','Design range must be increasing');}const time=stamp(),value={schema_version:'0.1.0',recipe_version_id:makeId('rv',`${input.recipe_id}|${input.version}`),tenant_id:input.tenant_id,recipe_id:input.recipe_id,version:input.version,archetype:input.archetype,status:'draft',engine_range:clone(input.engine_range),design_requirements:clone(input.design_requirements),source_proposal_refs:clone(input.source_proposal_refs||[]),artifact_digest:sha(input.artifact),auto_publish:false,created_by:actor.actor_id,approved_by:null,created_at:time,updated_at:time};validate('recipe-version',value);recipeVersions.set(value.recipe_version_id,value);return clone(value);}
  function registerDesign(actor,input){authorize(actor,input.tenant_id,['operator','admin']);uniqueVersion(designVersions,input.tenant_id,input.design_system_id,input.version,'design_system_id');semver(input.version);const time=stamp(),value={schema_version:'0.1.0',design_version_id:makeId('dsv',`${input.design_system_id}|${input.version}`),tenant_id:input.tenant_id,design_system_id:input.design_system_id,version:input.version,status:'draft',token_digest:sha(input.tokens),component_digest:sha(input.components),accessibility_baseline:input.accessibility_baseline,created_by:actor.actor_id,approved_by:null,created_at:time,updated_at:time};validate('design-system-version',value);designVersions.set(value.design_version_id,value);return clone(value);}
  function activateVersion(actor,type,ref){const value=type==='recipe'?recipe(ref):design(ref);authorize(actor,value.tenant_id,['operator','admin']);if(value.created_by===actor.actor_id)throw fail('INDEPENDENT_APPROVAL_REQUIRED','Version creator cannot approve it');if(value.status!=='draft')throw fail('VERSION_STATE_INVALID','Only a draft version can be activated');value.status='active';value.approved_by=actor.actor_id;value.updated_at=stamp();validate(type==='recipe'?'recipe-version':'design-system-version',value);return clone(value);}
  function evaluateCompatibility(actor,{tenant_id,recipe_version_ref,design_version_ref,engine_version}){authorize(actor,tenant_id,['operator','admin']);const recipeValue=recipe(recipe_version_ref),designValue=design(design_version_ref);if(recipeValue.tenant_id!==tenant_id||designValue.tenant_id!==tenant_id)throw fail('TENANT_MISMATCH','Versions belong to a different tenant');const reasons=[];if(recipeValue.status!=='active')reasons.push('recipe_not_active');if(designValue.status!=='active')reasons.push('design_not_active');if(!inRange(engine_version,recipeValue.engine_range.minimum,recipeValue.engine_range.maximum_exclusive))reasons.push('engine_out_of_range');const requirement=recipeValue.design_requirements.find(item=>item.design_system_id===designValue.design_system_id);if(!requirement)reasons.push('design_system_not_allowed');else if(!inRange(designValue.version,requirement.minimum,requirement.maximum_exclusive))reasons.push('design_version_out_of_range');const value={schema_version:'0.1.0',evaluation_id:makeId('compat',`${recipe_version_ref}|${design_version_ref}|${engine_version}`),tenant_id,recipe_version_ref,design_version_ref,engine_version,verdict:reasons.length?'incompatible':'compatible',reasons:reasons.length?reasons:['all_constraints_satisfied'],evaluated_at:stamp()};validate('version-compatibility',value);compatibility.set(value.evaluation_id,value);return clone(value);}
  function registerSite(actor,input){authorize(actor,input.tenant_id,['operator','admin']);if(sites.has(input.site_id))throw fail('SITE_EXISTS','Fleet site already exists');const check=evaluateCompatibility(actor,{tenant_id:input.tenant_id,recipe_version_ref:input.current_recipe_ref,design_version_ref:input.current_design_ref,engine_version:input.engine_version});if(check.verdict!=='compatible')throw fail('INCOMPATIBLE_VERSIONS','Site versions are incompatible',check.reasons);const value={schema_version:'0.1.0',tenant_id:input.tenant_id,site_id:input.site_id,archetype:input.archetype,cohort_label:input.cohort_label,current_recipe_ref:input.current_recipe_ref,current_design_ref:input.current_design_ref,engine_version:input.engine_version,target_recipe_ref:null,target_design_ref:null,status:'stable',release_digest:input.release_digest,updated_at:stamp()};validate('fleet-site-record',value);sites.set(value.site_id,value);return clone(value);}
  function scoreSite(actor,{tenant_id,site_id,dimensions,hard_gates,passing_threshold=85}){authorize(actor,tenant_id,['operator','admin']);const fleetSite=site(site_id);if(fleetSite.tenant_id!==tenant_id)throw fail('TENANT_MISMATCH','Site belongs to a different tenant');const keys=['truth','visual','accessibility','performance','conversion'];if(keys.some(key=>!Number.isInteger(dimensions[key])||dimensions[key]<0||dimensions[key]>100))throw fail('QUALITY_DIMENSION_INVALID','Quality dimensions must be integers from 0 to 100');const overall=Math.round(dimensions.truth*.25+dimensions.visual*.2+dimensions.accessibility*.2+dimensions.performance*.2+dimensions.conversion*.15),hardPass=Object.values(hard_gates).every(Boolean),status=!hardPass||overall<passing_threshold-5?'failing':overall<passing_threshold?'watch':'passing',value={schema_version:'0.1.0',snapshot_id:makeId('fqs',site_id),tenant_id,site_id,recipe_version_ref:fleetSite.current_recipe_ref,design_version_ref:fleetSite.current_design_ref,dimensions:clone(dimensions),hard_gates:clone(hard_gates),overall_score:overall,status,generated_at:stamp()};validate('fleet-quality-snapshot',value);quality.set(value.snapshot_id,value);return clone(value);}
  function createCohort(actor,input){authorize(actor,input.tenant_id,['operator','admin']);if(new Set(input.site_ids).size!==input.site_ids.length)throw fail('DUPLICATE_SITE','Cohort site list must be unique');if(!input.steps_percent.length||input.steps_percent.at(-1)!==100||input.steps_percent.some((value,index)=>index&&value<=input.steps_percent[index-1]))throw fail('ROLLOUT_STEPS_INVALID','Rollout steps must be strictly increasing and end at 100');for(const siteId of input.site_ids){const item=site(siteId);if(item.tenant_id!==input.tenant_id)throw fail('TENANT_MISMATCH','Cohort contains another tenant');const check=evaluateCompatibility(actor,{tenant_id:input.tenant_id,recipe_version_ref:input.target_recipe_ref,design_version_ref:input.target_design_ref,engine_version:item.engine_version});if(check.verdict!=='compatible')throw fail('INCOMPATIBLE_TARGET','Target versions are incompatible',check.reasons);}const time=stamp(),value={schema_version:'0.1.0',cohort_id:makeId('cohort',input.name),tenant_id:input.tenant_id,name:input.name,site_ids:clone(input.site_ids),target_recipe_ref:input.target_recipe_ref,target_design_ref:input.target_design_ref,steps_percent:clone(input.steps_percent),quality_threshold:input.quality_threshold,rollback_threshold:input.rollback_threshold,max_incidents:input.max_incidents,status:'draft',current_step:0,created_by:actor.actor_id,approved_by:null,created_at:time,updated_at:time};validate('rollout-cohort',value);cohorts.set(value.cohort_id,value);return clone(value);}
  function approveCohort(actor,cohortId){const value=cohort(cohortId);authorize(actor,value.tenant_id,['operator','admin']);if(value.created_by===actor.actor_id)throw fail('INDEPENDENT_APPROVAL_REQUIRED','Cohort creator cannot approve it');if(value.status!=='draft')throw fail('COHORT_STATE_INVALID','Only draft cohort can be approved');value.status='approved';value.approved_by=actor.actor_id;value.updated_at=stamp();validate('rollout-cohort',value);return clone(value);}
  function startCohort(actor,cohortId){const value=cohort(cohortId);authorize(actor,value.tenant_id,['operator','admin']);if(value.status!=='approved')throw fail('COHORT_NOT_APPROVED','Approved cohort required');value.status='running';value.updated_at=stamp();for(const siteId of value.site_ids){const item=site(siteId);item.target_recipe_ref=value.target_recipe_ref;item.target_design_ref=value.target_design_ref;item.status='scheduled';item.updated_at=stamp();validate('fleet-site-record',item);}return clone(value);}
  function evaluateCheckpoint(actor,{cohort_ref,step_percent,observed_sites,average_quality_score,incident_count,critical_drift_count}){const rollout=cohort(cohort_ref);authorize(actor,rollout.tenant_id,['operator','admin']);if(rollout.status!=='running')throw fail('COHORT_NOT_RUNNING','Running cohort required');const expected=rollout.steps_percent.find(step=>step>rollout.current_step);if(step_percent!==expected)throw fail('STEP_OUT_OF_ORDER','Checkpoint must evaluate the next configured step');let verdict='pass',reason='La cohorte supera calidad y guardrails para continuar.';if(incident_count>rollout.max_incidents||critical_drift_count>0||average_quality_score<rollout.rollback_threshold){verdict='rollback';reason='La cohorte cruza un umbral de rollback o presenta deriva crítica.';}else if(average_quality_score<rollout.quality_threshold){verdict='hold';reason='La calidad está bajo el umbral de avance; la cohorte queda pausada.';}const value={schema_version:'0.1.0',checkpoint_id:makeId('rcp',`${cohort_ref}|${step_percent}`),tenant_id:rollout.tenant_id,cohort_ref,step_percent,observed_sites,average_quality_score,incident_count,critical_drift_count,verdict,reason,evaluated_by:actor.actor_id,evaluated_at:stamp()};validate('rollout-checkpoint',value);checkpoints.set(value.checkpoint_id,value);if(verdict==='pass'){rollout.current_step=step_percent;rollout.status=step_percent===100?'completed':'running';for(const siteId of rollout.site_ids){const item=site(siteId);item.status=step_percent===100?'stable':'canary';if(step_percent===100){item.current_recipe_ref=rollout.target_recipe_ref;item.current_design_ref=rollout.target_design_ref;item.target_recipe_ref=null;item.target_design_ref=null;}item.updated_at=stamp();validate('fleet-site-record',item);}}else{rollout.status='paused';for(const siteId of rollout.site_ids){const item=site(siteId);item.status='paused';item.updated_at=stamp();validate('fleet-site-record',item);}}rollout.updated_at=stamp();validate('rollout-cohort',rollout);return clone(value);}
  function detectDrift(actor,{tenant_id,site_id,asset_type,expected_digest,observed_digest}){authorize(actor,tenant_id,['service','operator','admin']);const item=site(site_id);if(item.tenant_id!==tenant_id)throw fail('TENANT_MISMATCH','Site belongs to a different tenant');const changed=expected_digest!==observed_digest;let severity='none',recommended_action='no_action';if(changed&&['recipe','design'].includes(asset_type)){severity='critical';recommended_action='rollback';}else if(changed&&asset_type==='engine'){severity='high';recommended_action='pause';}else if(changed){severity='medium';recommended_action='reconcile';}const value={schema_version:'0.1.0',drift_id:makeId('drift',`${site_id}|${asset_type}`),tenant_id,site_id,asset_type,expected_digest,observed_digest,severity,recommended_action,status:changed?'open':'resolved',detected_at:stamp(),resolved_at:changed?null:stamp()};validate('fleet-drift-report',value);drifts.set(value.drift_id,value);return clone(value);}
  function planRollback(actor,{cohort_ref,trigger_type,trigger_ref}){const rollout=cohort(cohort_ref);authorize(actor,rollout.tenant_id,['operator','admin']);if(!['paused','running'].includes(rollout.status))throw fail('ROLLBACK_STATE_INVALID','Rollback requires a running or paused cohort');if(trigger_type==='checkpoint'){const checkpoint=checkpoints.get(trigger_ref);if(!checkpoint||checkpoint.cohort_ref!==cohort_ref||checkpoint.verdict!=='rollback')throw fail('ROLLBACK_TRIGGER_INVALID','Checkpoint must require rollback');}if(trigger_type==='drift'){const drift=drifts.get(trigger_ref);if(!drift||drift.tenant_id!==rollout.tenant_id||drift.recommended_action!=='rollback')throw fail('ROLLBACK_TRIGGER_INVALID','Drift must require rollback');}const fromRecipe=rollout.target_recipe_ref,toRecipe=site(rollout.site_ids[0]).current_recipe_ref,time=stamp(),value={schema_version:'0.1.0',rollback_id:makeId('frb',cohort_ref),tenant_id:rollout.tenant_id,cohort_ref,site_ids:clone(rollout.site_ids),from_recipe_ref:fromRecipe,to_recipe_ref:toRecipe,trigger_type,trigger_ref,status:'planned',external_changes:false,planned_by:actor.actor_id,executed_by:null,planned_at:time,executed_at:null};validate('fleet-rollback-record',value);rollbacks.set(value.rollback_id,value);return clone(value);}
  function executeRollback(actor,rollbackId){const value=rollbacks.get(rollbackId);if(!value)throw fail('ROLLBACK_NOT_FOUND','Rollback record not found');authorize(actor,value.tenant_id,['operator','admin']);if(actor.actor_id===value.planned_by)throw fail('INDEPENDENT_EXECUTION_REQUIRED','Rollback planner cannot execute it');if(value.status!=='planned')throw fail('ROLLBACK_STATE_INVALID','Only planned rollback can execute');const rollout=cohort(value.cohort_ref);value.status='executed';value.executed_by=actor.actor_id;value.executed_at=stamp();rollout.status='rolled_back';rollout.updated_at=stamp();for(const siteId of value.site_ids){const item=site(siteId);item.target_recipe_ref=null;item.target_design_ref=null;item.status='rolled_back';item.updated_at=stamp();validate('fleet-site-record',item);}validate('fleet-rollback-record',value);validate('rollout-cohort',rollout);return clone(value);}
  function createDeprecation(actor,input){authorize(actor,input.tenant_id,['operator','admin']);if(input.deprecated_version_ref===input.successor_version_ref)throw fail('SUCCESSOR_INVALID','Successor must differ from deprecated version');for(const siteId of input.affected_site_ids)if(site(siteId).tenant_id!==input.tenant_id)throw fail('TENANT_MISMATCH','Deprecation contains another tenant');const time=stamp(),value={schema_version:'0.1.0',plan_id:makeId('vdp',input.deprecated_version_ref),tenant_id:input.tenant_id,asset_type:input.asset_type,deprecated_version_ref:input.deprecated_version_ref,successor_version_ref:input.successor_version_ref,affected_site_ids:clone(input.affected_site_ids),deadline:new Date(input.deadline).toISOString(),blockers:clone(input.blockers||[]),status:'draft',created_by:actor.actor_id,approved_by:null,created_at:time,updated_at:time};validate('version-deprecation-plan',value);deprecations.set(value.plan_id,value);return clone(value);}
  function approveDeprecation(actor,planId){const value=deprecations.get(planId);if(!value)throw fail('DEPRECATION_NOT_FOUND','Deprecation plan not found');authorize(actor,value.tenant_id,['operator','admin']);if(actor.actor_id===value.created_by)throw fail('INDEPENDENT_APPROVAL_REQUIRED','Plan creator cannot approve it');if(value.status!=='draft')throw fail('DEPRECATION_STATE_INVALID','Only draft plan can be approved');value.status='approved';value.approved_by=actor.actor_id;value.updated_at=stamp();validate('version-deprecation-plan',value);return clone(value);}
  function portfolioSnapshot(actor,tenantId){authorize(actor,tenantId,['owner','operator','admin']);const ownSites=[...sites.values()].filter(item=>item.tenant_id===tenantId),latestQuality=new Map();for(const item of quality.values())if(item.tenant_id===tenantId)latestQuality.set(item.site_id,item);const count=(items,key)=>items.reduce((result,item)=>(result[item[key]]=(result[item[key]]||0)+1,result),{}),value={schema_version:'0.1.0',snapshot_id:makeId('fps',tenantId),tenant_id:tenantId,total_sites:ownSites.length,site_status_counts:count(ownSites,'status'),quality_status_counts:count([...latestQuality.values()],'status'),recipe_distribution:count(ownSites,'current_recipe_ref'),design_distribution:count(ownSites,'current_design_ref'),active_rollouts:[...cohorts.values()].filter(item=>item.tenant_id===tenantId&&['approved','running','paused'].includes(item.status)).length,open_critical_drift:[...drifts.values()].filter(item=>item.tenant_id===tenantId&&item.status==='open'&&item.severity==='critical').length,pending_deprecations:[...deprecations.values()].filter(item=>item.tenant_id===tenantId&&!['completed','cancelled'].includes(item.status)).length,generated_at:stamp()};validate('fleet-portfolio-snapshot',value);portfolios.set(value.snapshot_id,value);return clone(value);}
  function read(actor,tenantId){authorize(actor,tenantId,['owner','operator','admin']);const own=item=>item.tenant_id===tenantId;return {recipe_versions:[...recipeVersions.values()].filter(own).map(clone),design_versions:[...designVersions.values()].filter(own).map(clone),compatibility:[...compatibility.values()].filter(own).map(clone),sites:[...sites.values()].filter(own).map(clone),quality:[...quality.values()].filter(own).map(clone),cohorts:[...cohorts.values()].filter(own).map(clone),checkpoints:[...checkpoints.values()].filter(own).map(clone),drifts:[...drifts.values()].filter(own).map(clone),rollbacks:[...rollbacks.values()].filter(own).map(clone),deprecations:[...deprecations.values()].filter(own).map(clone),portfolios:[...portfolios.values()].filter(own).map(clone)};}
  return {registerRecipe,registerDesign,activateVersion,evaluateCompatibility,registerSite,scoreSite,createCohort,approveCohort,startCohort,evaluateCheckpoint,detectDrift,planRollback,executeRollback,createDeprecation,approveDeprecation,portfolioSnapshot,read,_state:{recipeVersions,designVersions,compatibility,sites,quality,cohorts,checkpoints,drifts,rollbacks,deprecations,portfolios}};
}
module.exports={createFleetGovernance,compareVersions,inRange,sha};
