'use strict';
const { validate } = require('../site-engine/index.cjs');
const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const created_at = '2026-09-30T23:00:00Z';
const base = profile => ({schema_version:'0.1.0',profile_id:profile.id,archetype:profile.archetype,synthetic:true,created_at,action:{label:'Continuar con un asesor',enabled:false,reason:'Contacto desactivado hasta incorporar un negocio autorizado.'}});
function buildExperience(profile,catalog){
 const refs=catalog.items.map(item=>item.id);let model;
 if(profile.archetype==='catalogo-amplio')model={...base(profile),module_type:'catalog_search',eyebrow:'Exploración guiada',headline:'Empieza por lo que sí cambia tu decisión.',description:'Una búsqueda útil reduce opciones por intención, zona, formato y presupuesto antes de mostrar fichas.',payload:{filters:[{key:'operacion',label:'Quiero',options:['Comprar','Alquilar']},{key:'zona',label:'Zona',options:['Miraflores','Barranco','San Isidro']},{key:'formato',label:'Tipo de espacio',options:['Departamento','Casa','Flexible']},{key:'presupuesto',label:'Presupuesto',options:['Hasta US$ 250k','US$ 250k–450k','Más de US$ 450k']}],result_refs:refs}};
 else if(profile.archetype==='desarrollador-proyectos')model={...base(profile),module_type:'project_timeline',eyebrow:'Avance del proyecto',headline:'Entiende cada etapa antes de separar.',description:'La presentación ordena el recorrido del proyecto y marca cada dato que todavía necesita verificación del desarrollador.',payload:{stages:[{order:1,label:'Concepto y ubicación',status:'reference'},{order:2,label:'Permisos y documentación',status:'requires_verification'},{order:3,label:'Construcción',status:'requires_verification'},{order:4,label:'Entrega y postventa',status:'requires_verification'}],result_refs:refs}};
 else if(profile.archetype==='asesor-boutique')model={...base(profile),module_type:'advisory_path',eyebrow:'Diagnóstico inicial',headline:'Primero entendemos tu momento.',description:'Tres preguntas preparan una conversación relevante sin fingir recomendaciones automáticas.',payload:{questions:[{key:'objetivo',label:'¿Qué quieres resolver?',options:['Comprar','Vender','Alquilar']},{key:'prioridad',label:'¿Qué no quieres negociar?',options:['Ubicación','Tiempo','Presupuesto']},{key:'etapa',label:'¿En qué etapa estás?',options:['Explorando','Comparando','Listo para actuar']}]} };
 else if(profile.archetype==='proyectos-lotes')model={...base(profile),module_type:'lot_comparison',eyebrow:'Comparación responsable',headline:'Compara el terreno, no solo la promesa.',description:'El módulo hace visibles los criterios que deben verificarse antes de evaluar un proyecto de lotes.',payload:{criteria:[{key:'situacion_legal',label:'Situación legal',options:['Por verificar','Documentación revisada']},{key:'servicios',label:'Servicios',options:['Proyectados','Habilitados']},{key:'etapa',label:'Etapa del proyecto',options:['Inicial','Obras','Entrega']},{key:'acceso',label:'Acceso',options:['Por verificar','Confirmado']}],result_refs:refs}};
 else if(profile.archetype==='tasacion-propietarios')model={...base(profile),module_type:'valuation_brief',eyebrow:'Brief de valoración',headline:'Una estimación seria empieza con contexto.',description:'El propietario prepara la información mínima para una evaluación humana, sin prometer una tasación automática.',payload:{questions:[{key:'objetivo',label:'Objetivo del propietario',options:['Vender','Alquilar','Evaluar opciones']},{key:'tipo_inmueble',label:'Tipo de inmueble',options:['Departamento','Casa','Terreno']},{key:'estado',label:'Estado actual',options:['Listo','Necesita mejoras','Ocupado']},{key:'plazo',label:'Plazo deseado',options:['0–3 meses','3–6 meses','Sin fecha']}]} };
 else throw Object.assign(new Error('Unsupported real-estate archetype'),{code:'ARCHETYPE_UNSUPPORTED'});
 validate('real-estate-experience',model);return model;
}
function controls(items){return `<div class="experience-controls">${items.map(item=>`<div><span>${esc(item.label)}</span><div>${item.options.map((option,index)=>`<button type="button" aria-pressed="false" disabled>${esc(option)}${index===0?'':''}</button>`).join('')}</div></div>`).join('')}</div>`;}
function renderExperience(model,catalog){validate('real-estate-experience',model);const known=new Set(catalog.items.map(item=>item.id));for(const ref of model.payload.result_refs||[])if(!known.has(ref))throw Object.assign(new Error('Experience references unknown catalog item'),{code:'CATALOG_REFERENCE_UNKNOWN'});let body='';
 if(model.module_type==='catalog_search')body=controls(model.payload.filters)+`<p class="experience-result">${model.payload.result_refs.length} referencias sintéticas disponibles</p>`;
 else if(model.module_type==='project_timeline')body=`<ol class="experience-timeline">${model.payload.stages.map(stage=>`<li><span>${String(stage.order).padStart(2,'0')}</span><b>${esc(stage.label)}</b><em>${stage.status==='reference'?'Referencia visual':'Requiere verificación'}</em></li>`).join('')}</ol>`;
 else if(model.module_type==='lot_comparison')body=controls(model.payload.criteria);
 else body=controls(model.payload.questions);
 return `<section class="experience-module" data-module="${esc(model.module_type)}"><div class="experience-heading"><div><p class="eyebrow">${esc(model.eyebrow)}</p><h2>${esc(model.headline)}</h2></div><p>${esc(model.description)}</p></div>${body}<div class="experience-action"><span>${esc(model.action.label)}</span><small>${esc(model.action.reason)}</small></div></section>`;
}
module.exports={buildExperience,renderExperience};
