'use strict';
const crypto=require('node:crypto');const {validate}=require('../site-engine/index.cjs');
const clone=v=>structuredClone(v),sha=v=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex'),id=p=>`${p}-${crypto.randomBytes(12).toString('hex')}`,safe=(v,label='identifier')=>{if(!/^[a-z0-9][a-z0-9-]{2,79}$/.test(String(v||'')))throw Object.assign(new Error(`Invalid ${label}`),{code:'INVALID_IDENTIFIER'});return String(v);};
const actionMatrix={owner:new Set(['dashboard.read','contact.reveal','preferences.write','privacy.submit','business.change.submit','session.revoke']),operator:new Set(['dashboard.read','contact.reveal','privacy.process','business.change.review','session.revoke']),admin:new Set(['dashboard.read','contact.reveal','preferences.write','privacy.submit','privacy.process','business.change.submit','business.change.review','session.revoke'])};
const privacyTransitions={submitted:new Set(['identity_pending','rejected']),identity_pending:new Set(['verified','rejected']),verified:new Set(['processing','rejected']),processing:new Set(['completed','rejected']),completed:new Set(),rejected:new Set()};
function createLocalIdentityProvider(entries){const assertions=new Map(Object.entries(entries||{}).map(([key,value])=>[key,clone(value)]));return {verify(assertion){const result=assertions.get(String(assertion||''));if(!result||result.status!=='active')throw Object.assign(new Error('Identity rejected'),{code:'IDENTITY_REJECTED'});if(!['owner','operator','admin'].includes(result.role)||!Array.isArray(result.tenant_ids)||!result.tenant_ids.length)throw Object.assign(new Error('Identity assertion invalid'),{code:'IDENTITY_INVALID'});return clone(result);}};}
function createOwnerPortal({identityProvider,vault=null,auditKey,now=()=>new Date(),absoluteMinutes=480,idleMinutes=30}={}){
 if(!identityProvider?.verify)throw Object.assign(new Error('Identity provider required'),{code:'IDENTITY_PROVIDER_REQUIRED'});if(!Buffer.isBuffer(auditKey)||auditKey.length<32)throw Object.assign(new Error('Audit key must be at least 32 bytes'),{code:'AUDIT_KEY_INVALID'});
 const sessions=new Map(),preferences=new Map(),privacyRequests=new Map(),changes=new Map(),auditRows=[];
 const currentIso=()=>now().toISOString(),plus=(iso,min)=>new Date(Date.parse(iso)+min*60000).toISOString();
 function audit(session,action,resourceRef,outcome='success',occurredAt=currentIso()){const previous_hash=auditRows.length?auditRows.at(-1).event_hash:null,base={schema_version:'0.1.0',sequence:auditRows.length+1,event_id:id('paudit'),session_ref:session?.session_id||null,principal_id:safe(session?.principal_id||'unknown-principal','principal'),tenant_id:safe(session?.tenant_id||'unknown-tenant','tenant'),action,resource_ref:String(resourceRef).toLowerCase().replace(/[^a-z0-9:_-]/g,'-').slice(0,160),outcome,occurred_at:occurredAt,previous_hash},event_hash=sha(base),signature=crypto.createHmac('sha256',auditKey).update(event_hash).digest('hex'),row={...base,event_hash,signature};validate('portal-audit-event',row);auditRows.push(row);return clone(row);}
 function startSession(assertion,tenantId){const principal=identityProvider.verify(assertion),tenant=safe(tenantId,'tenant');if(!principal.tenant_ids.includes(tenant))throw Object.assign(new Error('Tenant membership rejected'),{code:'TENANT_ACCESS_DENIED'});const created=currentIso(),csrf=crypto.randomBytes(32).toString('hex'),session={schema_version:'0.1.0',session_id:id('session'),principal_id:safe(principal.principal_id,'principal'),tenant_id:tenant,role:principal.role,assurance:principal.assurance||'aal1',issued_at:created,expires_at:plus(created,absoluteMinutes),idle_expires_at:plus(created,idleMinutes),last_seen_at:created,reauthenticated_at:principal.assurance==='aal2'?created:null,csrf_sha256:sha(csrf),status:'active'};validate('portal-session',session);sessions.set(session.session_id,session);audit(session,'session.created',session.session_id,'success',created);return {session:clone(session),csrf_token:csrf};}
 function denied(session,resource){audit(session,'access.denied',resource,'denied');throw Object.assign(new Error('Access denied'),{code:'ACCESS_DENIED'});}
 function authorize(sessionId,csrfToken,action,tenantId,{aal2=false,recent=false}={}){const session=sessions.get(sessionId);if(!session)throw Object.assign(new Error('Session not found'),{code:'SESSION_INVALID'});const stamp=Date.parse(currentIso());if(session.status!=='active'||stamp>=Date.parse(session.expires_at)||stamp>=Date.parse(session.idle_expires_at)){session.status='expired';validate('portal-session',session);throw Object.assign(new Error('Session expired'),{code:'SESSION_EXPIRED'});}const supplied=Buffer.from(sha(String(csrfToken||'')),'hex'),expected=Buffer.from(session.csrf_sha256,'hex');if(supplied.length!==expected.length||!crypto.timingSafeEqual(supplied,expected))return denied(session,`csrf:${action}`);if(session.tenant_id!==tenantId||!actionMatrix[session.role]?.has(action))return denied(session,`${action}:${tenantId}`);if(aal2&&session.assurance!=='aal2')throw Object.assign(new Error('Step-up authentication required'),{code:'STEP_UP_REQUIRED'});if(recent&&(!session.reauthenticated_at||stamp-Date.parse(session.reauthenticated_at)>5*60000))throw Object.assign(new Error('Recent authentication required'),{code:'RECENT_AUTH_REQUIRED'});session.last_seen_at=new Date(stamp).toISOString();session.idle_expires_at=new Date(Math.min(stamp+idleMinutes*60000,Date.parse(session.expires_at))).toISOString();validate('portal-session',session);return session;}
 function reauthenticate(sessionId,csrfToken,assertion){const existing=sessions.get(sessionId);if(!existing)throw Object.assign(new Error('Session not found'),{code:'SESSION_INVALID'});authorize(sessionId,csrfToken,'dashboard.read',existing.tenant_id);const principal=identityProvider.verify(assertion);if(principal.principal_id!==existing.principal_id||principal.assurance!=='aal2'||!principal.tenant_ids.includes(existing.tenant_id))return denied(existing,'session:reauthenticate');existing.assurance='aal2';existing.reauthenticated_at=currentIso();validate('portal-session',existing);audit(existing,'session.reauthenticated',existing.session_id);return clone(existing);}
 function dashboard(sessionId,csrfToken){const existing=sessions.get(sessionId),session=authorize(sessionId,csrfToken,'dashboard.read',existing?.tenant_id);audit(session,'dashboard.read',`tenant:${session.tenant_id}`);return {tenant_id:session.tenant_id,principal_id:session.principal_id,role:session.role,capabilities:[...actionMatrix[session.role]].sort(),preferences:preferences.has(`${session.tenant_id}:${session.principal_id}`),privacy_requests:[...privacyRequests.values()].filter(x=>x.tenant_id===session.tenant_id).length,business_changes:[...changes.values()].filter(x=>x.tenant_id===session.tenant_id).length};}
 function revealContact(sessionId,csrfToken,recordId){const existing=sessions.get(sessionId),session=authorize(sessionId,csrfToken,'contact.reveal',existing?.tenant_id,{aal2:true,recent:true});if(!vault)throw Object.assign(new Error('Private vault required'),{code:'VAULT_REQUIRED'});const result=vault.getJson({actor_id:session.principal_id,role:session.role,tenant_id:session.tenant_id},recordId);if(result.envelope.record_type!=='interaction_submission')throw Object.assign(new Error('Record type cannot be revealed'),{code:'RECORD_TYPE_BLOCKED'});audit(session,'contact.revealed',`record:${recordId}`);return {record_id:recordId,purpose:result.payload.purpose,contact:clone(result.payload.contact),message:result.payload.message,property_ref:result.payload.property_ref};}
 function updatePreferences(sessionId,csrfToken,input,expectedVersion=0){const existing=sessions.get(sessionId),session=authorize(sessionId,csrfToken,'preferences.write',existing?.tenant_id),allowed=new Set(['locale','timezone','notifications','digest']);if(!input||Object.keys(input).some(key=>!allowed.has(key)))throw Object.assign(new Error('Unexpected preference field'),{code:'PREFERENCES_INVALID'});const key=`${session.tenant_id}:${session.principal_id}`,prior=preferences.get(key);if((prior?.version||0)!==expectedVersion)throw Object.assign(new Error('Preference version conflict'),{code:'VERSION_CONFLICT'});const value={schema_version:'0.1.0',preference_id:prior?.preference_id||id('pref'),tenant_id:session.tenant_id,principal_id:session.principal_id,locale:input.locale,timezone:input.timezone,notifications:clone(input.notifications),digest:input.digest,version:(prior?.version||0)+1,updated_at:currentIso()};validate('owner-preferences',value);preferences.set(key,value);audit(session,'preferences.updated',value.preference_id);return clone(value);}
 function submitPrivacy(sessionId,csrfToken,input){const existing=sessions.get(sessionId),session=authorize(sessionId,csrfToken,'privacy.submit',existing?.tenant_id),created=currentIso(),request={schema_version:'0.1.0',request_id:id('privacy'),tenant_id:session.tenant_id,principal_id:session.principal_id,type:input?.type,scope:input?.scope,subject_ref:String(input?.subject_ref||''),status:'submitted',verification_ref:null,rejection_reason:null,due_at:plus(created,30*24*60),created_at:created,updated_at:created};validate('privacy-request',request);privacyRequests.set(request.request_id,request);audit(session,'privacy.submitted',request.request_id);return clone(request);}
 function transitionPrivacy(sessionId,csrfToken,requestId,to,{verification_ref=null,rejection_reason=null}={}){const existing=sessions.get(sessionId),request=privacyRequests.get(requestId);if(!request)throw Object.assign(new Error('Privacy request not found'),{code:'REQUEST_NOT_FOUND'});const session=authorize(sessionId,csrfToken,'privacy.process',request.tenant_id);if(!privacyTransitions[request.status]?.has(to))throw Object.assign(new Error('Invalid privacy transition'),{code:'INVALID_TRANSITION'});request.status=to;request.updated_at=currentIso();if(verification_ref)request.verification_ref=String(verification_ref);if(to==='rejected')request.rejection_reason=String(rejection_reason||'');validate('privacy-request',request);audit(session,'privacy.transitioned',request.request_id);return clone(request);}
 function submitBusinessChange(sessionId,csrfToken,input){const existing=sessions.get(sessionId),session=authorize(sessionId,csrfToken,'business.change.submit',existing?.tenant_id),created=currentIso(),change={schema_version:'0.1.0',change_id:id('change'),tenant_id:session.tenant_id,business_id:safe(input?.business_id,'business'),requested_by:session.principal_id,base_truth_sha256:String(input?.base_truth_sha256||''),operations:clone(input?.operations),reason:String(input?.reason||'').trim(),status:'submitted',reviewer_id:null,review_reason:null,created_at:created,updated_at:created};validate('business-change-request',change);changes.set(change.change_id,change);audit(session,'business_change.submitted',change.change_id);return clone(change);}
 function reviewBusinessChange(sessionId,csrfToken,changeId,decision,reason){const existing=sessions.get(sessionId),change=changes.get(changeId);if(!change)throw Object.assign(new Error('Business change not found'),{code:'CHANGE_NOT_FOUND'});const session=authorize(sessionId,csrfToken,'business.change.review',change.tenant_id);if(change.status!=='submitted'||!['approved','rejected'].includes(decision))throw Object.assign(new Error('Invalid business change review'),{code:'INVALID_REVIEW'});change.status=decision;change.reviewer_id=session.principal_id;change.review_reason=String(reason||'').trim();change.updated_at=currentIso();validate('business-change-request',change);audit(session,'business_change.reviewed',change.change_id);return clone(change);}
 function revoke(sessionId,csrfToken){const existing=sessions.get(sessionId),session=authorize(sessionId,csrfToken,'session.revoke',existing?.tenant_id);session.status='revoked';validate('portal-session',session);audit(session,'session.revoked',session.session_id);return clone(session);}
 function verifyAudit(){let previous=null;for(let index=0;index<auditRows.length;index++){const row=auditRows[index],{event_hash,signature,...base}=row;if(row.sequence!==index+1||row.previous_hash!==previous||sha(base)!==event_hash||crypto.createHmac('sha256',auditKey).update(event_hash).digest('hex')!==signature)return {valid:false,entries:auditRows.length,failed_sequence:index+1};validate('portal-audit-event',row);previous=event_hash;}return {valid:true,entries:auditRows.length,head:previous};}
 return {startSession,reauthenticate,dashboard,revealContact,updatePreferences,submitPrivacy,transitionPrivacy,submitBusinessChange,reviewBusinessChange,revoke,verifyAudit,_state:{sessions,preferences,privacyRequests,changes,auditRows}};
}
module.exports={createOwnerPortal,createLocalIdentityProvider,actionMatrix,privacyTransitions};
