'use strict';
const crypto=require('node:crypto');const {validate}=require('../site-engine/index.cjs');
const clone=value=>structuredClone(value),hash=value=>crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex'),id=prefix=>`${prefix}-${crypto.randomBytes(12).toString('hex')}`;
const fail=(code,message)=>{throw Object.assign(new Error(message),{code});};
const permissions={owner:new Set(['health.read','alerts.read','usage.read']),operator:new Set(['telemetry.ingest','slo.evaluate','usage.evaluate','health.read','alerts.read','alert.ack','incident.open','incident.update','usage.read']),admin:new Set(['telemetry.ingest','slo.evaluate','usage.evaluate','health.read','alerts.read','alert.ack','alert.resolve','incident.open','incident.update','usage.read']),system:new Set(['telemetry.ingest','slo.evaluate','usage.evaluate','health.read','alerts.read','usage.read'])};
function authorize(actor,action,tenant){if(!actor||!permissions[actor.role]?.has(action)||(actor.tenant_id&&actor.tenant_id!==tenant))fail('ACCESS_DENIED','Access denied');}
const percentile95=values=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.max(0,Math.ceil(sorted.length*.95)-1)];};
function createUnconfiguredNotificationAdapter(){return {name:'unconfigured',deliver(){fail('NOTIFICATION_ADAPTER_UNCONFIGURED','Notification adapter is not configured');}};}
function createLocalNotificationAdapter(){const deliveries=[];return {name:'local_sandbox',deliver(alert){if(!alert?.synthetic)fail('NOTIFICATION_REJECTED','Local adapter accepts synthetic alerts only');const result={alert_id:alert.alert_id,status:'simulated',external_messages:0};deliveries.push(result);return clone(result);},deliveries};}
function createObservabilityService({sloPolicies=[],guardrailPolicies=[],notificationAdapter=createUnconfiguredNotificationAdapter(),now=()=>new Date()}={}){
 const slos=new Map(),guardrails=new Map(),events=[],evaluations=new Map(),usageSnapshots=new Map(),alerts=new Map(),incidents=new Map();for(const policy of sloPolicies){validate('slo-policy',policy);slos.set(policy.slo_id,clone(policy));}for(const policy of guardrailPolicies){validate('tenant-guardrail-policy',policy);guardrails.set(policy.tenant_id,clone(policy));}const stamp=()=>now().toISOString();
 function ingest(actor,input){authorize(actor,'telemetry.ingest',input.tenant_id);const allowed=new Set(['tenant_id','service','release_ref','type','outcome','measurements','occurred_at']),measurementAllowed=new Set(['count','duration_ms','bytes']);if(Object.keys(input).some(key=>!allowed.has(key))||Object.keys(input.measurements||{}).some(key=>!measurementAllowed.has(key)))fail('SCHEMA_INVALID','Telemetry input contains unsupported fields');const event={schema_version:'0.1.0',event_id:id('telemetry'),tenant_id:input.tenant_id,service:input.service,release_ref:input.release_ref??null,type:input.type,outcome:input.outcome,measurements:{count:input.measurements?.count??1,duration_ms:input.measurements?.duration_ms??null,bytes:input.measurements?.bytes??null},occurred_at:input.occurred_at||stamp()};validate('telemetry-event',event);events.push(event);return clone(event);}
 function upsertAlert({tenant_id,service,release_ref=null,kind,severity,summary,source_ref}){const key=hash(`${tenant_id}|${service}|${kind}|${release_ref||'none'}`),existing=alerts.get(key),time=stamp();if(existing&&existing.status!=='resolved'){existing.occurrences++;existing.last_seen_at=time;existing.source_ref=source_ref;validate('operational-alert',existing);return clone(existing);}const alert={schema_version:'0.1.0',alert_id:id('alert'),dedupe_key:key,tenant_id,service,release_ref,kind,severity,status:'open',summary,source_ref,occurrences:1,first_seen_at:time,last_seen_at:time};validate('operational-alert',alert);alerts.set(key,alert);return clone(alert);}
 function evaluateSlo(actor,{tenant_id,slo_id,window_start,window_end}){authorize(actor,'slo.evaluate',tenant_id);const policy=slos.get(slo_id);if(!policy||policy.status!=='active')fail('SLO_UNAVAILABLE','Active SLO required');const start=Date.parse(window_start),end=Date.parse(window_end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)fail('WINDOW_INVALID','Invalid evaluation window');const selected=events.filter(x=>x.tenant_id===tenant_id&&x.service===policy.service&&Date.parse(x.occurred_at)>=start&&Date.parse(x.occurred_at)<end),sample=selected.reduce((sum,x)=>sum+x.measurements.count,0),failures=selected.filter(x=>x.outcome!=='success').reduce((sum,x)=>sum+x.measurements.count,0),availability=sample?Number((((sample-failures)/sample)*100).toFixed(4)):null,latency=percentile95(selected.filter(x=>x.measurements.duration_ms!==null).map(x=>x.measurements.duration_ms)),allowedError=100-policy.availability_target,consumed=sample?(allowedError===0?(failures?10000:0):Number((((failures/sample)*100/allowedError)*100).toFixed(2))):null;let status='insufficient_data';if(sample>=policy.minimum_events){const breached=availability<policy.availability_target||(latency!==null&&latency>policy.latency_threshold_ms),risk=!breached&&(consumed>=80||(latency!==null&&latency>=policy.latency_threshold_ms*.8));status=breached?'breached':risk?'at_risk':'healthy';}const release_refs=[...new Set(selected.map(x=>x.release_ref).filter(Boolean))].sort(),evaluation={schema_version:'0.1.0',evaluation_id:id('sloeval'),tenant_id,slo_ref:policy.slo_id,service:policy.service,window_start:new Date(start).toISOString(),window_end:new Date(end).toISOString(),sample_size:sample,availability_percent:availability,latency_p95_ms:latency,error_budget_consumed_percent:consumed,status,release_refs,evaluated_at:stamp()};validate('slo-evaluation',evaluation);evaluations.set(evaluation.evaluation_id,evaluation);if(status==='at_risk'||status==='breached')upsertAlert({tenant_id,service:policy.service,release_ref:release_refs.at(-1)||null,kind:status==='breached'?'slo_breached':'slo_at_risk',severity:status==='breached'?'critical':'warning',summary:`SLO ${policy.slo_id} ${status}.`,source_ref:evaluation.evaluation_id});return clone(evaluation);}
 function evaluateUsage(actor,{tenant_id,period_start,period_end,usage}){authorize(actor,'usage.evaluate',tenant_id);const policy=guardrails.get(tenant_id);if(!policy||policy.status!=='active')fail('GUARDRAIL_UNAVAILABLE','Active tenant guardrail required');const resources=policy.limits.map(limit=>{const used=Math.max(0,Math.trunc(usage?.[limit.resource]||0)),percent=Number((used/limit.hard_limit*100).toFixed(2)),state=used>=limit.hard_limit?'exhausted':percent>=limit.warning_at_percent?'warning':'normal';return {resource:limit.resource,used,hard_limit:limit.hard_limit,utilization_percent:percent,state,enforcement:limit.enforcement};}),snapshot={schema_version:'0.1.0',snapshot_id:id('usage'),tenant_id,policy_ref:policy.policy_id,period_start:new Date(period_start).toISOString(),period_end:new Date(period_end).toISOString(),resources,generated_at:stamp()};validate('usage-snapshot',snapshot);usageSnapshots.set(snapshot.snapshot_id,snapshot);for(const row of resources.filter(x=>x.state!=='normal'))upsertAlert({tenant_id,service:'publication',kind:row.state==='exhausted'?'usage_exhausted':'usage_warning',severity:row.state==='exhausted'?'critical':'warning',summary:`${row.resource} alcanzó ${row.utilization_percent}% del límite técnico.`,source_ref:`${snapshot.snapshot_id}:${row.resource}`});return clone(snapshot);}
 function enforce(snapshot,resource){validate('usage-snapshot',snapshot);const row=snapshot.resources.find(x=>x.resource===resource);if(!row)return {allowed:false,action:'deny_unknown'};if(row.state!=='exhausted')return {allowed:true,action:row.state==='warning'?'observe_warning':'allow'};if(row.enforcement==='observe')return {allowed:true,action:'observe_exhausted'};if(row.enforcement==='throttle')return {allowed:true,action:'throttle'};return {allowed:false,action:'block_new'};}
 function listAlerts(actor,tenant_id){authorize(actor,'alerts.read',tenant_id);return [...alerts.values()].filter(x=>x.tenant_id===tenant_id).map(clone);}
 function acknowledgeAlert(actor,alertId){const alert=[...alerts.values()].find(x=>x.alert_id===alertId);if(!alert)fail('ALERT_NOT_FOUND','Alert not found');authorize(actor,'alert.ack',alert.tenant_id);if(alert.status!=='open')fail('ALERT_STATE_INVALID','Only open alerts can be acknowledged');alert.status='acknowledged';alert.last_seen_at=stamp();validate('operational-alert',alert);return clone(alert);}
 function resolveAlert(actor,alertId){const alert=[...alerts.values()].find(x=>x.alert_id===alertId);if(!alert)fail('ALERT_NOT_FOUND','Alert not found');authorize(actor,'alert.resolve',alert.tenant_id);if(alert.status==='resolved')fail('ALERT_STATE_INVALID','Alert already resolved');alert.status='resolved';alert.last_seen_at=stamp();validate('operational-alert',alert);return clone(alert);}
 function openIncident(actor,{alert_refs,title}){if(!Array.isArray(alert_refs)||!alert_refs.length)fail('ALERT_REQUIRED','At least one alert required');const selected=alert_refs.map(ref=>[...alerts.values()].find(x=>x.alert_id===ref));if(selected.some(x=>!x)||new Set(selected.map(x=>x.tenant_id)).size!==1)fail('ALERT_SET_INVALID','Alerts must exist for one tenant');const tenant=selected[0].tenant_id;authorize(actor,'incident.open',tenant);if(selected.every(x=>x.severity!=='critical'))fail('CRITICAL_ALERT_REQUIRED','A critical alert is required');const time=stamp(),incident={schema_version:'0.1.0',incident_id:id('incident'),tenant_id:tenant,severity:'critical',status:'open',title:String(title||''),alert_refs:[...new Set(alert_refs)],release_refs:[...new Set(selected.map(x=>x.release_ref).filter(Boolean))],commander_id:actor.actor_id,timeline:[{type:'opened',note:'Incidente abierto desde alertas operativas.',actor_id:actor.actor_id,occurred_at:time}],opened_at:time,resolved_at:null};validate('incident-record',incident);incidents.set(incident.incident_id,incident);return clone(incident);}
 function updateIncident(actor,incidentId,type,note){const incident=incidents.get(incidentId);if(!incident)fail('INCIDENT_NOT_FOUND','Incident not found');authorize(actor,'incident.update',incident.tenant_id);const transitions={open:new Set(['acknowledged','mitigation_started','rollback_requested']),mitigating:new Set(['mitigation_started','rollback_requested','resolved']),resolved:new Set()};if(!transitions[incident.status]?.has(type)&&!(incident.status==='open'&&type==='resolved'))fail('INCIDENT_TRANSITION_INVALID','Invalid incident transition');incident.timeline.push({type,note:String(note||''),actor_id:actor.actor_id,occurred_at:stamp()});if(['mitigation_started','rollback_requested'].includes(type))incident.status='mitigating';if(type==='resolved'){incident.status='resolved';incident.resolved_at=stamp();}validate('incident-record',incident);return clone(incident);}
 function health(actor,tenant_id,services){authorize(actor,'health.read',tenant_id);const openAlerts=[...alerts.values()].filter(x=>x.tenant_id===tenant_id&&x.status!=='resolved'),openIncidents=[...incidents.values()].filter(x=>x.tenant_id===tenant_id&&x.status!=='resolved'),rows=services.map(input=>{const latest=[...evaluations.values()].filter(x=>x.tenant_id===tenant_id&&x.service===input.service).sort((a,b)=>Date.parse(b.evaluated_at)-Date.parse(a.evaluated_at))[0];const failed=openAlerts.some(x=>x.service===input.service&&x.severity==='critical'),degraded=failed||openAlerts.some(x=>x.service===input.service);return {service:input.service,status:failed?'failed':degraded?'degraded':'operational',slo_status:latest?.status||'not_evaluated',release_ref:input.release_ref??null};}),status=openIncidents.length?'incident':rows.some(x=>x.status!=='operational')?'degraded':'operational',snapshot={schema_version:'0.1.0',snapshot_id:id('health'),tenant_id,status,services:rows,open_alerts:openAlerts.length,open_incidents:openIncidents.length,generated_at:stamp()};validate('service-health-snapshot',snapshot);return snapshot;}
 function notify(actor,alertId){const alert=[...alerts.values()].find(x=>x.alert_id===alertId);if(!alert)fail('ALERT_NOT_FOUND','Alert not found');authorize(actor,'alerts.read',alert.tenant_id);return notificationAdapter.deliver({...clone(alert),synthetic:true});}
 return {ingest,evaluateSlo,evaluateUsage,enforce,listAlerts,acknowledgeAlert,resolveAlert,openIncident,updateIncident,health,notify,_state:{events,evaluations,usageSnapshots,alerts,incidents,slos,guardrails}};
}
module.exports={createObservabilityService,createLocalNotificationAdapter,createUnconfiguredNotificationAdapter,percentile95};
