'use strict';
const crypto=require('node:crypto');const {validate}=require('../site-engine/index.cjs');
const clone=v=>structuredClone(v),sha=v=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex'),id=p=>`${p}-${crypto.randomBytes(12).toString('hex')}`,safe=(v,label='identifier')=>{if(!/^[a-z0-9][a-z0-9-]{2,79}$/.test(String(v||'')))throw Object.assign(new Error(`Invalid ${label}`),{code:'INVALID_IDENTIFIER'});return String(v);};
const capabilities=['portal.access','privacy.request','data.export.request','site.preview','site.publish','lead.capture','custom.domain','analytics.basic','content.change.request','asset.upload','multi.site'];
const baseline=new Set(['portal.access','privacy.request','data.export.request']),claimSensitive=new Set(['site.publish','custom.domain','lead.capture','asset.upload','multi.site']);
const permissions={owner:new Set(['claim.start','claim.evidence','claim.submit','entitlements.read']),operator:new Set(['claim.review','entitlements.read']),admin:new Set(['claim.start','claim.evidence','claim.submit','claim.review','claim.revoke','grant.create','grant.revoke','billing.ingest','entitlements.read']),system:new Set(['billing.ingest','entitlements.read'])};
const subscriptionTransitions={none:new Set(['trialing','active']),trialing:new Set(['trialing','active','past_due','suspended','cancelled']),active:new Set(['active','past_due','suspended','cancelled']),past_due:new Set(['active','past_due','suspended','cancelled']),suspended:new Set(['active','suspended','cancelled']),cancelled:new Set()};
function authorize(actor,action,tenant){if(!actor||!permissions[actor.role]?.has(action)||(actor.tenant_id&&actor.tenant_id!==tenant))throw Object.assign(new Error('Access denied'),{code:'ACCESS_DENIED'});return true;}
function createUnconfiguredBillingAdapter(){return {name:'unconfigured',normalize(){throw Object.assign(new Error('Billing adapter is not configured'),{code:'BILLING_UNCONFIGURED'});}};}
function createLocalBillingAdapter(){return {name:'local_sandbox',normalize(raw){if(!raw?.synthetic)throw Object.assign(new Error('Local adapter accepts synthetic events only'),{code:'BILLING_EVENT_REJECTED'});const event={schema_version:'0.1.0',event_id:raw.event_id||id('billing'),provider:'local_sandbox',tenant_id:raw.tenant_id,subscription_id:raw.subscription_id,plan_ref:raw.plan_ref??null,type:raw.type,new_status:raw.new_status,occurred_at:raw.occurred_at,idempotency_key:sha(raw.idempotency_key||`${raw.subscription_id}|${raw.type}|${raw.occurred_at}`),signature_verified:true};return {event,trial_ends_at:raw.trial_ends_at??null,period_ends_at:raw.period_ends_at??null,cancel_at_period_end:raw.cancel_at_period_end===true};}};}
function createClaimEntitlementService({plans,billingAdapter=createUnconfiguredBillingAdapter(),now=()=>new Date()}={}){
 if(!Array.isArray(plans)||!plans.length)throw Object.assign(new Error('Plan catalog required'),{code:'PLAN_CATALOG_REQUIRED'});const planMap=new Map();for(const plan of plans){validate('product-plan',plan);if(planMap.has(plan.plan_id)||new Set(plan.capabilities.map(x=>x.key)).size!==plan.capabilities.length)throw Object.assign(new Error('Duplicate plan or capability'),{code:'PLAN_CATALOG_INVALID'});planMap.set(plan.plan_id,clone(plan));}
 const claims=new Map(),subscriptions=new Map(),billingEvents=new Map(),grants=new Map();const at=()=>now().toISOString();
 function startClaim(actor,{tenant_id,business_id}){authorize(actor,'claim.start',tenant_id);const created=at(),claim={schema_version:'0.1.0',claim_id:id('claim'),tenant_id:safe(tenant_id,'tenant'),business_id:safe(business_id,'business'),claimant_id:safe(actor.actor_id,'actor'),status:'draft',evidence:[],submitted_at:null,verified_at:null,reviewer_id:null,decision_reason:null,created_at:created,updated_at:created};validate('business-claim',claim);claims.set(claim.claim_id,claim);return clone(claim);}
 function addEvidence(actor,claimId,{kind,artifact_sha256}){const claim=claims.get(claimId);if(!claim)throw Object.assign(new Error('Claim not found'),{code:'CLAIM_NOT_FOUND'});authorize(actor,'claim.evidence',claim.tenant_id);if(actor.actor_id!==claim.claimant_id||!['draft','evidence_pending'].includes(claim.status))throw Object.assign(new Error('Evidence cannot be added'),{code:'CLAIM_STATE_INVALID'});if(claim.evidence.some(x=>x.kind===kind&&x.artifact_sha256===artifact_sha256))throw Object.assign(new Error('Duplicate evidence'),{code:'EVIDENCE_DUPLICATE'});claim.evidence.push({evidence_id:id('evidence'),kind,artifact_sha256:String(artifact_sha256||''),collected_at:at(),verification_status:'pending',reviewer_id:null,review_note:null});claim.updated_at=at();validate('business-claim',claim);return clone(claim);}
 function submitClaim(actor,claimId){const claim=claims.get(claimId);if(!claim)throw Object.assign(new Error('Claim not found'),{code:'CLAIM_NOT_FOUND'});authorize(actor,'claim.submit',claim.tenant_id);if(actor.actor_id!==claim.claimant_id||!['draft','evidence_pending'].includes(claim.status)||new Set(claim.evidence.map(x=>x.kind)).size<2)throw Object.assign(new Error('Two independent evidence kinds required'),{code:'EVIDENCE_INSUFFICIENT'});claim.status='submitted';claim.submitted_at=at();claim.updated_at=claim.submitted_at;validate('business-claim',claim);return clone(claim);}
 function reviewEvidence(actor,claimId,evidenceId,decision,note){const claim=claims.get(claimId);if(!claim)throw Object.assign(new Error('Claim not found'),{code:'CLAIM_NOT_FOUND'});authorize(actor,'claim.review',claim.tenant_id);if(actor.actor_id===claim.claimant_id||!['submitted','evidence_pending'].includes(claim.status)||!['accepted','rejected'].includes(decision))throw Object.assign(new Error('Evidence review invalid'),{code:'EVIDENCE_REVIEW_INVALID'});const evidence=claim.evidence.find(x=>x.evidence_id===evidenceId);if(!evidence||evidence.verification_status!=='pending')throw Object.assign(new Error('Evidence unavailable'),{code:'EVIDENCE_STATE_INVALID'});evidence.verification_status=decision;evidence.reviewer_id=safe(actor.actor_id,'reviewer');evidence.review_note=String(note||'').trim();claim.status='evidence_pending';claim.updated_at=at();validate('business-claim',claim);return clone(claim);}
 function decideClaim(actor,claimId,decision,reason){const claim=claims.get(claimId);if(!claim)throw Object.assign(new Error('Claim not found'),{code:'CLAIM_NOT_FOUND'});authorize(actor,'claim.review',claim.tenant_id);if(actor.actor_id===claim.claimant_id||!['submitted','evidence_pending'].includes(claim.status)||!['verified','rejected'].includes(decision))throw Object.assign(new Error('Claim decision invalid'),{code:'CLAIM_DECISION_INVALID'});const accepted=new Set(claim.evidence.filter(x=>x.verification_status==='accepted').map(x=>x.kind));if(decision==='verified'&&accepted.size<2)throw Object.assign(new Error('Verified claim needs two accepted evidence kinds'),{code:'EVIDENCE_INSUFFICIENT'});claim.status=decision;claim.reviewer_id=safe(actor.actor_id,'reviewer');claim.decision_reason=String(reason||'').trim();claim.updated_at=at();claim.verified_at=decision==='verified'?claim.updated_at:null;validate('business-claim',claim);return clone(claim);}
 function revokeClaim(actor,claimId,reason){const claim=claims.get(claimId);if(!claim)throw Object.assign(new Error('Claim not found'),{code:'CLAIM_NOT_FOUND'});authorize(actor,'claim.revoke',claim.tenant_id);if(claim.status!=='verified')throw Object.assign(new Error('Only verified claims can be revoked'),{code:'CLAIM_STATE_INVALID'});claim.status='revoked';claim.reviewer_id=safe(actor.actor_id,'reviewer');claim.decision_reason=String(reason||'').trim();claim.updated_at=at();validate('business-claim',claim);return clone(claim);}
 function ingestBilling(actor,raw){const normalized=billingAdapter.normalize(raw),event=normalized.event;validate('billing-normalized-event',event);authorize(actor,'billing.ingest',event.tenant_id);if(billingEvents.has(event.idempotency_key))return {subscription:clone(subscriptions.get(event.tenant_id)),event:clone(billingEvents.get(event.idempotency_key)),duplicate:true};const plan=event.plan_ref?planMap.get(event.plan_ref):null;if(event.plan_ref&&!plan)throw Object.assign(new Error('Unknown plan'),{code:'PLAN_UNKNOWN'});if(plan&&plan.status!=='active'&&event.provider!=='local_sandbox')throw Object.assign(new Error('Plan is not commercially active'),{code:'PLAN_INACTIVE'});const prior=subscriptions.get(event.tenant_id),from=prior?.status||'none';if(!subscriptionTransitions[from]?.has(event.new_status))throw Object.assign(new Error('Invalid subscription transition'),{code:'SUBSCRIPTION_TRANSITION_INVALID'});if(prior?.last_event_at&&Date.parse(event.occurred_at)<Date.parse(prior.last_event_at))throw Object.assign(new Error('Stale billing event'),{code:'BILLING_EVENT_STALE'});const created=prior?.created_at||event.occurred_at,state={schema_version:'0.1.0',subscription_id:event.subscription_id,tenant_id:event.tenant_id,plan_ref:event.plan_ref,provider:event.provider,external_customer_ref:null,status:event.new_status,trial_ends_at:normalized.trial_ends_at,period_ends_at:normalized.period_ends_at,cancel_at_period_end:normalized.cancel_at_period_end,last_event_at:event.occurred_at,version:(prior?.version||0)+1,created_at:created,updated_at:event.occurred_at};validate('subscription-state',state);subscriptions.set(event.tenant_id,state);billingEvents.set(event.idempotency_key,event);return {subscription:clone(state),event:clone(event),duplicate:false};}
 function createGrant(actor,{tenant_id,capability,limit=null,expires_at,reason,source='manual_pilot'}){authorize(actor,'grant.create',tenant_id);if(!capabilities.includes(capability)||Date.parse(expires_at)<=Date.parse(at())||Date.parse(expires_at)>Date.parse(at())+31*86400000)throw Object.assign(new Error('Grant invalid or exceeds 31 days'),{code:'GRANT_INVALID'});if(claimSensitive.has(capability)&&![...claims.values()].some(x=>x.tenant_id===tenant_id&&x.status==='verified'))throw Object.assign(new Error('Verified claim required for sensitive grant'),{code:'CLAIM_REQUIRED'});const created=at(),grant={schema_version:'0.1.0',grant_id:id('grant'),tenant_id:safe(tenant_id,'tenant'),capability,source,status:'active',limit,starts_at:created,expires_at,reason:String(reason||'').trim(),granted_by:safe(actor.actor_id,'actor'),created_at:created};validate('entitlement-grant',grant);grants.set(grant.grant_id,grant);return clone(grant);}
 function revokeGrant(actor,grantId){const grant=grants.get(grantId);if(!grant)throw Object.assign(new Error('Grant not found'),{code:'GRANT_NOT_FOUND'});authorize(actor,'grant.revoke',grant.tenant_id);grant.status='revoked';validate('entitlement-grant',grant);return clone(grant);}
 function derive(actor,tenantId){authorize(actor,'entitlements.read',tenantId);const stamp=Date.parse(at()),claim=[...claims.values()].filter(x=>x.tenant_id===tenantId&&x.status==='verified').sort((a,b)=>Date.parse(b.verified_at)-Date.parse(a.verified_at))[0]||null,subscription=subscriptions.get(tenantId)||null,plan=subscription?.plan_ref?planMap.get(subscription.plan_ref):null,subscriptionActive=!!subscription&&['active','trialing'].includes(subscription.status)&&!(subscription.status==='trialing'&&subscription.trial_ends_at&&Date.parse(subscription.trial_ends_at)<=stamp),planCapabilities=new Map((plan?.capabilities||[]).map(x=>[x.key,x])),activeGrants=[...grants.values()].filter(x=>x.tenant_id===tenantId&&x.status==='active'&&Date.parse(x.starts_at)<=stamp&&Date.parse(x.expires_at)>stamp),rows=capabilities.map(key=>{if(baseline.has(key))return {key,allowed:true,limit:null,reason:'baseline_safety'};const grant=activeGrants.find(x=>x.capability===key);if(grant&&(!claimSensitive.has(key)||claim))return {key,allowed:true,limit:grant.limit,reason:'manual_grant'};if(!claim)return {key,allowed:false,limit:null,reason:'claim_required'};if(!subscriptionActive)return {key,allowed:false,limit:null,reason:'subscription_inactive'};const configured=planCapabilities.get(key);if(!configured||configured.mode==='disabled')return {key,allowed:false,limit:null,reason:'plan_disabled'};return {key,allowed:true,limit:configured.mode==='limited'?configured.limit:null,reason:'verified_active_plan'};}),inputs={claim:claim?{id:claim.claim_id,status:claim.status,updated_at:claim.updated_at}:null,subscription:subscription?{id:subscription.subscription_id,status:subscription.status,version:subscription.version}:null,plan:plan?{id:plan.plan_id,version:plan.plan_version}:null,grants:activeGrants.map(x=>x.grant_id).sort()},snapshot={schema_version:'0.1.0',snapshot_id:id('entitlements'),tenant_id:tenantId,claim_ref:claim?.claim_id||null,subscription_ref:subscription?.subscription_id||null,plan_ref:plan?.plan_id||null,generated_at:at(),inputs_sha256:sha(inputs),capabilities:rows};validate('entitlement-snapshot',snapshot);return snapshot;}
 function can(snapshot,key){validate('entitlement-snapshot',snapshot);return snapshot.capabilities.find(x=>x.key===key)?.allowed===true;}
 return {startClaim,addEvidence,submitClaim,reviewEvidence,decideClaim,revokeClaim,ingestBilling,createGrant,revokeGrant,derive,can,_state:{claims,subscriptions,billingEvents,grants,plans:planMap}};
}
module.exports={createClaimEntitlementService,createLocalBillingAdapter,createUnconfiguredBillingAdapter,capabilities};
