'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const Ajv=require('ajv/dist/2020');const addFormats=require('ajv-formats');
const ROOT=path.resolve(__dirname,'../..'),ajv=new Ajv({allErrors:true,strict:false,validateFormats:true});addFormats(ajv);
const schemaNames=['pilot-dossier','pilot-review-decision','owner-pilot-acceptance','launch-readiness-evaluation','launch-rehearsal','pilot-launch-package','pilot-acceptance-audit-event'];
const validators=Object.fromEntries(schemaNames.map(name=>[name,ajv.compile(JSON.parse(fs.readFileSync(path.join(ROOT,'contracts',`${name}.schema.json`),'utf8')))]));
const clone=value=>JSON.parse(JSON.stringify(value));
const canonical=value=>JSON.stringify(value,(_key,current)=>current&&typeof current==='object'&&!Array.isArray(current)?Object.fromEntries(Object.entries(current).sort(([left],[right])=>left.localeCompare(right))):current);
const sha=value=>crypto.createHash('sha256').update(typeof value==='string'?value:canonical(value)).digest('hex');
const fail=(code,message,details)=>Object.assign(new Error(message),{code,details});
function validate(name,value){const validator=validators[name];if(!validator(value))throw fail('SCHEMA_INVALID',`${name} invalid`,validator.errors);return value;}
const requirementLabels={identity:'Identidad y autoridad del negocio',brand:'Marca y posicionamiento',assets:'Derechos y estado de activos',copy:'Copy y afirmaciones',design:'Dirección visual y páginas',privacy:'Aviso y controles de privacidad',contact:'Canal público autorizado',domain:'Dominio y hostname',publication:'Plan de publicación y rollback'};
const areaRequirements={content:['identity','brand','copy'],visual:['assets','design'],privacy:['privacy','contact'],technical:['domain','publication']};
const acceptanceScope=['identity','copy','design','assets','contact','domain','privacy'];
function hashDossier(dossier){return sha({tenant_id:dossier.tenant_id,business_id:dossier.business_id,site_id:dossier.site_id,revision:dossier.revision,synthetic:dossier.synthetic,source_refs:dossier.source_refs,requirements:dossier.requirements});}
function createPilotAcceptanceService({now=()=>new Date(),allowRealData=false}={}){
  const dossiers=new Map(),reviews=new Map(),acceptances=new Map(),evaluations=new Map(),rehearsals=new Map(),packages=new Map(),events=[];let sequence=0;
  const stamp=()=>now().toISOString(),makeId=(prefix,salt='')=>`${prefix}-${sha(`${prefix}|${salt}|${sequence++}|${stamp()}`).slice(0,24)}`;
  function authorize(actor,tenantId,roles){if(!actor||!roles.includes(actor.role)||(actor.role!=='admin'&&actor.tenant_id!==tenantId))throw fail('ACCESS_DENIED','Actor cannot access this tenant');}
  function append(type,subjectRef,actor,dossier){const previous=events.at(-1)?.event_hash||null,base={schema_version:'0.1.0',event_id:makeId('pilotev',subjectRef),tenant_id:dossier.tenant_id,dossier_id:dossier.dossier_id,type,subject_ref:subjectRef,actor_id:actor.actor_id,occurred_at:stamp(),previous_hash:previous},event={...base,event_hash:sha(base)};validate('pilot-acceptance-audit-event',event);events.push(event);return event;}
  function createDossier(actor,input){authorize(actor,input.tenant_id,['operator','admin']);if(input.synthetic!==true&&!allowRealData)throw fail('REAL_DATA_DISABLED','Real pilot data is disabled in the local service');const created=stamp(),dossier={schema_version:'0.1.0',dossier_id:makeId('pilotd',input.business_id),tenant_id:input.tenant_id,business_id:input.business_id,site_id:input.site_id,revision:1,synthetic:input.synthetic===true,status:'draft',source_refs:clone(input.source_refs),requirements:Object.entries(requirementLabels).map(([key,label])=>({key,label,status:'pending',evidence_refs:[],blocker_code:null,updated_by:actor.actor_id,updated_at:created})),snapshot_hash:'0'.repeat(64),created_by:actor.actor_id,created_at:created,updated_at:created};dossier.snapshot_hash=hashDossier(dossier);validate('pilot-dossier',dossier);dossiers.set(dossier.dossier_id,dossier);append('dossier.created',dossier.dossier_id,actor,dossier);return clone(dossier);}
  function getDossier(id){const dossier=dossiers.get(id);if(!dossier)throw fail('DOSSIER_NOT_FOUND','Pilot dossier not found');return dossier;}
  function updateRequirement(actor,dossierId,expectedRevision,key,input){const current=getDossier(dossierId);authorize(actor,current.tenant_id,['operator','admin']);if(current.status==='sealed_local')throw fail('DOSSIER_SEALED','Sealed dossier cannot change');if(current.revision!==expectedRevision)throw fail('REVISION_CONFLICT','Dossier revision changed');const dossier=clone(current),requirement=dossier.requirements.find(item=>item.key===key);if(!requirement)throw fail('REQUIREMENT_UNKNOWN','Unknown pilot requirement');if(!['pending','ready','blocked'].includes(input.status))throw fail('REQUIREMENT_STATUS_INVALID','Invalid requirement status');requirement.status=input.status;requirement.evidence_refs=[...new Set(input.evidence_refs||[])];requirement.blocker_code=input.status==='blocked'?String(input.blocker_code||'evidence_missing'):null;requirement.updated_by=actor.actor_id;requirement.updated_at=stamp();dossier.revision+=1;dossier.status=input.status==='blocked'?'changes_requested':'draft';dossier.updated_at=stamp();dossier.snapshot_hash=hashDossier(dossier);validate('pilot-dossier',dossier);dossiers.set(dossierId,dossier);append('requirement.updated',key,actor,dossier);return clone(dossier);}
  function submitDossier(actor,dossierId){const dossier=getDossier(dossierId);authorize(actor,dossier.tenant_id,['operator','admin']);const blockers=dossier.requirements.filter(item=>item.status!=='ready').map(item=>item.key);if(blockers.length)throw fail('DOSSIER_INCOMPLETE','Every requirement needs evidence before review',blockers);dossier.status='in_review';dossier.updated_at=stamp();validate('pilot-dossier',dossier);append('dossier.submitted',dossier.dossier_id,actor,dossier);return clone(dossier);}
  function recordReview(actor,{dossier_id,dossier_hash,area,decision,failed_checks=[],reason_codes=[],notes=null}){const dossier=getDossier(dossier_id);authorize(actor,dossier.tenant_id,['operator','admin']);if(dossier.snapshot_hash!==dossier_hash)throw fail('DOSSIER_STALE','Review targets a stale dossier snapshot');if(dossier.status!=='in_review')throw fail('DOSSIER_NOT_IN_REVIEW','Dossier is not open for review');if(actor.actor_id===dossier.created_by)throw fail('INDEPENDENT_REVIEW_REQUIRED','Dossier creator cannot approve the dossier');if(!areaRequirements[area])throw fail('REVIEW_AREA_INVALID','Unknown review area');if([...reviews.values()].some(item=>item.dossier_id===dossier_id&&item.dossier_hash===dossier_hash&&item.area===area))throw fail('REVIEW_ALREADY_RECORDED','Review area already has an immutable decision');const checks=areaRequirements[area].map(key=>{const requirement=dossier.requirements.find(item=>item.key===key),passed=requirement.status==='ready'&&!failed_checks.includes(key);return {check_id:key,label:requirement.label,status:passed?'passed':'failed',evidence:passed?requirement.evidence_refs.join(', '):'Requiere corrección antes de aceptar.'};});if(decision==='approved'&&checks.some(item=>item.status!=='passed'))throw fail('REVIEW_BLOCKED','Approval requires every area check to pass');const review={schema_version:'0.1.0',review_id:makeId('pilotr',`${dossier_id}|${area}`),dossier_id,dossier_hash,tenant_id:dossier.tenant_id,area,decision,checks,reason_codes:decision==='approved'?[]:[...new Set(reason_codes.length?reason_codes:['changes_required'])],notes,reviewer:{actor_id:actor.actor_id,role:actor.role},created_at:stamp()};validate('pilot-review-decision',review);reviews.set(review.review_id,review);if(decision!=='approved')dossier.status='changes_requested';append('review.recorded',review.review_id,actor,dossier);return clone(review);}
  function currentApprovedReviews(dossier){return Object.keys(areaRequirements).map(area=>[...reviews.values()].find(item=>item.dossier_id===dossier.dossier_id&&item.dossier_hash===dossier.snapshot_hash&&item.area===area&&item.decision==='approved')).filter(Boolean);}
  function ownerAccept(actor,{dossier_id,dossier_hash,decision='accepted',acknowledgements}){const dossier=getDossier(dossier_id);authorize(actor,dossier.tenant_id,['owner']);if(dossier.snapshot_hash!==dossier_hash)throw fail('DOSSIER_STALE','Acceptance targets a stale dossier snapshot');const approved=currentApprovedReviews(dossier);if(approved.length!==4)throw fail('REVIEWS_INCOMPLETE','Four approved independent reviews are required');const acceptance={schema_version:'0.1.0',acceptance_id:makeId('pilota',dossier_id),dossier_id,dossier_hash,tenant_id:dossier.tenant_id,business_id:dossier.business_id,scope:[...acceptanceScope],decision,acknowledgements:clone(acknowledgements),owner_id:actor.actor_id,created_at:stamp()};validate('owner-pilot-acceptance',acceptance);acceptances.set(acceptance.acceptance_id,acceptance);dossier.status=decision==='accepted'?'accepted':'changes_requested';dossier.updated_at=stamp();if(decision==='accepted')append('owner.accepted',acceptance.acceptance_id,actor,dossier);return clone(acceptance);}
  function evaluateReadiness(actor,dossierId){const dossier=getDossier(dossierId);authorize(actor,dossier.tenant_id,['operator','admin']);const approved=currentApprovedReviews(dossier),acceptance=[...acceptances.values()].find(item=>item.dossier_id===dossierId&&item.dossier_hash===dossier.snapshot_hash&&item.decision==='accepted'),checks=[];for(const requirement of dossier.requirements)checks.push({key:`requirement-${requirement.key}`,status:requirement.status==='ready'?'passed':'failed',evidence_ref:requirement.evidence_refs[0]||null});for(const area of Object.keys(areaRequirements)){const review=approved.find(item=>item.area===area);checks.push({key:`review-${area}`,status:review?'passed':'failed',evidence_ref:review?.review_id||null});}checks.push({key:'owner-acceptance',status:acceptance?'passed':'failed',evidence_ref:acceptance?.acceptance_id||null});const blockers=checks.filter(item=>item.status==='failed').map(item=>item.key),status=blockers.length?'blocked':'ready_for_rehearsal',evaluation={schema_version:'0.1.0',evaluation_id:makeId('pilote',dossierId),dossier_id:dossierId,dossier_hash:dossier.snapshot_hash,tenant_id:dossier.tenant_id,status,checks,blockers,review_refs:approved.map(item=>item.review_id),acceptance_ref:acceptance?.acceptance_id||null,evaluated_by:actor.actor_id,evaluated_at:stamp()};validate('launch-readiness-evaluation',evaluation);evaluations.set(evaluation.evaluation_id,evaluation);if(status==='ready_for_rehearsal'){dossier.status='ready_for_rehearsal';dossier.updated_at=stamp();}append('readiness.evaluated',evaluation.evaluation_id,actor,dossier);return clone(evaluation);}
  function rehearseLaunch(actor,{dossier_id,readiness_ref,fail_step=null}){const dossier=getDossier(dossier_id);authorize(actor,dossier.tenant_id,['operator','admin']);const readiness=evaluations.get(readiness_ref);if(!readiness||readiness.dossier_id!==dossier_id||readiness.dossier_hash!==dossier.snapshot_hash||readiness.status!=='ready_for_rehearsal')throw fail('READINESS_REQUIRED','Current ready evaluation required');const definitions=[['snapshot-binding','Snapshot and approvals point to the same immutable revision.'],['asset-rights','Asset rights gate completed.'],['content-acceptance','Copy and factual claims accepted.'],['visual-acceptance','Responsive pages accepted.'],['privacy-controls','Privacy and contact controls present.'],['domain-plan','Managed hostname plan checked locally.'],['rollback-plan','Rollback path and incident owner identified.']],steps=definitions.map(([key,detail])=>({key,status:key===fail_step?'failed':'passed',detail:key===fail_step?'Synthetic failure requested for rehearsal.':detail})),status=steps.every(item=>item.status==='passed')?'passed':'failed',rehearsal={schema_version:'0.1.0',rehearsal_id:makeId('piloth',dossier_id),dossier_id,dossier_hash:dossier.snapshot_hash,tenant_id:dossier.tenant_id,readiness_ref,environment:'local',execution_mode:'dry_run',status,steps,external_changes:0,external_messages:0,publication_performed:false,performed_by:actor.actor_id,performed_at:stamp()};validate('launch-rehearsal',rehearsal);rehearsals.set(rehearsal.rehearsal_id,rehearsal);append('rehearsal.completed',rehearsal.rehearsal_id,actor,dossier);return clone(rehearsal);}
  function sealPackage(actor,{dossier_id,readiness_ref,rehearsal_ref}){const dossier=getDossier(dossier_id);authorize(actor,dossier.tenant_id,['operator','admin']);const readiness=evaluations.get(readiness_ref),rehearsal=rehearsals.get(rehearsal_ref);if(!readiness||readiness.dossier_hash!==dossier.snapshot_hash||readiness.status!=='ready_for_rehearsal')throw fail('READINESS_REQUIRED','Current ready evaluation required');if(!rehearsal||rehearsal.dossier_hash!==dossier.snapshot_hash||rehearsal.readiness_ref!==readiness_ref||rehearsal.status!=='passed')throw fail('REHEARSAL_REQUIRED','Passed rehearsal required');const artifactRefs=[...new Set([...Object.values(dossier.source_refs),...readiness.review_refs,readiness.acceptance_ref,readiness_ref,rehearsal_ref].filter(Boolean))],generated=stamp(),record={schema_version:'0.1.0',package_id:makeId('pilotp',dossier_id),dossier_id,dossier_hash:dossier.snapshot_hash,tenant_id:dossier.tenant_id,business_id:dossier.business_id,readiness_ref,rehearsal_ref,artifact_refs:artifactRefs,content_digest:sha(artifactRefs.join('|')),status:'sealed_local',may_publish:false,generated_by:actor.actor_id,generated_at:generated};validate('pilot-launch-package',record);packages.set(record.package_id,record);dossier.status='sealed_local';dossier.updated_at=generated;append('package.sealed',record.package_id,actor,dossier);return clone(record);}
  function revokePackage(actor,packageId){const record=packages.get(packageId);if(!record)throw fail('PACKAGE_NOT_FOUND','Pilot package not found');authorize(actor,record.tenant_id,['operator','admin']);if(record.status==='revoked')return clone(record);record.status='revoked';const dossier=getDossier(record.dossier_id);append('package.revoked',record.package_id,actor,dossier);return clone(record);}
  function read(actor,tenantId){authorize(actor,tenantId,['owner','operator','admin']);const own=item=>item.tenant_id===tenantId;return {dossiers:[...dossiers.values()].filter(own).map(clone),reviews:[...reviews.values()].filter(own).map(clone),acceptances:[...acceptances.values()].filter(own).map(clone),evaluations:[...evaluations.values()].filter(own).map(clone),rehearsals:[...rehearsals.values()].filter(own).map(clone),packages:[...packages.values()].filter(own).map(clone),events:events.filter(own).map(clone)};}
  function verifyAudit(){for(let index=0;index<events.length;index++){const event=events[index],base={...event};delete base.event_hash;if(event.previous_hash!==(index?events[index-1].event_hash:null)||sha(base)!==event.event_hash)return false;}return true;}
  return {createDossier,updateRequirement,submitDossier,recordReview,ownerAccept,evaluateReadiness,rehearseLaunch,sealPackage,revokePackage,read,verifyAudit,hashDossier,_state:{dossiers,reviews,acceptances,evaluations,rehearsals,packages,events}};
}
module.exports={createPilotAcceptanceService,hashDossier,requirementLabels,areaRequirements,acceptanceScope};
