'use strict';
const crypto=require('node:crypto');
const {validate}=require('../site-engine/index.cjs');
const clone=value=>structuredClone(value);
const hash=value=>crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
const id=prefix=>`${prefix}-${crypto.randomBytes(12).toString('hex')}`;
const fail=(code,message)=>{throw Object.assign(new Error(message),{code});};
const safe=value=>{if(!/^[a-z0-9][a-z0-9-]{2,100}$/.test(String(value||'')))fail('IDENTIFIER_INVALID','Unsafe identifier');return String(value);};
const requiredConfiguration=['CF_ACCOUNT_ID','CF_ZONE_ID','CF_API_TOKEN','CF_R2_BUCKET_NAME','CF_D1_DATABASE_ID','CF_QUEUE_NAME','CF_CUSTOM_HOSTNAMES_ENABLED','CF_HEALTH_ENDPOINT'];
const services=['account','zone','worker','r2','d1','queue','custom_hostnames','health_endpoint'];
const permissions={operator:new Set(['plan.create','plan.approve','plan.simulate','drift.read']),admin:new Set(['plan.create','plan.approve','plan.simulate','plan.apply','drift.read']),system:new Set(['plan.simulate','drift.read']),owner:new Set(['drift.read'])};
function authorize(actor,action,tenantId){if(!actor||!permissions[actor.role]?.has(action)||(actor.tenant_id&&actor.tenant_id!==tenantId))fail('ACCESS_DENIED','Access denied');}
function cleanHostname(value){const hostname=String(value||'').trim().toLowerCase().replace(/\.$/,'');if(!/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(hostname))fail('HOSTNAME_INVALID','Invalid hostname');return hostname;}
function createDryRunAdapter(options={}){return {name:'cloudflare_dry_run',mode:'dry_run',executeAction(action){return {resource:action.resource,status:'simulated',provider_ref:`dry-run://${action.logical_ref}`};},probe({stage_percent,hostname,artifact_digest}){const failure=options.failStage===stage_percent;return {status_code:failure&&options.failure==='status'?503:200,latency_ms:failure&&options.failure==='latency'?2501:45+stage_percent,content_digest_match:!(failure&&options.failure==='digest'),security_headers:!(failure&&options.failure==='headers'),indexing_policy:'noindex',hostname,artifact_digest};},rollback(){return {status:'simulated'};}};}
function createUnconfiguredCloudflareAdapter(){return {name:'unconfigured',mode:'blocked',executeAction(){fail('CLOUDFLARE_ADAPTER_UNCONFIGURED','Cloudflare apply adapter is not configured');},probe(){fail('CLOUDFLARE_ADAPTER_UNCONFIGURED','Cloudflare apply adapter is not configured');},rollback(){fail('CLOUDFLARE_ADAPTER_UNCONFIGURED','Cloudflare apply adapter is not configured');}};}
function createDeploymentService({adapter=createUnconfiguredCloudflareAdapter(),now=()=>new Date()}={}){
 const plans=new Map(),executions=new Map();const stamp=()=>now().toISOString();
 function buildUploadPlan({tenant_id,build_id,manifest_digest,artifacts}){safe(tenant_id);safe(build_id);if(!Array.isArray(artifacts)||!artifacts.length)fail('ARTIFACTS_REQUIRED','Artifacts required');if(new Set(artifacts.map(x=>x.path)).size!==artifacts.length)fail('ARTIFACT_DUPLICATE','Artifact paths must be unique');const plan={schema_version:'0.1.0',upload_plan_id:id('uploadplan'),tenant_id,build_id,bucket_binding:'SITE_ARTIFACTS',prefix:`tenants/${tenant_id}/builds/${build_id}/`,manifest_digest,artifacts:artifacts.map(item=>({path:item.path,sha256:item.sha256,bytes:item.bytes,cache_control:item.cache_control||'public, max-age=31536000, immutable'})),total_bytes:artifacts.reduce((sum,item)=>sum+item.bytes,0),immutable:true,created_at:stamp()};validate('artifact-upload-plan',plan);return plan;}
 function createPlan(actor,input){authorize(actor,'plan.create',input.tenant_id);const hostname=cleanHostname(input.hostname);if(!hostname.endsWith('.guialima.online'))fail('STAGING_HOSTNAME_REQUIRED','Staging requires a guialima.online hostname');const refs={worker:'site-router-staging',r2_artifacts:`artifacts-${safe(input.build_id)}`,d1_routes:`route-${safe(input.site_id)}`,queue:'deployment-events',custom_hostname:`hostname-${hostname.replaceAll('.','-')}`,cache:`cache-${safe(input.site_id)}`},dependencies={worker:['r2_artifacts','d1_routes'],r2_artifacts:[],d1_routes:['r2_artifacts'],queue:[],custom_hostname:['worker','d1_routes'],cache:['custom_hostname']};const plan={schema_version:'0.1.0',plan_id:id('deployplan'),tenant_id:safe(input.tenant_id),site_id:safe(input.site_id),release_id:safe(input.release_id),build_id:safe(input.build_id),environment:'staging',hostname,artifact_digest:String(input.artifact_digest),execution_mode:input.execution_mode||'dry_run',status:'draft',resource_actions:Object.keys(refs).map(resource=>({resource,action:resource==='worker'?'update':'create',logical_ref:refs[resource],depends_on:dependencies[resource]})),configuration_requirements:[...requiredConfiguration],created_by:safe(actor.actor_id),approved_by:null,approved_at:null,created_at:stamp()};validate('cloudflare-deployment-plan',plan);plans.set(plan.plan_id,plan);return clone(plan);}
 function approvePlan(actor,planId){const plan=plans.get(planId);if(!plan)fail('PLAN_NOT_FOUND','Plan not found');authorize(actor,'plan.approve',plan.tenant_id);if(actor.actor_id===plan.created_by)fail('INDEPENDENT_APPROVAL_REQUIRED','Plan creator cannot approve it');if(plan.status!=='draft')fail('PLAN_STATE_INVALID','Only draft plans can be approved');plan.status='approved';plan.approved_by=safe(actor.actor_id);plan.approved_at=stamp();validate('cloudflare-deployment-plan',plan);return clone(plan);}
 function preflight(actor,planId,configuration={}){const plan=plans.get(planId);if(!plan)fail('PLAN_NOT_FOUND','Plan not found');authorize(actor,plan.execution_mode==='apply'?'plan.apply':'plan.simulate',plan.tenant_id);const missing=plan.configuration_requirements.filter(name=>!configuration[name]);const dry=plan.execution_mode==='dry_run';const checks=services.map((service,index)=>{const key=requiredConfiguration[index],ready=!!configuration[key];return {service,status:dry?'simulated':ready?'ready':'blocked',evidence:dry?`${key} se valida por nombre; no se consulta el proveedor.`:ready?`${key} presente en memoria; valor no registrado.`:`Falta ${key}.`};});const report={schema_version:'0.1.0',preflight_id:id('preflight'),plan_id:plan.plan_id,execution_mode:plan.execution_mode,status:dry?'simulated':missing.length?'blocked':'ready',checks,missing_configuration:missing,may_simulate:dry,may_apply:!dry&&missing.length===0&&adapter.mode==='apply',generated_at:stamp()};validate('cloudflare-preflight',report);return report;}
 function runCanary(plan){const checks=[];for(const stage of [5,25,50,100]){const observed=adapter.probe({stage_percent:stage,hostname:plan.hostname,artifact_digest:plan.artifact_digest}),passed=observed.status_code===200&&observed.latency_ms<=2000&&observed.content_digest_match===true&&observed.security_headers===true&&observed.indexing_policy==='noindex',check={schema_version:'0.1.0',check_id:id('canary'),plan_id:plan.plan_id,stage_percent:stage,hostname:plan.hostname,status_code:observed.status_code,latency_ms:observed.latency_ms,content_digest_match:observed.content_digest_match,security_headers:observed.security_headers,indexing_policy:observed.indexing_policy,status:passed?'passed':'failed',checked_at:stamp()};validate('canary-check',check);checks.push(check);if(!passed)break;}return checks;}
 function execute(actor,planId,preflightReport){const plan=plans.get(planId);if(!plan)fail('PLAN_NOT_FOUND','Plan not found');authorize(actor,plan.execution_mode==='apply'?'plan.apply':'plan.simulate',plan.tenant_id);if(plan.status!=='approved'||preflightReport?.plan_id!==plan.plan_id)fail('EXECUTION_GATE_FAILED','Approved plan and matching preflight required');validate('cloudflare-preflight',preflightReport);if(plan.execution_mode==='apply'&&!preflightReport.may_apply)fail('REAL_APPLY_BLOCKED','Real apply is blocked');if(plan.execution_mode==='dry_run'&&adapter.mode!=='dry_run')fail('DRY_RUN_ADAPTER_REQUIRED','Dry-run adapter required');const started=stamp(),operations=[];try{for(const action of plan.resource_actions)operations.push(adapter.executeAction(action,{plan:clone(plan)}));const canary=runCanary(plan),failed=canary.some(check=>check.status==='failed');let rollback=false;if(failed){adapter.rollback({plan:clone(plan),operations:clone(operations)});rollback=true;for(const operation of operations)operation.status='rolled_back';}const execution={schema_version:'0.1.0',execution_id:id('deployment'),plan_id:plan.plan_id,mode:plan.execution_mode,status:failed?'rolled_back':plan.execution_mode==='dry_run'?'simulated':'succeeded',operations,canary_checks:canary,rollback_triggered:rollback,external_changes:plan.execution_mode==='dry_run'?0:operations.filter(x=>x.status==='applied').length,started_at:started,finished_at:stamp()};validate('deployment-execution',execution);plan.status=failed?'failed':plan.execution_mode==='dry_run'?'simulated':'executed';executions.set(execution.execution_id,execution);return clone(execution);}catch(error){plan.status='failed';throw error;}}
 function drift(actor,planId,observed=[]){const plan=plans.get(planId);if(!plan)fail('PLAN_NOT_FOUND','Plan not found');authorize(actor,'drift.read',plan.tenant_id);const byResource=new Map(observed.map(item=>[item.resource,item]));const differences=[];for(const action of plan.resource_actions){const item=byResource.get(action.resource);if(!item){differences.push({resource:action.resource,field:'presence',expected:true,observed:false,severity:'critical'});continue;}if(item.logical_ref!==action.logical_ref)differences.push({resource:action.resource,field:'logical_ref',expected:action.logical_ref,observed:item.logical_ref??null,severity:'critical'});if(item.status&&item.status!=='ready')differences.push({resource:action.resource,field:'status',expected:'ready',observed:item.status,severity:'warning'});}const report={schema_version:'0.1.0',report_id:id('drift'),plan_id:plan.plan_id,status:differences.length?'drifted':'in_sync',differences,secrets_compared:false,generated_at:stamp()};validate('deployment-drift-report',report);return report;}
 return {buildUploadPlan,createPlan,approvePlan,preflight,execute,drift,_state:{plans,executions}};
}
module.exports={createDeploymentService,createDryRunAdapter,createUnconfiguredCloudflareAdapter,requiredConfiguration,cleanHostname,hash};
