'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const Ajv=require('ajv/dist/2020'),addFormats=require('ajv-formats');
const ROOT=path.resolve(__dirname,'../..');
const schemaNames=['service-identity','workload-identity-binding','service-credential','authorization-policy','access-decision','signing-key-record','key-rotation','artifact-attestation','privileged-operation','operation-approval','break-glass-session','security-audit-entry','audit-verification','security-rehearsal'];
const ajv=new Ajv({allErrors:true,strict:false,validateFormats:true});addFormats(ajv);
const validators=Object.fromEntries(schemaNames.map(name=>[name,ajv.compile(JSON.parse(fs.readFileSync(path.join(ROOT,'contracts',`${name}.schema.json`),'utf8')))]));
const canonical=value=>JSON.stringify(value,(_key,current)=>current&&typeof current==='object'&&!Array.isArray(current)?Object.fromEntries(Object.entries(current).sort(([a],[b])=>a.localeCompare(b))):current);
const sha=value=>crypto.createHash('sha256').update(Buffer.isBuffer(value)?value:typeof value==='string'?value:canonical(value)).digest('hex');
const clone=value=>JSON.parse(JSON.stringify(value));
const fail=(code,message,details)=>Object.assign(new Error(message),{code,details});
const riskRank={low:1,medium:2,high:3,critical:4};
function validate(name,value){const check=validators[name];if(!check(value))throw fail('SCHEMA_INVALID',`${name} invalid`,check.errors);return value;}
function b64(value){return Buffer.from(value).toString('base64url');}
function unb64(value){return Buffer.from(value,'base64url').toString('utf8');}
function actorId(actor){return actor?.actor_id||actor?.identity_id||'anonymous';}
function hasRole(actor,role){return Array.isArray(actor?.roles)&&actor.roles.includes(role);}
function requireRole(actor,...roles){if(!roles.some(role=>hasRole(actor,role)))throw fail('ROLE_REQUIRED',`One of these roles is required: ${roles.join(', ')}`);}
function createKeyRecord(now,id){const pair=crypto.generateKeyPairSync('ed25519'),publicDer=pair.publicKey.export({type:'spki',format:'der'});return {record:{schema_version:'0.1.0',key_id:id,algorithm:'Ed25519',status:'active',public_key_fingerprint:sha(publicDer),created_at:now().toISOString(),grace_ends_at:null,retired_at:null},privateKey:pair.privateKey,publicKey:pair.publicKey};}

function createZeroTrustSecurity({now=()=>new Date(),maximumCredentialTtlSeconds=900}={}){
  let counter=0,currentKeyId='sigk-root-001';
  const identities=new Map(),bindings=new Map(),credentials=new Map(),policies=new Map(),keys=new Map(),rotations=new Map(),attestations=new Map(),operations=new Map(),approvals=new Map(),breakGlass=new Map(),auditEntries=[],accessDecisions=[];
  keys.set(currentKeyId,createKeyRecord(now,currentKeyId));
  const stamp=()=>now().toISOString(),id=(prefix,salt='')=>`${prefix}-${sha(`${prefix}|${salt}|${counter++}|${stamp()}`).slice(0,24)}`;
  function signText(text,keyId=currentKeyId){const key=keys.get(keyId);if(!key)throw fail('KEY_NOT_FOUND','Signing key not found');return crypto.sign(null,Buffer.from(text),key.privateKey).toString('base64url');}
  function verifyText(text,signature,keyId){const key=keys.get(keyId);return Boolean(key&&crypto.verify(null,Buffer.from(text),key.publicKey,Buffer.from(signature,'base64url')));}
  function audit(actor,action,subject,decision='success',details={}){
    const previous=auditEntries.at(-1)?.entry_hash??null,base={sequence:auditEntries.length+1,entry_id:id('saudit',action),actor_ref:actorId(actor),action,subject_ref:String(subject),decision,details_digest:sha(details),previous_hash:previous,key_ref:currentKeyId,created_at:stamp()},entryHash=sha(base),entry={schema_version:'0.1.0',...base,entry_hash:entryHash,signature:signText(entryHash)};
    validate('security-audit-entry',entry);auditEntries.push(entry);return clone(entry);
  }
  function deny(actor,action,subject,code,message,details={}){audit(actor,action,subject,'denied',{code,...details});throw fail(code,message,details);}
  function registerIdentity(actor,spec){requireRole(actor,'security_admin');if(identities.has(spec.identity_id))throw fail('IDENTITY_EXISTS','Identity already exists');const value={schema_version:'0.1.0',identity_id:spec.identity_id,display_name:spec.display_name,status:'active',tenant_scopes:[...new Set(spec.tenant_scopes)],capabilities:[...new Set(spec.capabilities)],labels:spec.labels??{},created_at:stamp(),updated_at:stamp()};validate('service-identity',value);identities.set(value.identity_id,value);audit(actor,'identity.registered',value.identity_id,'success',{capabilities:value.capabilities,tenant_scopes:value.tenant_scopes});return clone(value);}
  function setIdentityStatus(actor,identityId,status){requireRole(actor,'security_admin');const value=identities.get(identityId);if(!value)throw fail('IDENTITY_NOT_FOUND','Identity not found');if(!['active','suspended','revoked'].includes(status))throw fail('IDENTITY_STATUS_INVALID','Unsupported identity status');value.status=status;value.updated_at=stamp();audit(actor,'identity.status_changed',identityId,'success',{status});return clone(value);}
  function bindWorkload(actor,spec){requireRole(actor,'security_admin');const identity=identities.get(spec.identity_ref);if(!identity)throw fail('IDENTITY_NOT_FOUND','Identity not found');const value={schema_version:'0.1.0',binding_id:id('wbind',spec.subject),identity_ref:spec.identity_ref,runtime:spec.runtime,subject:spec.subject,environment:spec.environment,status:'active',created_at:stamp(),revoked_at:null};validate('workload-identity-binding',value);bindings.set(value.binding_id,value);audit(actor,'workload.bound',value.binding_id,'success',{identity_ref:value.identity_ref,environment:value.environment});return clone(value);}
  function definePolicy(actor,spec){requireRole(actor,'security_admin');const previous=policies.get(spec.policy_id),value={schema_version:'0.1.0',policy_id:spec.policy_id,version:(previous?.version??0)+1,status:'active',capabilities:[...new Set(spec.capabilities)],environments:[...new Set(spec.environments)],maximum_risk:spec.maximum_risk??'medium',require_mfa:Boolean(spec.require_mfa),created_at:stamp()};validate('authorization-policy',value);policies.set(value.policy_id,value);audit(actor,'policy.activated',value.policy_id,'success',{version:value.version});return clone(value);}
  function issueCredential(actor,spec){requireRole(actor,'security_admin','token_broker');const identity=identities.get(spec.identity_ref);if(!identity||identity.status!=='active')return deny(actor,'credential.issue',spec.identity_ref,'IDENTITY_INACTIVE','Identity is missing or inactive');const ttl=spec.ttl_seconds;if(!Number.isInteger(ttl)||ttl<30||ttl>maximumCredentialTtlSeconds)throw fail('CREDENTIAL_TTL_INVALID','Credential TTL is outside the allowed range');const requestedTenants=spec.tenant_scopes??identity.tenant_scopes,requestedCapabilities=spec.capabilities??identity.capabilities;if(!requestedTenants.every(value=>identity.tenant_scopes.includes(value))||!requestedCapabilities.every(value=>identity.capabilities.includes(value)))return deny(actor,'credential.issue',spec.identity_ref,'SCOPE_ESCALATION','Credential exceeds identity grants');const issued=now(),expires=new Date(issued.getTime()+ttl*1000),credentialId=id('cred',identity.identity_id),claims={v:1,jti:credentialId,sub:identity.identity_id,kid:currentKeyId,aud:spec.audience,ten:requestedTenants,cap:requestedCapabilities,iat:Math.floor(issued.getTime()/1000),exp:Math.floor(expires.getTime()/1000)},payload=b64(canonical(claims)),token=`hct1.${payload}.${signText(payload)}`,record={schema_version:'0.1.0',credential_id:credentialId,identity_ref:identity.identity_id,key_ref:currentKeyId,audience:spec.audience,tenant_scopes:requestedTenants,capabilities:requestedCapabilities,issued_at:issued.toISOString(),expires_at:expires.toISOString(),token_hash:sha(token),status:'active',revoked_at:null};validate('service-credential',record);credentials.set(credentialId,record);audit(actor,'credential.issued',credentialId,'success',{identity_ref:identity.identity_id,ttl_seconds:ttl});return {credential:clone(record),token};}
  function revokeCredential(actor,credentialId){requireRole(actor,'security_admin');const record=credentials.get(credentialId);if(!record)throw fail('CREDENTIAL_NOT_FOUND','Credential not found');record.status='revoked';record.revoked_at=stamp();audit(actor,'credential.revoked',credentialId);return clone(record);}
  function decide(identityRef,tenantId,capability,audience,result,reasonCode,policyRef=null){const value={schema_version:'0.1.0',decision_id:id('adec',identityRef),identity_ref:identityRef,tenant_id:tenantId,capability,audience,result,reason_code:reasonCode,policy_ref:policyRef,decided_at:stamp()};validate('access-decision',value);accessDecisions.push(value);return value;}
  function verifyCredential(token,request){let claims,record,identity;try{if(typeof token!=='string')throw fail('TOKEN_MALFORMED','Credential is missing');const parts=token.split('.');if(parts.length!==3||parts[0]!=='hct1')throw fail('TOKEN_MALFORMED','Credential format is invalid');claims=JSON.parse(unb64(parts[1]));if(!verifyText(parts[1],parts[2],claims.kid))throw fail('TOKEN_SIGNATURE_INVALID','Credential signature is invalid');const key=keys.get(claims.kid)?.record;if(!key||key.status==='revoked'||key.status==='retired'&&Date.parse(key.grace_ends_at??0)<=now().getTime())throw fail('TOKEN_KEY_INACTIVE','Credential signing key is inactive');record=credentials.get(claims.jti);identity=identities.get(claims.sub);if(!record||record.status!=='active'||record.token_hash!==sha(token))throw fail('TOKEN_REVOKED','Credential is revoked or unknown');if(!identity||identity.status!=='active')throw fail('IDENTITY_INACTIVE','Identity is inactive');if(claims.exp<=Math.floor(now().getTime()/1000)){record.status='expired';throw fail('TOKEN_EXPIRED','Credential has expired');}if(claims.aud!==request.audience)throw fail('AUDIENCE_MISMATCH','Credential audience does not match');if(!claims.ten.includes(request.tenant_id))throw fail('TENANT_SCOPE_DENIED','Tenant is outside credential scope');if(!claims.cap.includes(request.capability))throw fail('CAPABILITY_DENIED','Capability is outside credential scope');const environment=request.context?.environment??'local',risk=request.context?.risk??'low',policy=[...policies.values()].find(item=>item.status==='active'&&item.capabilities.includes(request.capability));if(!policy)throw fail('POLICY_NOT_FOUND','No active policy grants this capability');if(!policy.environments.includes(environment))throw fail('ENVIRONMENT_DENIED','Environment is outside policy');if(riskRank[risk]>riskRank[policy.maximum_risk])throw fail('RISK_DENIED','Risk exceeds policy allowance');if(policy.require_mfa&&!request.context?.mfa)throw fail('MFA_REQUIRED','Policy requires MFA');const decision=decide(identity.identity_id,request.tenant_id,request.capability,request.audience,'allow','POLICY_ALLOWED',policy.policy_id);audit({actor_id:identity.identity_id},'access.allowed',decision.decision_id,'success',{capability:request.capability,tenant_id:request.tenant_id});return {claims:clone(claims),decision:clone(decision)};}catch(error){const identityRef=identity?.identity_id??claims?.sub??'unknown-identity',decision=decide(identityRef,request.tenant_id,request.capability,request.audience,'deny',error.code??'ACCESS_DENIED',null);audit({actor_id:identityRef},'access.denied',decision.decision_id,'denied',{reason:error.code??'ACCESS_DENIED'});throw error;}}
  function rotateSigningKey(actor,{grace_seconds=300}={}){requireRole(actor,'security_admin');if(!Number.isInteger(grace_seconds)||grace_seconds<0||grace_seconds>86400)throw fail('KEY_GRACE_INVALID','Key grace period is invalid');const previous=keys.get(currentKeyId),created=now(),nextId=id('sigk','rotation'),next=createKeyRecord(now,nextId),graceEnds=new Date(created.getTime()+grace_seconds*1000).toISOString();previous.record.status='retiring';previous.record.grace_ends_at=graceEnds;keys.set(nextId,next);currentKeyId=nextId;const value={schema_version:'0.1.0',rotation_id:id('krot',nextId),previous_key_ref:previous.record.key_id,new_key_ref:nextId,grace_ends_at:graceEnds,rotated_by:actorId(actor),status:'active_grace',created_at:created.toISOString(),completed_at:null};validate('key-rotation',value);rotations.set(value.rotation_id,value);audit(actor,'key.rotated',value.rotation_id,'success',{previous_key_ref:value.previous_key_ref,new_key_ref:value.new_key_ref});return clone(value);}
  function retireExpiredKeys(actor){requireRole(actor,'security_admin');let retired=0;for(const key of keys.values())if(key.record.status==='retiring'&&Date.parse(key.record.grace_ends_at)<=now().getTime()){key.record.status='retired';key.record.retired_at=stamp();retired++;for(const rotation of rotations.values())if(rotation.previous_key_ref===key.record.key_id){rotation.status='completed';rotation.completed_at=stamp();}}audit(actor,'key.retirement_sweep','signing-keys','success',{retired});return retired;}
  function attestArtifact(token,request){const verified=verifyCredential(token,{audience:request.audience,tenant_id:request.tenant_id,capability:'artifact.attest',context:{environment:request.environment,risk:'medium'}}),base={attestation_id:id('attest',request.artifact_name),artifact_name:request.artifact_name,artifact_digest:request.artifact_digest,manifest_digest:request.manifest_digest,signer_ref:verified.claims.sub,key_ref:currentKeyId,environment:request.environment,created_at:stamp()},signature=signText(canonical(base)),value={schema_version:'0.1.0',...base,signature,status:'verified'};validate('artifact-attestation',value);attestations.set(value.attestation_id,value);audit({actor_id:value.signer_ref},'artifact.attested',value.attestation_id,'success',{artifact_digest:value.artifact_digest});return clone(value);}
  function verifyAttestation(attestationId){const value=attestations.get(attestationId);if(!value)return false;const {schema_version,status,signature,...base}=value;void schema_version;void status;return verifyText(canonical(base),signature,value.key_ref);}
  function requestPrivilegedOperation(actor,spec){requireRole(actor,'operator','security_admin','incident_commander');if(!['high','critical'].includes(spec.risk))throw fail('RISK_INVALID','Privileged operation risk must be high or critical');const requested=now(),value={schema_version:'0.1.0',operation_id:id('pop',spec.capability),requester_ref:actorId(actor),capability:spec.capability,resource:spec.resource,risk:spec.risk,required_approvals:spec.risk==='critical'?2:1,status:'pending',justification:spec.justification,requested_at:requested.toISOString(),expires_at:new Date(requested.getTime()+(spec.ttl_seconds??900)*1000).toISOString(),executed_at:null};validate('privileged-operation',value);operations.set(value.operation_id,value);audit(actor,'privileged.requested',value.operation_id,'success',{risk:value.risk,capability:value.capability});return clone(value);}
  function approvePrivilegedOperation(actor,operationId,{decision='approve',comment='Reviewed and authorized'}={}){requireRole(actor,'security_approver');const operation=operations.get(operationId);if(!operation)throw fail('OPERATION_NOT_FOUND','Privileged operation not found');if(operation.status!=='pending'&&operation.status!=='approved')throw fail('OPERATION_NOT_PENDING','Operation is not awaiting approval');if(Date.parse(operation.expires_at)<=now().getTime()){operation.status='expired';throw fail('OPERATION_EXPIRED','Operation request has expired');}if(operation.requester_ref===actorId(actor))return deny(actor,'privileged.approve',operationId,'SELF_APPROVAL_DENIED','Requester cannot approve the operation');const existing=[...approvals.values()].find(value=>value.operation_ref===operationId&&value.approver_ref===actorId(actor));if(existing)throw fail('DUPLICATE_APPROVAL','Approver already decided');const value={schema_version:'0.1.0',approval_id:id('pappr',operationId),operation_ref:operationId,approver_ref:actorId(actor),decision,comment,decided_at:stamp()};validate('operation-approval',value);approvals.set(value.approval_id,value);if(decision==='reject')operation.status='rejected';else if([...approvals.values()].filter(item=>item.operation_ref===operationId&&item.decision==='approve').length>=operation.required_approvals)operation.status='approved';audit(actor,`privileged.${decision}`,operationId,decision==='approve'?'success':'denied',{approval_id:value.approval_id});return {approval:clone(value),operation:clone(operation)};}
  function executePrivilegedOperation(actor,operationId,executor){requireRole(actor,'privileged_executor');const operation=operations.get(operationId);if(!operation)throw fail('OPERATION_NOT_FOUND','Privileged operation not found');if(operation.status!=='approved')return deny(actor,'privileged.execute',operationId,'OPERATION_NOT_APPROVED','Operation is not fully approved');if(Date.parse(operation.expires_at)<=now().getTime()){operation.status='expired';throw fail('OPERATION_EXPIRED','Operation request has expired');}const involved=new Set([operation.requester_ref,...[...approvals.values()].filter(item=>item.operation_ref===operationId&&item.decision==='approve').map(item=>item.approver_ref)]);if(involved.has(actorId(actor)))return deny(actor,'privileged.execute',operationId,'SEPARATION_OF_DUTIES_REQUIRED','Executor must be independent');const result=executor({capability:operation.capability,resource:operation.resource,operation_id:operation.operation_id});operation.status='executed';operation.executed_at=stamp();audit(actor,'privileged.executed',operationId,'success',{result_digest:sha(result)});return {operation:clone(operation),result:clone(result)};}
  function requestBreakGlass(actor,spec){requireRole(actor,'incident_responder');const ttl=spec.ttl_seconds??300;if(!Number.isInteger(ttl)||ttl<60||ttl>900)throw fail('BREAK_GLASS_TTL_INVALID','Break-glass TTL must be between 60 and 900 seconds');const created=now(),value={schema_version:'0.1.0',session_id:id('bglass',spec.ticket_ref),requester_ref:actorId(actor),approver_ref:null,ticket_ref:spec.ticket_ref,reason:spec.reason,capabilities:[...new Set(spec.capabilities)],tenant_scopes:[...new Set(spec.tenant_scopes)],status:'pending',created_at:created.toISOString(),expires_at:new Date(created.getTime()+ttl*1000).toISOString(),closed_at:null};validate('break-glass-session',value);breakGlass.set(value.session_id,value);audit(actor,'break_glass.requested',value.session_id,'success',{ticket_ref:value.ticket_ref});return clone(value);}
  function approveBreakGlass(actor,sessionId){requireRole(actor,'security_approver');const session=breakGlass.get(sessionId);if(!session)throw fail('BREAK_GLASS_NOT_FOUND','Break-glass request not found');if(session.requester_ref===actorId(actor))return deny(actor,'break_glass.approve',sessionId,'SELF_APPROVAL_DENIED','Requester cannot approve break-glass');if(session.status!=='pending')throw fail('BREAK_GLASS_NOT_PENDING','Break-glass request is not pending');if(Date.parse(session.expires_at)<=now().getTime()){session.status='expired';throw fail('BREAK_GLASS_EXPIRED','Break-glass request expired');}session.approver_ref=actorId(actor);session.status='active';audit(actor,'break_glass.activated',sessionId,'success',{requester_ref:session.requester_ref});return clone(session);}
  function authorizeBreakGlass(actor,sessionId,{tenant_id,capability}){const session=breakGlass.get(sessionId);if(!session||session.requester_ref!==actorId(actor))throw fail('BREAK_GLASS_DENIED','Session does not belong to requester');if(session.status!=='active'||Date.parse(session.expires_at)<=now().getTime()){if(session.status==='active')session.status='expired';throw fail('BREAK_GLASS_EXPIRED','Break-glass session is inactive or expired');}if(!session.tenant_scopes.includes(tenant_id)||!session.capabilities.includes(capability))return deny(actor,'break_glass.access',sessionId,'BREAK_GLASS_SCOPE_DENIED','Request exceeds break-glass scope');audit(actor,'break_glass.access',sessionId,'success',{tenant_id,capability});return true;}
  function revokeBreakGlass(actor,sessionId){requireRole(actor,'security_admin','security_approver');const session=breakGlass.get(sessionId);if(!session)throw fail('BREAK_GLASS_NOT_FOUND','Break-glass session not found');session.status='revoked';session.closed_at=stamp();audit(actor,'break_glass.revoked',sessionId);return clone(session);}
  function verifyAudit(){let previous=null,firstFailure=null,chainValid=true,signaturesValid=true;for(const entry of auditEntries){const {schema_version,entry_hash,signature,...base}=entry;void schema_version;const expected=sha(base),chain=base.previous_hash===previous&&expected===entry_hash,signed=verifyText(entry_hash,signature,entry.key_ref);if(!chain){chainValid=false;firstFailure??=entry.sequence;}if(!signed){signaturesValid=false;firstFailure??=entry.sequence;}previous=entry.entry_hash;}const value={schema_version:'0.1.0',verification_id:id('averify','audit'),entries_scanned:auditEntries.length,chain_valid:chainValid,signatures_valid:signaturesValid,first_failure_sequence:firstFailure,status:chainValid&&signaturesValid?'passed':'failed',verified_at:stamp()};validate('audit-verification',value);return value;}
  function runRehearsal(actor,checks){requireRole(actor,'security_admin');const started=stamp(),results=checks.map(check=>{try{return Boolean(check())}catch{return false;}}),passed=results.filter(Boolean).length,value={schema_version:'0.1.0',rehearsal_id:id('srehearse','zero-trust'),scenario:'Zero-trust local synthetic rehearsal',checks_total:results.length,checks_passed:passed,checks_failed:results.length-passed,external_changes:false,status:passed===results.length?'passed':'failed',started_at:started,completed_at:stamp()};validate('security-rehearsal',value);audit(actor,'security.rehearsal',value.rehearsal_id,value.status==='passed'?'success':'failure',{checks_passed:passed,checks_total:results.length});return value;}
  function summary(){return {identities:identities.size,bindings:bindings.size,credentials:credentials.size,policies:policies.size,keys:keys.size,rotations:rotations.size,attestations:attestations.size,operations:operations.size,approvals:approvals.size,break_glass_sessions:breakGlass.size,access_decisions:accessDecisions.length,audit_entries:auditEntries.length,active_key_ref:currentKeyId};}
  return {registerIdentity,setIdentityStatus,bindWorkload,definePolicy,issueCredential,revokeCredential,verifyCredential,rotateSigningKey,retireExpiredKeys,attestArtifact,verifyAttestation,requestPrivilegedOperation,approvePrivilegedOperation,executePrivilegedOperation,requestBreakGlass,approveBreakGlass,authorizeBreakGlass,revokeBreakGlass,verifyAudit,runRehearsal,summary,listAudit:()=>clone(auditEntries),listKeys:()=>clone([...keys.values()].map(value=>value.record)),listDecisions:()=>clone(accessDecisions),getOperation:operationId=>clone(operations.get(operationId)??null),getBreakGlass:sessionId=>clone(breakGlass.get(sessionId)??null),_auditEntries:auditEntries};
}
module.exports={createZeroTrustSecurity,canonical,sha,validators};
