'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {validate}=require('../site-engine/index.cjs');
const encode=v=>JSON.stringify(v,null,2)+'\n',sha=value=>crypto.createHash('sha256').update(Buffer.isBuffer(value)?value:typeof value==='string'?value:encode(value)).digest('hex'),b64=v=>Buffer.from(v).toString('base64url'),unb64=v=>Buffer.from(v,'base64url');
const permissions={owner:new Set(['record.create','record.read','asset.quarantine']),operator:new Set(['record.read','asset.release']),admin:new Set(['record.create','record.read','record.delete','asset.quarantine','asset.release','retention.evaluate']),system:new Set(['record.create','record.read','record.delete','asset.quarantine','asset.release','retention.evaluate'])};
function keyFromBase64(value,label='key'){const key=Buffer.from(String(value||''),'base64');if(key.length!==32)throw Object.assign(new Error(`${label} must decode to exactly 32 bytes`),{code:'KEY_INVALID'});return key;}
function safeId(value){if(!/^[a-z0-9][a-z0-9-]{2,100}$/.test(value))throw Object.assign(new Error('Unsafe record identifier'),{code:'ID_UNSAFE'});return value;}
function authorize(ctx,action,tenantId){if(!ctx||!permissions[ctx.role]?.has(action)||(ctx.role==='owner'&&ctx.tenant_id!==tenantId))throw Object.assign(new Error('Access denied'),{code:'ACCESS_DENIED'});return true;}
function createFoundation(root,encryptionKey,auditKey){
 if(!Buffer.isBuffer(encryptionKey)||encryptionKey.length!==32)throw Object.assign(new Error('Encryption key must be 32 bytes'),{code:'KEY_INVALID'});if(!Buffer.isBuffer(auditKey)||auditKey.length<32)throw Object.assign(new Error('Audit key must be at least 32 bytes'),{code:'KEY_INVALID'});
 const vault=path.join(root,'vault'),tombstones=path.join(root,'tombstones'),auditFile=path.join(root,'audit.jsonl');fs.mkdirSync(vault,{recursive:true});fs.mkdirSync(tombstones,{recursive:true});
 const file=id=>path.join(vault,safeId(id)+'.enc.json');
 function entries(){if(!fs.existsSync(auditFile))return [];return fs.readFileSync(auditFile,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);}
 function audit(ctx,action,resource,result='success',occurred_at=new Date().toISOString()){
  const prior=entries(),sequence=prior.length+1,previous_hash=prior.length?prior.at(-1).event_hash:null,base={schema_version:'0.1.0',sequence,event_id:'aud-'+crypto.randomBytes(12).toString('hex'),occurred_at,actor:{actor_id:ctx.actor_id,role:ctx.role,tenant_id:ctx.tenant_id??null},action,resource,result,previous_hash},event_hash=sha(base),signature=crypto.createHmac('sha256',auditKey).update(event_hash).digest('hex'),entry={...base,event_hash,signature};validate('audit-entry',entry);fs.appendFileSync(auditFile,JSON.stringify(entry)+'\n');return entry;
 }
 function denied(ctx,action,resource){try{audit(ctx,action==='asset.release'?'access.denied':'access.denied',resource,'denied');}catch{}throw Object.assign(new Error('Access denied'),{code:'ACCESS_DENIED'});}
 function check(ctx,action,tenantId,resource){try{return authorize(ctx,action,tenantId);}catch{return denied(ctx,action,resource);}}
 function putJson(ctx,record,now=new Date().toISOString()){
  safeId(record.record_id);const resource={record_id:record.record_id,tenant_id:record.tenant_id,record_type:record.record_type,content_hash:null};check(ctx,'record.create',record.tenant_id,resource);if(fs.existsSync(file(record.record_id)))throw Object.assign(new Error('Record already exists'),{code:'RECORD_EXISTS'});
  const plaintext=Buffer.from(encode(record.payload)),plaintext_sha256=sha(plaintext),iv=crypto.randomBytes(12),aad=Buffer.from(`${record.record_id}|${record.tenant_id}|${record.record_type}|${now}`),cipher=crypto.createCipheriv('aes-256-gcm',encryptionKey,iv);cipher.setAAD(aad);const ciphertext=Buffer.concat([cipher.update(plaintext),cipher.final()]),authTag=cipher.getAuthTag();const envelope={schema_version:'0.1.0',record_id:record.record_id,tenant_id:record.tenant_id,record_type:record.record_type,algorithm:'aes-256-gcm',iv:b64(iv),auth_tag:b64(authTag),ciphertext:b64(ciphertext),plaintext_sha256,retention:{class:record.retention_class,expires_at:record.expires_at??null,deletion_status:'active'},created_at:now,updated_at:now};validate('private-vault-record',envelope);const temp=file(record.record_id)+'.'+crypto.randomBytes(6).toString('hex')+'.tmp';fs.writeFileSync(temp,encode(envelope),{flag:'wx'});fs.renameSync(temp,file(record.record_id));audit(ctx,'record.create',{...resource,content_hash:plaintext_sha256});return envelope;
 }
 function getJson(ctx,recordId){const envelope=JSON.parse(fs.readFileSync(file(recordId),'utf8')),resource={record_id:envelope.record_id,tenant_id:envelope.tenant_id,record_type:envelope.record_type,content_hash:envelope.plaintext_sha256};check(ctx,'record.read',envelope.tenant_id,resource);const aad=Buffer.from(`${envelope.record_id}|${envelope.tenant_id}|${envelope.record_type}|${envelope.created_at}`),decipher=crypto.createDecipheriv('aes-256-gcm',encryptionKey,unb64(envelope.iv));decipher.setAAD(aad);decipher.setAuthTag(unb64(envelope.auth_tag));let plaintext;try{plaintext=Buffer.concat([decipher.update(unb64(envelope.ciphertext)),decipher.final()]);}catch{throw Object.assign(new Error('Ciphertext authentication failed'),{code:'DECRYPT_FAILED'});}if(sha(plaintext)!==envelope.plaintext_sha256)throw Object.assign(new Error('Plaintext hash mismatch'),{code:'INTEGRITY_FAILED'});audit(ctx,'record.read',resource);return {envelope,payload:JSON.parse(plaintext.toString('utf8'))};}
 function remove(ctx,recordId,reason,now=new Date().toISOString()){const envelope=JSON.parse(fs.readFileSync(file(recordId),'utf8')),resource={record_id:envelope.record_id,tenant_id:envelope.tenant_id,record_type:envelope.record_type,content_hash:envelope.plaintext_sha256};check(ctx,'record.delete',envelope.tenant_id,resource);if(!reason||String(reason).length<5)throw Object.assign(new Error('Deletion reason required'),{code:'DELETION_REASON_REQUIRED'});fs.unlinkSync(file(recordId));const tombstone={record_id:recordId,tenant_id:envelope.tenant_id,record_type:envelope.record_type,deleted_at:now,reason:String(reason),deleted_content_hash:envelope.plaintext_sha256};fs.writeFileSync(path.join(tombstones,safeId(recordId)+'.json'),encode(tombstone),{flag:'wx'});audit(ctx,'record.delete',resource);return tombstone;}
 function retention(ctx,now=new Date().toISOString()){authorize(ctx,'retention.evaluate',ctx.tenant_id??'system');const current=Date.parse(now),records=fs.readdirSync(vault).filter(x=>x.endsWith('.enc.json')).map(name=>JSON.parse(fs.readFileSync(path.join(vault,name),'utf8'))),due=records.filter(r=>r.retention.class!=='legal_hold'&&r.retention.expires_at&&Date.parse(r.retention.expires_at)<=current).map(r=>({record_id:r.record_id,tenant_id:r.tenant_id,expires_at:r.retention.expires_at,action:'request_deletion'}));audit(ctx,'retention.evaluate',{record_id:'retention-scan',tenant_id:ctx.tenant_id??'system',record_type:'retention_report',content_hash:sha(due)});return due;}
 function verifyAudit(){const rows=entries();let previous=null;for(let i=0;i<rows.length;i++){const row=rows[i],{event_hash,signature,...base}=row;if(row.sequence!==i+1||row.previous_hash!==previous||sha(base)!==event_hash||crypto.createHmac('sha256',auditKey).update(event_hash).digest('hex')!==signature)return {valid:false,entries:rows.length,failed_sequence:i+1};validate('audit-entry',row);previous=event_hash;}return {valid:true,entries:rows.length,head:previous};}
 return {putJson,getJson,remove,retention,verifyAudit,paths:{vault,tombstones,auditFile}};
}
function releaseAsset(asset){validate('asset-intake',asset);if(asset.security.scan_status!=='clean'||asset.security.active_content_detected||asset.rights.status!=='approved')throw Object.assign(new Error('Asset cannot leave quarantine'),{code:'ASSET_BLOCKED'});const released=structuredClone(asset);released.security.quarantine_status='released';validate('asset-intake',released);return released;}
module.exports={createFoundation,releaseAsset,keyFromBase64,authorize,sha,encode};
