'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {validate}=require('../site-engine/index.cjs');const {detectType,dimensions,hasActiveContent}=require('../asset-pipeline/index.cjs');
const encode=value=>JSON.stringify(value,null,2)+'\n';const sha256=value=>crypto.createHash('sha256').update(Buffer.isBuffer(value)?value:encode(value)).digest('hex');const shortHash=value=>sha256(value).slice(0,16);const clone=value=>structuredClone(value);
function fail(message,code){throw Object.assign(new Error(message),{code});}
function buildPilotRegistry(root,generatedAt='2026-09-30T23:30:00Z'){
 const definitions=JSON.parse(fs.readFileSync(path.join(root,'pilot/asset-sources.json'),'utf8'));if(definitions.synthetic!==true)fail('Pilot asset sources must be synthetic','ASSET_SOURCE_BLOCKED');
 const ids=new Set(),names=new Set();const assets=definitions.assets.map(definition=>{if(ids.has(definition.asset_id)||names.has(definition.filename))fail('Duplicate asset definition','ASSET_DUPLICATE');ids.add(definition.asset_id);names.add(definition.filename);const bytes=fs.readFileSync(path.join(root,'pilot/assets',definition.filename)),detected=detectType(bytes),measured=dimensions(bytes,detected);if(!detected||hasActiveContent(bytes,detected))fail('Pilot asset inspection failed','ASSET_INSPECTION_FAILED');if(definition.kind==='photo'&&!measured)fail('Pilot photo dimensions missing','DIMENSIONS_INVALID');return {asset_id:definition.asset_id,filename:definition.filename,kind:definition.kind,detected_type:detected,bytes:bytes.length,content_sha256:sha256(bytes),dimensions:measured,state:'synthetic_fixture',eligibility:{local_demo:true,private:false,production:false},rights:{status:'approved_internal_fixture',evidence:'Fixture sintético generado y reservado para demostraciones locales.'}};});
 const registry={schema_version:'0.1.0',registry_id:`registry-${shortHash(assets)}`,environment:'local_demo',assets,generated_at:generatedAt};validate('site-asset-registry',registry);return registry;
}
function assetMap(registry){validate('site-asset-registry',registry);return new Map(registry.assets.map(asset=>[asset.asset_id,asset]));}
function assertEligible(registry,assetId,mode='local_demo'){const asset=assetMap(registry).get(assetId);if(!asset)fail('Asset is not registered','ASSET_UNKNOWN');if(!['local_demo','private','production'].includes(mode)||asset.state==='revoked'||asset.eligibility[mode]!==true)fail('Asset is not eligible for this environment','ASSET_INELIGIBLE');if(mode==='production'&&asset.state!=='web_ready')fail('Production requires web-ready assets','ASSET_NOT_WEB_READY');return asset;}
function assertCatalogAssets(registry,catalog,assetsRoot,mode='local_demo'){const seen=new Set();for(const item of catalog.items){if(!item.asset_id||seen.has(item.asset_id))fail('Catalog asset reference missing or duplicated','CATALOG_ASSET_INVALID');seen.add(item.asset_id);const asset=assertEligible(registry,item.asset_id,mode);if(asset.filename!==item.image)fail('Catalog filename differs from registry','CATALOG_ASSET_MISMATCH');const actual=fs.readFileSync(path.join(assetsRoot,asset.filename));if(sha256(actual)!==asset.content_sha256||actual.length!==asset.bytes)fail('Asset bytes differ from registry','ASSET_STALE');}return true;}
function createUsageIndex(registry,profiles,catalog,generatedAt='2026-09-30T23:31:00Z'){const buildId=`visual-${shortHash({registry_id:registry.registry_id,profiles:profiles.map(x=>x.id),catalog:catalog.items.map(x=>x.id)})}`,first=catalog.items[0]?.asset_id;const entries=registry.assets.map(asset=>{const item=catalog.items.find(candidate=>candidate.asset_id===asset.asset_id);if(!item)fail('Registered asset missing from catalog','CATALOG_REFERENCE_MISSING');const usages=[];for(const profile of profiles){usages.push({site_id:profile.id,page_path:`${profile.id}/index.html`,slot:'catalog_card'});if(asset.asset_id===first)usages.push({site_id:profile.id,page_path:`${profile.id}/index.html`,slot:'hero'});usages.push({site_id:profile.id,page_path:`${profile.id}/${item.id}.html`,slot:'detail_hero'});}return {asset_id:asset.asset_id,content_sha256:asset.content_sha256,usages};});const index={schema_version:'0.1.0',index_id:`usage-${shortHash({buildId,entries})}`,build_id:buildId,registry_id:registry.registry_id,entries,generated_at:generatedAt};validate('asset-usage-index',index);return index;}
function revokeAsset(registry,index,assetId,reason){validate('site-asset-registry',registry);validate('asset-usage-index',index);if(!reason||String(reason).length<5)fail('Revocation reason required','REVOCATION_REASON_REQUIRED');const next=clone(registry),asset=next.assets.find(item=>item.asset_id===assetId);if(!asset)fail('Asset is not registered','ASSET_UNKNOWN');asset.state='revoked';asset.eligibility={local_demo:false,private:false,production:false};asset.rights={status:'revoked',evidence:String(reason).slice(0,300)};validate('site-asset-registry',next);const entry=index.entries.find(item=>item.asset_id===assetId);return {registry:next,impact:{asset_id:assetId,build_id:index.build_id,pages:[...new Set((entry?.usages||[]).map(usage=>usage.page_path))].sort(),usage_count:entry?.usages.length||0,action:'rebuild_without_asset'}};}
function renderTrace(registry,index){validate('site-asset-registry',registry);validate('asset-usage-index',index);const rows=registry.assets.map(asset=>{const entry=index.entries.find(x=>x.asset_id===asset.asset_id);return `<article><div><span>${asset.state.replace('_',' ')}</span><h2>${asset.filename}</h2><code>${asset.content_sha256.slice(0,12)}…</code></div><strong>${entry.usages.length}</strong><p>usos registrados<br>${new Set(entry.usages.map(x=>x.site_id)).size} sitios</p></article>`;}).join('');return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Trazabilidad de activos</title><link rel="stylesheet" href="styles.css"></head><body class="asset-trace"><div class="demo-bar"><span></span> DEMOSTRACIÓN FICTICIA · REGISTRO SINTÉTICO · PUBLICACIÓN BLOQUEADA</div><main><a href="index.html">← Volver a experiencias</a><header><p>FASE 11 · ${registry.registry_id}</p><h1>Cada imagen sabe dónde aparece.</h1><div><span>BUILD</span><code>${index.build_id}</code></div></header><section>${rows}</section><aside><b>Revocación preparada</b><p>Retirar un activo devuelve la lista exacta de páginas que deben reconstruirse. Los fixtures actuales nunca son elegibles para producción.</p></aside></main></body></html>`;}
module.exports={buildPilotRegistry,assertEligible,assertCatalogAssets,createUsageIndex,revokeAsset,renderTrace,sha256};
