'use strict';
const form=document.querySelector('#onboarding-form');const steps=[...document.querySelectorAll('.step')];const rail=[...document.querySelectorAll('.rail li')];let current=0;let generated=null;
const sample={display_name:'Horizonte Casa — FICTICIO',primary_category:'agentes-inmobiliarios',representative_role:'owner',legal_name:'',description:'Estudio inmobiliario ficticio que acompaña a propietarios y compradores con información clara y atención personalizada.',ideal_customer:'Propietarios que desean preparar mejor una venta y compradores que valoran una selección explicada.',specialty:'Asesoría residencial y curaduría de inmuebles en distritos urbanos de Lima.',primary_action:'schedule_conversation',service_areas:'Miraflores, Barranco, San Isidro',service_1_name:'Asesoría para vender',service_1_description:'Preparación, presentación y acompañamiento ficticio del proceso de venta.',service_2_name:'Búsqueda personalizada',service_2_description:'Selección ficticia de alternativas según prioridades previamente conversadas.',preferred_channel:'email',public_email:'demo@example.invalid',public_phone:'',asset_relationship:'owner_supplied',permission_note:'Activo sintético creado para pruebas internas.'};
function fillSample(){for(const [name,value] of Object.entries(sample)){const input=form.elements[name];if(input)input.value=value;}for(const name of ['authorized_representative','truthfulness_confirmed','contact_permission','asset_rights_confirmed'])form.elements[name].checked=false;updateStatus();}
function showStep(index){current=Math.max(0,Math.min(steps.length-1,index));steps.forEach((s,i)=>{s.hidden=i!==current;s.classList.toggle('active',i===current);});rail.forEach((li,i)=>li.classList.toggle('active',i===current));document.querySelector('#progress-label').textContent=`Paso ${current+1} de ${steps.length}`;document.querySelector('#progress-bar').style.width=`${(current+1)/steps.length*100}%`;document.querySelector('#back').disabled=current===0;document.querySelector('#next').hidden=current===steps.length-1;document.querySelector('#generate').hidden=current!==steps.length-1;document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'start'});}
function validateCurrent(){const inputs=[...steps[current].querySelectorAll('input,textarea,select')];for(const input of inputs){const text=String(input.value||'').trim();const tooShort=input.minLength>0&&text.length<input.minLength;const missing=input.required&&!text;if(missing||tooShort){input.focus();input.setAttribute('aria-invalid','true');document.querySelector('#status-title').textContent=missing?'Completa el campo señalado':`Usa al menos ${input.minLength} caracteres`;return false;}input.removeAttribute('aria-invalid');}return true;}
function value(name){return form.elements[name].value.trim();}function id(text){return text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'item';}
function makeSubmission(){const now=new Date().toISOString();const name=value('display_name');return {schema_version:'0.1.0',submission_id:`onb-${id(name)}-demo`,business_id:`${id(name)}-demo`,status:'owner_confirmed',identity:{display_name:name,legal_name:value('legal_name')||null,primary_category:value('primary_category'),representative_role:value('representative_role')},business_profile:{description:value('description'),ideal_customer:value('ideal_customer'),specialty:value('specialty'),primary_action:value('primary_action')},service_areas:value('service_areas').split(',').map(x=>x.trim()).filter(Boolean),services:[{service_id:id(value('service_1_name')),name:value('service_1_name'),description:value('service_1_description')},{service_id:id(value('service_2_name')),name:value('service_2_name'),description:value('service_2_description')}],contacts:{public_phone:value('public_phone')||null,public_email:value('public_email')||null,preferred_channel:value('preferred_channel')},assets:[{asset_id:'logo-declarado',kind:'logo',reference:'urn:hazlocrecer:onboarding:pending-upload',relationship:value('asset_relationship'),usage_status:value('asset_relationship')==='unknown'?'pending_review':'approved',permission_note:value('permission_note')||null}],declarations:{authorized_representative:form.elements.authorized_representative.checked,truthfulness_confirmed:form.elements.truthfulness_confirmed.checked,contact_permission:form.elements.contact_permission.checked,asset_rights_confirmed:form.elements.asset_rights_confirmed.checked},owner_confirmed_at:now,created_at:now,updated_at:now};}
function completion(){const identity=value('display_name').length>=2;const offer=value('service_1_name').length>=2&&value('service_areas').length>=2;const rights=['authorized_representative','truthfulness_confirmed','contact_permission','asset_rights_confirmed'].every(n=>form.elements[n].checked)&&value('permission_note').length>0&&value('asset_relationship')!=='unknown';const list=document.querySelector('#checklist');const items=list.querySelectorAll('li');items[0].classList.toggle('done',identity);items[0].lastChild.textContent=identity?' Identidad registrada':' Identidad pendiente';items[1].classList.toggle('done',offer);items[1].lastChild.textContent=offer?' Oferta registrada':' Oferta pendiente';items[2].classList.toggle('done',rights);items[2].lastChild.textContent=rights?' Derechos declarados':' Derechos pendientes';return identity&&offer&&rights;}
function updateStatus(){const ready=completion();document.querySelector('#status-title').textContent=ready?'Listo para revisión':'Borrador local';}
document.querySelector('#next').addEventListener('click',()=>{if(validateCurrent())showStep(current+1);});document.querySelector('#back').addEventListener('click',()=>showStep(current-1));document.querySelectorAll('[data-step-target]').forEach(b=>b.addEventListener('click',()=>showStep(Number(b.dataset.stepTarget))));form.addEventListener('input',updateStatus);
document.querySelector('#reset').addEventListener('click',()=>{fillSample();showStep(0);});
document.querySelector('#generate').addEventListener('click',()=>{if(!validateCurrent())return;if(!completion()){document.querySelector('#status-title').textContent='Faltan confirmaciones';return;}generated=makeSubmission();document.querySelector('#json-preview').textContent=JSON.stringify(generated,null,2);const dialog=document.querySelector('#result-dialog');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');});
function close(){const dialog=document.querySelector('#result-dialog');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');}document.querySelector('#close-dialog').addEventListener('click',close);document.querySelector('#close-dialog-secondary').addEventListener('click',close);
document.querySelector('#download').addEventListener('click',()=>{if(!generated)return;const url=URL.createObjectURL(new Blob([JSON.stringify(generated,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=generated.submission_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0);});
fillSample();showStep(0);
