'use strict';
const crypto=require('node:crypto');const {validate}=require('../site-engine/index.cjs');
const hash=v=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex'),id=prefix=>`${prefix}-${crypto.randomBytes(12).toString('hex')}`,clone=v=>structuredClone(v);
const transitions={new:new Set(['assigned','closed']),assigned:new Set(['contacted','closed']),contacted:new Set(['qualified','closed']),qualified:new Set(['closed']),closed:new Set()};
const permissions={owner:new Set(['read','assign','transition','note','dispatch']),operator:new Set(['read','assign','transition','note','dispatch','create']),admin:new Set(['read','assign','transition','note','dispatch','create','sla']),system:new Set(['read','create','dispatch','sla'])};
function assertActor(actor,action,tenant){if(!actor||!permissions[actor.role]?.has(action)||(actor.role==='owner'&&actor.tenant_id!==tenant))throw Object.assign(new Error('Access denied'),{code:'ACCESS_DENIED'});}
function safe(value,label){if(!/^[a-z0-9][a-z0-9-]{2,79}$/.test(String(value||'')))throw Object.assign(new Error(`Invalid ${label}`),{code:'INVALID_IDENTIFIER'});return String(value);}
function createLocalDeliveryAdapter({fail=false}={}){const messages=[];return {name:'local_outbox',messages,deliver(payload,key){if(fail)return {status:'failed',error_code:'LOCAL_SIMULATED_FAILURE'};messages.push(clone(payload));return {status:'delivered',provider_reference:`local:${key.slice(0,16)}`};}};}
function createLeadInbox({now=()=>new Date(),deliveryAdapter=createLocalDeliveryAdapter(),vault=null,vaultContext=null}={}){
 const cases=new Map(),events=new Map(),attempts=new Map(),deliveryKeys=new Map(),slaEvents=new Set();
 const at=()=>now().toISOString();
 function event(type,current,actor,changes,occurred=at()){const value={schema_version:'0.1.0',event_id:id('levt'),type,case_id:current.case_id,tenant_id:current.tenant_id,actor_id:safe(actor.actor_id,'actor'),occurred_at:occurred,case_version:current.version,changes};validate('lead-event',value);events.set(value.event_id,value);return clone(value);}
 function get(caseId,actor){const current=cases.get(caseId);if(!current)throw Object.assign(new Error('Case not found'),{code:'CASE_NOT_FOUND'});assertActor(actor,'read',current.tenant_id);return clone(current);}
 function create(input,actor){for(const field of ['tenant_id','site_id','submission_ref','purpose'])if(!input?.[field])throw Object.assign(new Error(`Missing ${field}`),{code:'INVALID_CASE'});assertActor(actor,'create',input.tenant_id);if(!['contact_request','property_interest','valuation_request'].includes(input.purpose))throw Object.assign(new Error('Invalid purpose'),{code:'INVALID_CASE'});const created=at(),target=input.purpose==='property_interest'?15:input.purpose==='contact_request'?60:120,current={schema_version:'0.1.0',case_id:id('case'),tenant_id:safe(input.tenant_id,'tenant'),site_id:safe(input.site_id,'site'),submission_ref:input.submission_ref,purpose:input.purpose,priority:input.priority|| (input.purpose==='property_interest'?'high':'normal'),status:'new',assignee_id:null,sla:{target_minutes:target,due_at:new Date(Date.parse(created)+target*60000).toISOString(),breached:false},version:1,created_at:created,updated_at:created,closed_at:null,close_reason:null};validate('lead-case',current);cases.set(current.case_id,current);return {case:clone(current),event:event('case.created',current,actor,{from:null,to:'new',assignee_id:null,note_ref:null},created)};}
 function ensureVersion(current,expected){if(current.version!==expected)throw Object.assign(new Error('Case version conflict'),{code:'VERSION_CONFLICT',current_version:current.version});}
 function assign(caseId,assigneeId,actor,expectedVersion){const current=cases.get(caseId);if(!current)throw Object.assign(new Error('Case not found'),{code:'CASE_NOT_FOUND'});assertActor(actor,'assign',current.tenant_id);ensureVersion(current,expectedVersion);if(current.status==='closed')throw Object.assign(new Error('Closed case'),{code:'INVALID_TRANSITION'});const from=current.status;current.assignee_id=safe(assigneeId,'assignee');if(current.status==='new')current.status='assigned';current.version++;current.updated_at=at();validate('lead-case',current);return {case:clone(current),event:event('case.assigned',current,actor,{from,to:current.status,assignee_id:current.assignee_id,note_ref:null},current.updated_at)};}
 function transition(caseId,to,actor,expectedVersion,closeReason=null){const current=cases.get(caseId);if(!current)throw Object.assign(new Error('Case not found'),{code:'CASE_NOT_FOUND'});assertActor(actor,'transition',current.tenant_id);ensureVersion(current,expectedVersion);if(!transitions[current.status]?.has(to))throw Object.assign(new Error('Invalid transition'),{code:'INVALID_TRANSITION'});if(to!=='closed'&&current.assignee_id===null)throw Object.assign(new Error('Assignment required'),{code:'ASSIGNMENT_REQUIRED'});if(to==='closed'&&!['resolved','not_qualified','duplicate','withdrawn','expired'].includes(closeReason))throw Object.assign(new Error('Close reason required'),{code:'CLOSE_REASON_REQUIRED'});const from=current.status;current.status=to;current.version++;current.updated_at=at();if(to==='closed'){current.closed_at=current.updated_at;current.close_reason=closeReason;}validate('lead-case',current);return {case:clone(current),event:event('case.transitioned',current,actor,{from,to,assignee_id:current.assignee_id,note_ref:null},current.updated_at)};}
 function addNote(caseId,body,actor,expectedVersion){const current=cases.get(caseId);if(!current)throw Object.assign(new Error('Case not found'),{code:'CASE_NOT_FOUND'});assertActor(actor,'note',current.tenant_id);ensureVersion(current,expectedVersion);if(!vault||!vaultContext)throw Object.assign(new Error('Encrypted note vault required'),{code:'NOTE_VAULT_REQUIRED'});const created=at(),note={schema_version:'0.1.0',note_id:id('note'),case_id:current.case_id,tenant_id:current.tenant_id,author_id:safe(actor.actor_id,'actor'),visibility:'internal',body:String(body||'').trim(),created_at:created};validate('lead-note',note);vault.putJson(vaultContext,{record_id:note.note_id,tenant_id:note.tenant_id,record_type:'lead_note',payload:note,retention_class:'inactive_lead',expires_at:new Date(Date.parse(created)+180*86400000).toISOString()},created);current.version++;current.updated_at=created;validate('lead-case',current);return {note_ref:note.note_id,case:clone(current),event:event('note.created',current,actor,{from:null,to:null,assignee_id:current.assignee_id,note_ref:note.note_id},created)};}
 function checkSla(actor){const currentTime=Date.parse(at()),breached=[];for(const current of cases.values()){assertActor(actor,'sla',current.tenant_id);if(current.status!=='closed'&&!current.sla.breached&&Date.parse(current.sla.due_at)<currentTime){current.sla.breached=true;current.version++;current.updated_at=new Date(currentTime).toISOString();validate('lead-case',current);if(!slaEvents.has(current.case_id)){slaEvents.add(current.case_id);const emitted=event('sla.breached',current,actor,{from:current.status,to:current.status,assignee_id:current.assignee_id,note_ref:null},current.updated_at);breached.push({case:clone(current),event:emitted});}}}return breached;}
 function dispatch(caseId,eventId,destinationRef,actor){const current=cases.get(caseId),sourceEvent=events.get(eventId);if(!current||!sourceEvent||sourceEvent.case_id!==caseId)throw Object.assign(new Error('Event not found'),{code:'EVENT_NOT_FOUND'});assertActor(actor,'dispatch',current.tenant_id);const destination=String(destinationRef||'');if(!/^[a-z0-9][a-z0-9:_-]{2,119}$/.test(destination))throw Object.assign(new Error('Invalid destination reference'),{code:'DESTINATION_INVALID'});const key=hash(`${eventId}|${destination}`);if(deliveryKeys.has(key))return {attempt:clone(attempts.get(deliveryKeys.get(key))),duplicate:true};const payload={event_id:sourceEvent.event_id,type:sourceEvent.type,case_id:current.case_id,tenant_id:current.tenant_id,status:current.status,priority:current.priority,due_at:current.sla.due_at,private_route:`/inbox/${current.case_id}`},created=at(),result=deliveryAdapter.deliver(clone(payload),key),attempt={schema_version:'0.1.0',attempt_id:id('delivery'),tenant_id:current.tenant_id,case_id:current.case_id,event_ref:eventId,provider:deliveryAdapter.name||'local_outbox',destination_ref:destination,idempotency_key:key,payload_sha256:hash(payload),status:result.status,attempt_count:1,created_at:created,updated_at:created,provider_reference:result.provider_reference||null,error_code:result.error_code||null};validate('delivery-attempt',attempt);attempts.set(attempt.attempt_id,attempt);deliveryKeys.set(key,attempt.attempt_id);return {attempt:clone(attempt),duplicate:false,payload};}
 function list(actor){return [...cases.values()].filter(x=>actor.role!=='owner'||x.tenant_id===actor.tenant_id).map(current=>{assertActor(actor,'read',current.tenant_id);return clone(current);});}
 return {create,get,list,assign,transition,addNote,checkSla,dispatch,_state:{events,attempts}};
}
module.exports={createLeadInbox,createLocalDeliveryAdapter,transitions};
