'use strict';
const crypto=require('node:crypto');
const {validate}=require('../site-engine/index.cjs');
const clone=value=>structuredClone(value);
const sha=value=>crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
const makeId=prefix=>`${prefix}-${crypto.randomBytes(12).toString('hex')}`;
const safe=(value,label='identifier')=>{if(!/^[a-z0-9][a-z0-9-]{2,127}$/.test(String(value||'')))throw error('INVALID_IDENTIFIER',`Invalid ${label}`);return String(value);};
const error=(code,message)=>Object.assign(new Error(message),{code});
const roles={
  owner:new Set(['publication.read']),
  operator:new Set(['publication.read','build.register','build.approve','route.create','domain.bind','release.promote','release.rollback','cache.purge']),
  admin:new Set(['publication.read','build.register','build.approve','build.revoke','route.create','route.suspend','domain.bind','domain.revoke','release.promote','release.rollback','cache.purge']),
  system:new Set(['publication.read','cache.purge'])
};
function authorize(actor,action,tenantId){if(!actor||!roles[actor.role]?.has(action)||(actor.tenant_id&&actor.tenant_id!==tenantId))throw error('ACCESS_DENIED','Access denied');}
function normalizeHostname(value){const host=String(value||'').trim().toLowerCase().replace(/\.$/,'');if(!/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(host))throw error('HOSTNAME_INVALID','Invalid hostname');return host;}
function createUnconfiguredPublicationAdapter(){return {name:'unconfigured',bind(){throw error('PUBLICATION_ADAPTER_UNCONFIGURED','Publication adapter is not configured');},purge(){throw error('PUBLICATION_ADAPTER_UNCONFIGURED','Publication adapter is not configured');}};}
function createLocalPublicationAdapter(){return {name:'local_sandbox',bind(input){if(!input?.synthetic)throw error('PROVIDER_REQUEST_REJECTED','Local adapter accepts synthetic bindings only');return {provider_ref:`local://${input.hostname}`,verification_status:'verified',certificate_status:input.kind==='managed_subdomain'?'not_required':'active'};},purge(input){if(!input?.synthetic)throw error('PROVIDER_REQUEST_REJECTED','Local adapter accepts synthetic purges only');return {status:'completed'};}};}
function createPublicationControl({adapter=createUnconfiguredPublicationAdapter(),now=()=>new Date()}={}){
  const builds=new Map(),routes=new Map(),domains=new Map(),releases=new Map(),purges=new Map(),events=[];
  const stamp=()=>now().toISOString();
  function audit(type,subject,actor,tenantId,siteId){const occurred_at=stamp(),previous_hash=events.length?events.at(-1).event_hash:null,payload={type,subject_id:subject,actor_id:actor.actor_id,tenant_id:tenantId,site_id:siteId,occurred_at,previous_hash},event={schema_version:'0.1.0',event_id:makeId('pubevt'),...payload,event_hash:sha(payload)};validate('publication-audit-event',event);events.push(event);return event;}
  function registerBuild(actor,input){authorize(actor,'build.register',input.tenant_id);const build={schema_version:'0.1.0',build_id:safe(input.build_id,'build'),tenant_id:safe(input.tenant_id,'tenant'),site_id:safe(input.site_id,'site'),snapshot_id:String(input.snapshot_id),artifact_digest:String(input.artifact_digest),entrypoint:String(input.entrypoint),environment:input.environment,qa_status:input.qa_status,approval_status:'pending',registered_by:safe(actor.actor_id,'actor'),approved_by:null,approved_at:null,created_at:stamp()};validate('publication-build',build);if(builds.has(build.build_id))throw error('BUILD_EXISTS','Build already registered');builds.set(build.build_id,build);audit('build.registered',build.build_id,actor,build.tenant_id,build.site_id);return clone(build);}
  function decideBuild(actor,buildId,decision){const build=builds.get(buildId);if(!build)throw error('BUILD_NOT_FOUND','Build not found');authorize(actor,'build.approve',build.tenant_id);if(actor.actor_id===build.registered_by)throw error('INDEPENDENT_APPROVAL_REQUIRED','Build registrar cannot approve the same build');if(build.approval_status!=='pending'||!['approved','rejected'].includes(decision))throw error('BUILD_STATE_INVALID','Build decision is invalid');build.approval_status=decision;build.approved_by=safe(actor.actor_id,'actor');build.approved_at=stamp();validate('publication-build',build);if(decision==='approved')audit('build.approved',build.build_id,actor,build.tenant_id,build.site_id);return clone(build);}
  function revokeBuild(actor,buildId){const build=builds.get(buildId);if(!build)throw error('BUILD_NOT_FOUND','Build not found');authorize(actor,'build.revoke',build.tenant_id);if(build.approval_status!=='approved')throw error('BUILD_STATE_INVALID','Only approved builds can be revoked');build.approval_status='revoked';validate('publication-build',build);for(const route of routes.values()){const release=route.active_release_id?releases.get(route.active_release_id):null;if(release?.build_id===buildId){route.status='suspended';route.updated_at=stamp();}}return clone(build);}
  function bindDomain(actor,input){authorize(actor,'domain.bind',input.tenant_id);const tenantId=safe(input.tenant_id,'tenant'),hostname=normalizeHostname(input.hostname);if([...domains.values()].some(item=>item.hostname===hostname&&item.verification_status!=='revoked'))throw error('HOSTNAME_CONFLICT','Hostname already belongs to a tenant');if(input.kind==='managed_subdomain'&&!hostname.endsWith('.guialima.online'))throw error('MANAGED_DOMAIN_INVALID','Managed domains must use guialima.online');const result=adapter.bind({synthetic:input.synthetic===true,hostname,kind:input.kind,tenant_id:tenantId}),created=stamp(),binding={schema_version:'0.1.0',binding_id:makeId('domain'),tenant_id:tenantId,hostname,kind:input.kind,verification_status:result.verification_status,certificate_status:result.certificate_status,provider_ref:result.provider_ref??null,last_checked_at:created,created_at:created,updated_at:created};validate('domain-binding',binding);domains.set(binding.binding_id,binding);audit('domain.bound',binding.binding_id,actor,tenantId,input.site_id);return clone(binding);}
  function revokeDomain(actor,bindingId){const domain=domains.get(bindingId);if(!domain)throw error('DOMAIN_NOT_FOUND','Domain binding not found');authorize(actor,'domain.revoke',domain.tenant_id);domain.verification_status='revoked';domain.certificate_status='revoked';domain.updated_at=stamp();validate('domain-binding',domain);for(const route of routes.values())if(route.domain_binding_ref===bindingId){route.status='suspended';route.updated_at=stamp();}return clone(domain);}
  function createRoute(actor,input){authorize(actor,'route.create',input.tenant_id);const tenantId=safe(input.tenant_id,'tenant'),siteId=safe(input.site_id,'site'),hostname=normalizeHostname(input.hostname),domain=[...domains.values()].find(item=>item.binding_id===input.domain_binding_ref);if(!domain||domain.tenant_id!==tenantId||domain.hostname!==hostname||domain.verification_status!=='verified'||!['active','not_required'].includes(domain.certificate_status))throw error('DOMAIN_NOT_READY','Verified domain binding required');if([...routes.values()].some(item=>item.hostname===hostname&&item.path_prefix===(input.path_prefix||'/')&&item.status!=='suspended'))throw error('ROUTE_CONFLICT','Route already exists');const created=stamp(),route={schema_version:'0.1.0',route_id:makeId('route'),tenant_id:tenantId,site_id:siteId,environment:input.environment,hostname,path_prefix:input.path_prefix||'/',domain_binding_ref:domain.binding_id,status:'ready',active_release_id:null,created_at:created,updated_at:created};validate('tenant-route',route);routes.set(route.route_id,route);audit('route.created',route.route_id,actor,tenantId,siteId);return clone(route);}
  function assertPublishGate(build,route,entitlements){if(build.approval_status!=='approved'||build.qa_status!=='passed')throw error('BUILD_NOT_APPROVED','Approved QA-passed build required');if(route.status==='suspended'||route.tenant_id!==build.tenant_id||route.site_id!==build.site_id||route.environment!==build.environment)throw error('ROUTE_MISMATCH','Compatible active route required');validate('entitlement-snapshot',entitlements);if(entitlements.tenant_id!==build.tenant_id)throw error('ENTITLEMENT_TENANT_MISMATCH','Entitlements belong to another tenant');const capability=entitlements.capabilities.find(item=>item.key==='site.publish');if(!capability?.allowed)throw error('PUBLISH_ENTITLEMENT_REQUIRED','site.publish entitlement required');}
  function promote(actor,{build_id,route_id,entitlements,reason}){const build=builds.get(build_id),route=routes.get(route_id);if(!build)throw error('BUILD_NOT_FOUND','Build not found');if(!route)throw error('ROUTE_NOT_FOUND','Route not found');authorize(actor,'release.promote',build.tenant_id);assertPublishGate(build,route,entitlements);const previous=route.active_release_id?releases.get(route.active_release_id):null;if(previous)previous.status='superseded';const release={schema_version:'0.1.0',release_id:makeId('release'),tenant_id:build.tenant_id,site_id:build.site_id,environment:build.environment,build_id:build.build_id,route_id:route.route_id,sequence:(previous?.sequence||0)+1,reason:String(reason||''),rollback_of:null,previous_release_id:previous?.release_id||null,status:'active',created_by:safe(actor.actor_id,'actor'),created_at:stamp()};validate('publication-release',release);releases.set(release.release_id,release);route.active_release_id=release.release_id;route.status='active';route.updated_at=release.created_at;validate('tenant-route',route);audit('release.promoted',release.release_id,actor,build.tenant_id,build.site_id);return clone(release);}
  function rollback(actor,{route_id,target_release_id,entitlements,reason}){const route=routes.get(route_id),target=releases.get(target_release_id);if(!route)throw error('ROUTE_NOT_FOUND','Route not found');authorize(actor,'release.rollback',route.tenant_id);if(!target||target.route_id!==route.route_id||target.status==='failed')throw error('ROLLBACK_TARGET_INVALID','Rollback target is invalid');const build=builds.get(target.build_id);assertPublishGate(build,route,entitlements);const current=route.active_release_id?releases.get(route.active_release_id):null;if(!current||current.release_id===target.release_id)throw error('ROLLBACK_NOT_NEEDED','Target is already active');current.status='superseded';const release={schema_version:'0.1.0',release_id:makeId('release'),tenant_id:route.tenant_id,site_id:route.site_id,environment:route.environment,build_id:target.build_id,route_id:route.route_id,sequence:current.sequence+1,reason:String(reason||''),rollback_of:current.release_id,previous_release_id:current.release_id,status:'active',created_by:safe(actor.actor_id,'actor'),created_at:stamp()};validate('publication-release',release);releases.set(release.release_id,release);route.active_release_id=release.release_id;route.updated_at=release.created_at;audit('release.rolled_back',release.release_id,actor,route.tenant_id,route.site_id);return clone(release);}
  function purgeCache(actor,{route_id,scope='release',paths=[],idempotency_key,synthetic=false}){const route=routes.get(route_id);if(!route)throw error('ROUTE_NOT_FOUND','Route not found');authorize(actor,'cache.purge',route.tenant_id);if(!route.active_release_id)throw error('RELEASE_REQUIRED','Active release required');const key=sha(idempotency_key||`${route.route_id}|${route.active_release_id}|${scope}|${paths.join(',')}`);if(purges.has(key))return {...clone(purges.get(key)),duplicate:true};if(scope==='paths'&&!paths.length)throw error('PURGE_PATHS_REQUIRED','At least one path is required');const result=adapter.purge({synthetic,hostname:route.hostname,scope,paths}),requested=stamp(),purge={schema_version:'0.1.0',purge_id:makeId('purge'),tenant_id:route.tenant_id,route_id:route.route_id,release_id:route.active_release_id,scope,paths:scope==='paths'?[...paths]:[],idempotency_key:key,provider:adapter.name==='local_sandbox'?'local_sandbox':'cloudflare',status:result.status,requested_by:safe(actor.actor_id,'actor'),requested_at:requested,completed_at:result.status==='completed'?requested:null};validate('cache-purge-request',purge);purges.set(key,purge);audit('cache.purged',purge.purge_id,actor,route.tenant_id,route.site_id);return {...clone(purge),duplicate:false};}
  function read(actor,tenantId){authorize(actor,'publication.read',tenantId);return {builds:[...builds.values()].filter(x=>x.tenant_id===tenantId).map(clone),domains:[...domains.values()].filter(x=>x.tenant_id===tenantId).map(clone),routes:[...routes.values()].filter(x=>x.tenant_id===tenantId).map(clone),releases:[...releases.values()].filter(x=>x.tenant_id===tenantId).map(clone),purges:[...purges.values()].filter(x=>x.tenant_id===tenantId).map(clone),events:events.filter(x=>x.tenant_id===tenantId).map(clone)};}
  return {registerBuild,decideBuild,revokeBuild,bindDomain,revokeDomain,createRoute,promote,rollback,purgeCache,read,_state:{builds,routes,domains,releases,purges,events}};
}
module.exports={createPublicationControl,createLocalPublicationAdapter,createUnconfiguredPublicationAdapter,normalizeHostname};
