'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const Ajv=require('ajv/dist/2020'),addFormats=require('ajv-formats');
const ROOT=path.resolve(__dirname,'../..'),ajv=new Ajv({allErrors:true,strict:false,validateFormats:true});addFormats(ajv);
const schemaNames=['orchestration-job','idempotency-record','worker-lease','retry-schedule','dead-letter-entry','maintenance-window','tenant-concurrency-policy','operation-budget','desired-state-record','observed-state-record','reconciliation-plan','reconciliation-run','queue-snapshot'];
const validators=Object.fromEntries(schemaNames.map(name=>[name,ajv.compile(JSON.parse(fs.readFileSync(path.join(ROOT,'contracts',`${name}.schema.json`),'utf8')))]));
const clone=value=>JSON.parse(JSON.stringify(value));
const canonical=value=>JSON.stringify(value,(_key,current)=>current&&typeof current==='object'&&!Array.isArray(current)?Object.fromEntries(Object.entries(current).sort(([a],[b])=>a.localeCompare(b))):current);
const sha=value=>crypto.createHash('sha256').update(typeof value==='string'?value:canonical(value)).digest('hex');
const fail=(code,message,details)=>Object.assign(new Error(message),{code,details});
function validate(name,value){const check=validators[name];if(!check(value))throw fail('SCHEMA_INVALID',`${name} invalid`,check.errors);return value;}
const addSeconds=(date,seconds)=>new Date(date.getTime()+seconds*1000);

function createFleetOrchestrator({now=()=>new Date(),idempotencyDays=30}={}){
  const jobs=new Map(),idempotency=new Map(),leases=new Map(),retries=new Map(),deadLetters=new Map(),windows=new Map(),policies=new Map(),budgets=new Map(),desired=new Map(),observed=new Map(),latestDesired=new Map(),latestObserved=new Map(),plans=new Map(),runs=new Map(),snapshots=new Map();let sequence=0;
  const stamp=()=>now().toISOString(),makeId=(prefix,salt='')=>`${prefix}-${sha(`${prefix}|${salt}|${sequence++}|${stamp()}`).slice(0,24)}`;
  function authorize(actor,tenantId,roles){if(!actor||!roles.includes(actor.role)||(actor.role!=='admin'&&actor.tenant_id!==tenantId))throw fail('ACCESS_DENIED','Actor cannot access this tenant');}
  const tenantKey=(tenantId,key)=>`${tenantId}|${key}`;
  function configurePolicy(actor,input){authorize(actor,input.tenant_id,['operator','admin']);const value={schema_version:'0.1.0',tenant_id:input.tenant_id,max_global:input.max_global,max_per_operation:input.max_per_operation,max_per_site:input.max_per_site,lease_seconds:input.lease_seconds,updated_by:actor.actor_id,updated_at:stamp()};if(value.max_per_operation>value.max_global||value.max_per_site>value.max_global)throw fail('CONCURRENCY_POLICY_INVALID','Specific limits cannot exceed global limit');validate('tenant-concurrency-policy',value);policies.set(value.tenant_id,value);return clone(value);}
  function createWindow(actor,input){authorize(actor,input.tenant_id,['operator','admin']);const start=Date.parse(input.starts_at),end=Date.parse(input.ends_at);if(!(start<end))throw fail('WINDOW_INVALID','Maintenance window end must follow start');const value={schema_version:'0.1.0',window_id:makeId('window',input.name),tenant_id:input.tenant_id,name:input.name,starts_at:new Date(start).toISOString(),ends_at:new Date(end).toISOString(),allowed_operations:clone(input.allowed_operations),status:'active',created_by:actor.actor_id,created_at:stamp()};validate('maintenance-window',value);windows.set(value.window_id,value);return clone(value);}
  function createBudget(actor,input){authorize(actor,input.tenant_id,['operator','admin']);const start=Date.parse(input.period_start),end=Date.parse(input.period_end);if(!(start<end))throw fail('BUDGET_PERIOD_INVALID','Budget period end must follow start');const value={schema_version:'0.1.0',budget_id:makeId('budget',input.tenant_id),tenant_id:input.tenant_id,period_start:new Date(start).toISOString(),period_end:new Date(end).toISOString(),max_jobs:input.max_jobs,max_cost_units:input.max_cost_units,consumed_jobs:0,consumed_cost_units:0,status:'open',created_by:actor.actor_id,created_at:stamp(),updated_at:stamp()};validate('operation-budget',value);budgets.set(value.budget_id,value);return clone(value);}
  function setDesiredState(actor,input){authorize(actor,input.tenant_id,['operator','admin']);const currentId=latestDesired.get(tenantKey(input.tenant_id,input.site_id)),current=currentId?desired.get(currentId):null;if(current&&input.generation<=current.generation)throw fail('STALE_GENERATION','Desired generation must increase');const value={schema_version:'0.1.0',desired_state_id:makeId('desired',`${input.site_id}|${input.generation}`),tenant_id:input.tenant_id,site_id:input.site_id,generation:input.generation,recipe_version_ref:input.recipe_version_ref,design_version_ref:input.design_version_ref,engine_version:input.engine_version,configuration_digest:input.configuration_digest,source_cohort_ref:input.source_cohort_ref,updated_by:actor.actor_id,updated_at:stamp()};validate('desired-state-record',value);desired.set(value.desired_state_id,value);latestDesired.set(tenantKey(value.tenant_id,value.site_id),value.desired_state_id);return clone(value);}
  function observeState(actor,input){authorize(actor,input.tenant_id,['service','operator','admin']);const currentId=latestObserved.get(tenantKey(input.tenant_id,input.site_id)),current=currentId?observed.get(currentId):null;if(current&&input.generation<current.generation)throw fail('STALE_OBSERVATION','Observed generation cannot move backwards');const value={schema_version:'0.1.0',observed_state_id:makeId('observed',`${input.site_id}|${input.generation}`),tenant_id:input.tenant_id,site_id:input.site_id,generation:input.generation,recipe_version_ref:input.recipe_version_ref,design_version_ref:input.design_version_ref,engine_version:input.engine_version,configuration_digest:input.configuration_digest,release_digest:input.release_digest,observed_at:stamp()};validate('observed-state-record',value);observed.set(value.observed_state_id,value);latestObserved.set(tenantKey(value.tenant_id,value.site_id),value.observed_state_id);return clone(value);}
  function reconcileSite(actor,tenantId,siteId){authorize(actor,tenantId,['operator','admin']);const desiredId=latestDesired.get(tenantKey(tenantId,siteId)),observedId=latestObserved.get(tenantKey(tenantId,siteId));if(!desiredId||!observedId)throw fail('STATE_INCOMPLETE','Desired and observed state are required');const wanted=desired.get(desiredId),actual=observed.get(observedId),drift=[],operations=[];if(wanted.recipe_version_ref!==actual.recipe_version_ref){drift.push('recipe');operations.push('apply_recipe');}if(wanted.design_version_ref!==actual.design_version_ref){drift.push('design');operations.push('apply_design');}if(wanted.engine_version!==actual.engine_version){drift.push('engine');operations.push('apply_engine');}if(wanted.configuration_digest!==actual.configuration_digest){drift.push('configuration');operations.push('apply_configuration');}if(wanted.generation!==actual.generation)drift.push('generation');let status='no_op';if(wanted.generation<actual.generation)status='blocked';else if(drift.length){status='ready';operations.push('verify_state');}const value={schema_version:'0.1.0',plan_id:makeId('reconp',`${siteId}|${wanted.generation}`),tenant_id:tenantId,site_id:siteId,desired_state_ref:wanted.desired_state_id,observed_state_ref:actual.observed_state_id,drift_keys:drift,operations:status==='blocked'?[]:[...new Set(operations)],idempotency_base:`reconcile:${siteId}:g${wanted.generation}`,status,external_changes:false,created_at:stamp()};validate('reconciliation-plan',value);plans.set(value.plan_id,value);return clone(value);}
  function enqueue(actor,input){authorize(actor,input.tenant_id,['service','operator','admin']);const requestDigest=sha({site_id:input.site_id,operation:input.operation,payload_digest:input.payload_digest,desired_state_ref:input.desired_state_ref,cost_units:input.cost_units}),key=tenantKey(input.tenant_id,input.idempotency_key),existing=idempotency.get(key);if(existing){if(existing.request_digest!==requestDigest)throw fail('IDEMPOTENCY_CONFLICT','Idempotency key was used with a different request');const job=jobs.get(existing.job_ref);return {job:clone(job),duplicate:true};}const time=stamp(),job={schema_version:'0.1.0',job_id:makeId('job',input.idempotency_key),tenant_id:input.tenant_id,site_id:input.site_id,operation:input.operation,idempotency_key:input.idempotency_key,payload_digest:input.payload_digest,desired_state_ref:input.desired_state_ref,status:'queued',priority:input.priority??50,attempts:0,max_attempts:input.max_attempts??5,cost_units:input.cost_units??1,available_at:time,lease_ref:null,created_at:time,updated_at:time},record={schema_version:'0.1.0',tenant_id:input.tenant_id,idempotency_key:input.idempotency_key,request_digest:requestDigest,job_ref:job.job_id,status:'accepted',created_at:time,expires_at:addSeconds(now(),idempotencyDays*86400).toISOString()};validate('orchestration-job',job);validate('idempotency-record',record);jobs.set(job.job_id,job);idempotency.set(key,record);return {job:clone(job),duplicate:false};}
  function activeWindow(tenantId,operation){const time=now().getTime();return [...windows.values()].find(item=>item.tenant_id===tenantId&&item.status==='active'&&Date.parse(item.starts_at)<=time&&time<Date.parse(item.ends_at)&&item.allowed_operations.includes(operation));}
  function currentBudget(tenantId){const time=now().getTime();return [...budgets.values()].find(item=>item.tenant_id===tenantId&&item.status==='open'&&Date.parse(item.period_start)<=time&&time<Date.parse(item.period_end));}
  function activeLeases(tenantId){const time=now().getTime();return [...leases.values()].filter(item=>item.tenant_id===tenantId&&item.status==='active'&&Date.parse(item.expires_at)>time);}
  function claim(actor,tenantId){authorize(actor,tenantId,['service','admin']);const policy=policies.get(tenantId);if(!policy)return {claimed:false,reason:'policy_missing'};const candidates=[...jobs.values()].filter(item=>item.tenant_id===tenantId&&['queued','retry_scheduled'].includes(item.status)&&Date.parse(item.available_at)<=now().getTime()).sort((a,b)=>b.priority-a.priority||Date.parse(a.created_at)-Date.parse(b.created_at));if(!candidates.length)return {claimed:false,reason:'queue_empty'};const active=activeLeases(tenantId);if(active.length>=policy.max_global)return {claimed:false,reason:'tenant_concurrency_limit'};const budget=currentBudget(tenantId);if(!budget)return {claimed:false,reason:'budget_missing_or_closed'};for(const job of candidates){if(!activeWindow(tenantId,job.operation))continue;const operationCount=active.filter(item=>jobs.get(item.job_ref)?.operation===job.operation).length,siteCount=active.filter(item=>jobs.get(item.job_ref)?.site_id===job.site_id).length;if(operationCount>=policy.max_per_operation||siteCount>=policy.max_per_site)continue;if(budget.consumed_jobs+1>budget.max_jobs||budget.consumed_cost_units+job.cost_units>budget.max_cost_units){budget.status='exhausted';budget.updated_at=stamp();validate('operation-budget',budget);return {claimed:false,reason:'budget_exhausted'};}const time=stamp(),lease={schema_version:'0.1.0',lease_id:makeId('lease',job.job_id),tenant_id:tenantId,job_ref:job.job_id,worker_id:actor.actor_id,status:'active',acquired_at:time,heartbeat_at:time,expires_at:addSeconds(now(),policy.lease_seconds).toISOString(),released_at:null};job.status='leased';job.attempts++;job.lease_ref=lease.lease_id;job.updated_at=time;budget.consumed_jobs++;budget.consumed_cost_units+=job.cost_units;budget.updated_at=time;if(budget.consumed_jobs>=budget.max_jobs||budget.consumed_cost_units>=budget.max_cost_units)budget.status='exhausted';validate('worker-lease',lease);validate('orchestration-job',job);validate('operation-budget',budget);leases.set(lease.lease_id,lease);return {claimed:true,job:clone(job),lease:clone(lease)};}return {claimed:false,reason:'window_or_specific_concurrency_limit'};}
  function activeLeaseFor(actor,leaseId){const lease=leases.get(leaseId);if(!lease)throw fail('LEASE_NOT_FOUND','Lease not found');authorize(actor,lease.tenant_id,['service','admin']);if(actor.role!=='admin'&&lease.worker_id!==actor.actor_id)throw fail('LEASE_OWNER_MISMATCH','Worker does not own lease');if(lease.status!=='active'||Date.parse(lease.expires_at)<=now().getTime())throw fail('LEASE_INACTIVE','Lease is not active');return lease;}
  function heartbeat(actor,leaseId){const lease=activeLeaseFor(actor,leaseId),policy=policies.get(lease.tenant_id);lease.heartbeat_at=stamp();lease.expires_at=addSeconds(now(),policy.lease_seconds).toISOString();validate('worker-lease',lease);return clone(lease);}
  function releaseLease(lease){lease.status='released';lease.released_at=stamp();lease.heartbeat_at=stamp();validate('worker-lease',lease);}
  function complete(actor,leaseId){const lease=activeLeaseFor(actor,leaseId),job=jobs.get(lease.job_ref);job.status='succeeded';job.lease_ref=null;job.updated_at=stamp();releaseLease(lease);const record=idempotency.get(tenantKey(job.tenant_id,job.idempotency_key));record.status='completed';validate('idempotency-record',record);validate('orchestration-job',job);return clone(job);}
  function scheduleFailure(job,failureCode,safeSummary){if(!/^[A-Z][A-Z0-9_]{2,79}$/.test(failureCode))throw fail('FAILURE_CODE_INVALID','Failure code must be safe and closed');if(typeof safeSummary!=='string'||safeSummary.length<5||safeSummary.length>240)throw fail('FAILURE_SUMMARY_INVALID','Safe summary length invalid');if(job.attempts<job.max_attempts){const delay=Math.min(3600,30*(2**(job.attempts-1))),available=addSeconds(now(),delay),retry={schema_version:'0.1.0',retry_id:makeId('retry',job.job_id),tenant_id:job.tenant_id,job_ref:job.job_id,attempt:job.attempts,delay_seconds:delay,available_at:available.toISOString(),reason_code:failureCode,created_at:stamp()};job.status='retry_scheduled';job.available_at=retry.available_at;job.lease_ref=null;job.updated_at=stamp();validate('retry-schedule',retry);validate('orchestration-job',job);retries.set(retry.retry_id,retry);return {job:clone(job),retry:clone(retry),dead_letter:null};}const entry={schema_version:'0.1.0',entry_id:makeId('dlq',job.job_id),tenant_id:job.tenant_id,job_ref:job.job_id,failure_code:failureCode,safe_summary:safeSummary,attempts:job.attempts,replay_allowed:true,status:'open',created_at:stamp(),resolved_at:null};job.status='dead_lettered';job.lease_ref=null;job.updated_at=stamp();validate('dead-letter-entry',entry);validate('orchestration-job',job);deadLetters.set(entry.entry_id,entry);return {job:clone(job),retry:null,dead_letter:clone(entry)};}
  function failJob(actor,leaseId,{failure_code,safe_summary}){const lease=activeLeaseFor(actor,leaseId),job=jobs.get(lease.job_ref);releaseLease(lease);return scheduleFailure(job,failure_code,safe_summary);}
  function sweepExpiredLeases(actor,tenantId){authorize(actor,tenantId,['operator','admin']);const expired=[];for(const lease of leases.values()){if(lease.tenant_id!==tenantId||lease.status!=='active'||Date.parse(lease.expires_at)>now().getTime())continue;lease.status='expired';lease.released_at=stamp();validate('worker-lease',lease);const job=jobs.get(lease.job_ref);expired.push(scheduleFailure(job,'LEASE_EXPIRED','Worker lease expired before completion.'));}return expired;}
  function replayDeadLetter(actor,entryId){const entry=deadLetters.get(entryId);if(!entry)throw fail('DEAD_LETTER_NOT_FOUND','Dead-letter entry not found');authorize(actor,entry.tenant_id,['operator','admin']);if(entry.status!=='open'||!entry.replay_allowed)throw fail('REPLAY_NOT_ALLOWED','Dead-letter entry cannot be replayed');const old=jobs.get(entry.job_ref),result=enqueue(actor,{tenant_id:old.tenant_id,site_id:old.site_id,operation:old.operation,idempotency_key:`${old.idempotency_key}:replay:${old.attempts}`,payload_digest:old.payload_digest,desired_state_ref:old.desired_state_ref,priority:old.priority,max_attempts:old.max_attempts,cost_units:old.cost_units});entry.status='replayed';entry.resolved_at=stamp();validate('dead-letter-entry',entry);return result;}
  function runReconciliation(actor,{tenant_id,site_ids,budget_ref}){authorize(actor,tenant_id,['operator','admin']);const budget=budgets.get(budget_ref);if(!budget||budget.tenant_id!==tenant_id)throw fail('BUDGET_NOT_FOUND','Tenant budget not found');let noOp=0,ready=0,blocked=0,enqueued=0,duplicates=0;for(const siteId of site_ids){const plan=reconcileSite(actor,tenant_id,siteId);if(plan.status==='no_op'){noOp++;continue;}if(plan.status==='blocked'){blocked++;continue;}ready++;for(const operation of plan.operations){const result=enqueue(actor,{tenant_id,site_id:siteId,operation,idempotency_key:`${plan.idempotency_base}:${operation}`,payload_digest:sha({desired_state_ref:plan.desired_state_ref,operation}),desired_state_ref:plan.desired_state_ref,priority:operation==='verify_state'?40:70,max_attempts:5,cost_units:operation==='verify_state'?1:3});if(result.duplicate)duplicates++;else enqueued++;}}const value={schema_version:'0.1.0',run_id:makeId('reconr',tenant_id),tenant_id,total_sites:site_ids.length,no_op_sites:noOp,ready_sites:ready,blocked_sites:blocked,jobs_enqueued:enqueued,duplicates_suppressed:duplicates,budget_ref,status:blocked||!enqueued?'partially_enqueued':'enqueued',dry_run:true,created_by:actor.actor_id,created_at:stamp()};if(!site_ids.length)value.status='planned';validate('reconciliation-run',value);runs.set(value.run_id,value);return clone(value);}
  function queueSnapshot(actor,tenantId,budgetRef){authorize(actor,tenantId,['owner','operator','admin']);const budget=budgets.get(budgetRef);if(!budget||budget.tenant_id!==tenantId)throw fail('BUDGET_NOT_FOUND','Tenant budget not found');const ownJobs=[...jobs.values()].filter(item=>item.tenant_id===tenantId),counts=ownJobs.reduce((result,item)=>(result[item.status]=(result[item.status]||0)+1,result),{}),value={schema_version:'0.1.0',snapshot_id:makeId('queue',tenantId),tenant_id:tenantId,job_counts:counts,active_leases:activeLeases(tenantId).length,scheduled_retries:[...retries.values()].filter(item=>item.tenant_id===tenantId&&jobs.get(item.job_ref)?.status==='retry_scheduled').length,open_dead_letters:[...deadLetters.values()].filter(item=>item.tenant_id===tenantId&&item.status==='open').length,budget_ref:budget.budget_id,budget_remaining_jobs:Math.max(0,budget.max_jobs-budget.consumed_jobs),budget_remaining_cost_units:Math.max(0,budget.max_cost_units-budget.consumed_cost_units),generated_at:stamp()};validate('queue-snapshot',value);snapshots.set(value.snapshot_id,value);return clone(value);}
  function read(actor,tenantId){authorize(actor,tenantId,['owner','operator','admin']);const own=item=>item.tenant_id===tenantId;return {jobs:[...jobs.values()].filter(own).map(clone),idempotency:[...idempotency.values()].filter(own).map(clone),leases:[...leases.values()].filter(own).map(clone),retries:[...retries.values()].filter(own).map(clone),dead_letters:[...deadLetters.values()].filter(own).map(clone),windows:[...windows.values()].filter(own).map(clone),policies:[...policies.values()].filter(own).map(clone),budgets:[...budgets.values()].filter(own).map(clone),desired:[...desired.values()].filter(own).map(clone),observed:[...observed.values()].filter(own).map(clone),plans:[...plans.values()].filter(own).map(clone),runs:[...runs.values()].filter(own).map(clone),snapshots:[...snapshots.values()].filter(own).map(clone)};}
  return {configurePolicy,createWindow,createBudget,setDesiredState,observeState,reconcileSite,enqueue,claim,heartbeat,complete,failJob,sweepExpiredLeases,replayDeadLetter,runReconciliation,queueSnapshot,read,_state:{jobs,idempotency,leases,retries,deadLetters,windows,policies,budgets,desired,observed,plans,runs,snapshots}};
}
module.exports={createFleetOrchestrator,sha};
