'use strict';
const data=window.REVIEW_QUEUE;let selected=0;let record=null;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const actionLabels={schedule_conversation:'Agendar conversación',explore_catalog:'Explorar catálogo',request_valuation:'Solicitar tasación',visit_project:'Visitar proyecto',request_information:'Pedir información'};
function renderQueue(){const list=$('#queue-list');list.innerHTML=data.items.map((item,i)=>`<button class="queue-item ${i===selected?'active':''} ${item.inspection.can_approve_private_demo?'':'blocked'}" data-index="${i}"><span>${item.submission.identity.primary_category.replaceAll('-',' ')}</span><h3>${item.submission.identity.display_name.replace(/\s*[—-]\s*FICTICIO$/i,'')}</h3><p>${item.label}</p><footer><time>${item.received_label}</time><b>${item.inspection.can_approve_private_demo?'Listo':'Bloqueado'}</b></footer></button>`).join('');$$('.queue-item').forEach(button=>button.addEventListener('click',()=>{selected=Number(button.dataset.index);render();}));}
function render(){const item=data.items[selected],s=item.submission,x=item.inspection,ready=x.can_approve_private_demo;renderQueue();$('#review-name').textContent=s.identity.display_name.replace(/\s*[—-]\s*FICTICIO$/i,'');$('#review-category').textContent=s.identity.primary_category.replaceAll('-',' ');$('#review-meta').textContent=`${item.received_label} · Prioridad ${item.priority}`;$('#review-status').classList.toggle('blocked',!ready);$('#review-status').lastChild.textContent=ready?' Listo para revisar':' Requisitos pendientes';$('#summary-description').textContent=s.business_profile.description;$('#summary-customer').textContent=s.business_profile.ideal_customer;$('#summary-specialty').textContent=s.business_profile.specialty;$('#summary-areas').textContent=s.service_areas.join(' · ');$('#summary-action').textContent=actionLabels[s.business_profile.primary_action]||s.business_profile.primary_action;$('#service-count').textContent=`${s.services.length} servicio${s.services.length===1?'':'s'}`;$('#service-list').innerHTML=s.services.map((service,i)=>`<article class="service"><span>${String(i+1).padStart(2,'0')}</span><div><h4>${service.name}</h4><p>${service.description}</p></div></article>`).join('');$('#snapshot-hash').textContent=x.submission_hash;
 $('#evidence-list').innerHTML=x.checks.map(c=>`<article class="evidence-row ${c.status==='passed'?'':'failed'}"><i></i><div><strong>${c.label}</strong><p>${c.evidence}</p></div><span>${c.status==='passed'?'Conforme':'Pendiente'}</span></article>`).join('');
 $('#manual-checks').innerHTML=x.checks.map(c=>`<label class="manual-check"><input type="checkbox" data-check="${c.check_id}" ${c.status==='passed'?'checked':'disabled'}><span>${c.label}</span></label>`).join('');$('#approve').disabled=!ready;$('#approve').style.opacity=ready?'1':'.35';$('#notes').value='';$('#decision-title').textContent='Pendiente';showTab('overview');}
function showTab(id){$$('.tab').forEach(t=>{t.hidden=t.id!==id;t.classList.toggle('active',t.id===id)});$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));}
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
function makeRecord(decision){const item=data.items[selected],x=item.inspection;const checks=x.checks.map(c=>({...c,status:$(`[data-check="${c.check_id}"]`)?.checked?'passed':'failed',evidence:$(`[data-check="${c.check_id}"]`)?.checked?c.evidence:'Marcado como pendiente por el operador.'}));if(decision==='approved_private_demo'&&checks.some(c=>c.status==='failed'))return null;const reasons=decision==='approved_private_demo'?[]:checks.filter(c=>c.status==='failed').map(c=>c.check_id==='asset-rights'?'asset_rights_missing':'other').filter((v,i,a)=>a.indexOf(v)===i);if(decision!=='approved_private_demo'&&!reasons.length)reasons.push('other');return {schema_version:'0.1.0',review_id:`rev-${item.submission.submission_id.slice(4)}-${x.submission_hash.slice(0,12)}`,submission_id:item.submission.submission_id,business_id:item.submission.business_id,submission_hash:x.submission_hash,decision,checks,reason_codes:reasons,notes:$('#notes').value.trim()||null,reviewer:{reviewer_id:'operator-demo',role:'hazlocrecer_operator'},capabilities:{may_generate_private_demo:decision==='approved_private_demo',may_publish:false,may_index:false},created_at:new Date().toISOString()};}
function decide(decision){record=makeRecord(decision);if(!record)return;const approved=decision==='approved_private_demo';$('#decision-title').textContent=approved?'Demo privada aprobada':decision==='changes_requested'?'Cambios solicitados':'Expediente rechazado';$('#dialog-icon').textContent=approved?'✓':'!';$('#dialog-icon').style.background=approved?'var(--green)':'var(--accent)';$('#dialog-title').textContent=$('#decision-title').textContent;$('#dialog-copy').textContent=approved?'La aprobación está vinculada a esta instantánea. Cualquier cambio exige una nueva revisión.':'El expediente vuelve al propietario con motivos estructurados y conserva su historial.';$('#cap-demo').textContent=approved?'Permitida':'Bloqueada';$('#record-preview').textContent=JSON.stringify(record,null,2);const dialog=$('#decision-dialog');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');}
$('#approve').addEventListener('click',()=>decide('approved_private_demo'));$('#changes').addEventListener('click',()=>decide('changes_requested'));$('#reject').addEventListener('click',()=>decide('rejected'));
function close(){const dialog=$('#decision-dialog');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');}$('#close').addEventListener('click',close);$('#close-secondary').addEventListener('click',close);
$('#download-review').addEventListener('click',()=>{if(!record)return;const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=record.review_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0);});
$('#copy-hash').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#snapshot-hash').textContent);$('#copy-hash').textContent='Copiado';}catch{$('#copy-hash').textContent='No disponible';}});
render();
